(specifications->manifest
 '(
   ;; Need 1.88 and we're simply... testing
   ; "rust"
   "curl"
   "findutils"
   "grep"
   "gcc-toolchain"
   "pkg-config"
   "which"
   "zlib"
   "binaryen" ; This provides wasm-opt
   "node"
   "openssl"
   "yarn"
   "tar"
   "bash"
   "clojure"
   "clojure-tools"
   "git"
   "squashfs-tools"
   "nss"
   "jq"
   "make"
   "git"
   "python"
   ;; app image
   "gtk+"
   "libx11"
   "libglvnd"
   "vulkan-loader"
   "eudev"
   "alsa-lib"
   "dbus"
   "mesa"
   "fuse@2"
   "atk"
   "pulseaudio"
   "pipewire"
   "cups"
   "libxcomposite"
   "libxdamage"
   "wayland"
   "libxrandr"
   "fontconfig"
   "font-liberation"
   "font-google-noto-emoji"
   ;; ./squashfs-root/AppRun

   ;;
   "bash"
   "sed"
   "nss-certs"
  ; "rust:cargo"
    "coreutils"))
