
** Worker Core

**** Preface

As we've built this out it becomes apparent there would be a tangible gain to separating
the behavior that is ONLY rust-sdk operations from the UI code.
This would allow our start-up to feel much more instantaneous and incredibly more responsive.

As far as documentation goes, some of it will be ported from the prior implementations location
if applicable.

**** Imports

#+begin_src clojurescript :tangle ../../src/worker/core.cljs
(ns worker.core
  (:require
   [cljs-workers.worker :as worker]
   [promesa.core :as p]
   [taoensso.timbre :as log]
   [clojure.string :as str]
   [client.session-store :as session-store :refer [SessionStore]]
   ["ffi-bindings" :as sdk]
   [cljs.core.async.interop :refer-macros [<p!]]
   [cljs.core.async :refer [go]]
   [utils.net :refer [set-auth-context!] :as net]
   [worker.state :as state]
   [worker.spaces :as spaces]
   [worker.settings :as settings :refer [setup-encryption-listeners!]]
   [worker.timeline]
   [worker.members]
   [worker.composer]
   [worker.previews :as previews]
   [worker.call]
   [worker.rooms :as rooms]
   [worker-sci-runner :as sci]
   ))
#+end_src



**** Web Worker Examples

The mechanisms we use for the web worker are relatively straightforward
once you see how they are used. It's effectively a bunch of RPCs between
the main thread and the web worker. The web worker we want to handle
all rust-sdk interaction. This creates a nice segmented design between
the Rust SDK operations and the actual UI. It also provides a guide
for creating future multi-threaded operations for the client.

At some point I would like to revise the cljs-workers library, but
for now it is plenty sufficient for what we need. That said, it isn't
actually super complex as it is just a wrapper for common web worker
operations.

#+begin_src clojurescript

#+end_src


Honestly forgot to expand on these, but longer term plans would be
creating a nice binding layer and keeping the syntax just as fluid.
So we'll likely need to expand on our cljs-worker library for that.

#+begin_src clojurescript

#+end_src





**** Initialize the Wasm


So the first thing we need to do is actually initialize the
WASM.


#+begin_src clojurescript :tangle ../../src/worker/core.cljs
(worker/register :init-wasm
                 (fn [_]
                   (go
                     (try
                       (<p! (sdk/uniffiInitAsync))
                       {:status :success}
                       (catch :default e
                         {:status :error :msg (str e)})))))
#+end_src





**** Starting the Client

This is more or less where we start our journey of actually interfacing with the
matrix-rust-sdk WASM bindings. Since the client initialization is relatively 'easy'
compared to actually making use of the information and state internally.

It seems that WASM needs camelCase after it is converted from Rust.
So entries_handle becomes entriesStream

We started with view models but eventually moved towards more Clojure native
implementations that align better with reframe to make writing more idiomatic.
As such it becomes much simpler to initialize and manage the state.
Though this does mean we'll retroactively need to add methods to do certain
behaviors against the Rust sdk.

This is a good spot to explore what the Rust FFI exposes to use in the client as well.
Such as the space_service is useful to avoid manaul calculation of the spaces vs rooms.
Well. So we thought anyway. It appears to not be as innately useful as initially thought.


***** Building a Client object

This actually was relatively quick to figure out, but the client builder merely takes
a few options. It is fairly dynamically configurable as is. Still, more time was spent
ensuring this could be used for both login and restore session.
So we allow nullish options in passphrase and store-id and if they're null
we generate them. If they are not null then we read from the value passed.
At the end of the process once the client object is 'built' we try to run the
login or restoreSession method depending on what is passed through to restore-or-login!


Now later we need some helper functions to determine which session we are currently in.
This is a functionality useful to supporting multiple accounts at once.

#+begin_src clojurescript :tangle ../../src/worker/core.cljs
(defn maybe-local-session []
  (p/let [store (SessionStore.)
          sessions (.loadSessions store)
          user-id (first (js/Object.keys sessions))]
    (when user-id (aget sessions user-id))))

(defn get-specific-session [target-user-id]
  (p/let [store (SessionStore.)
          sessions (.loadSessions store)]
    (aget sessions target-user-id)))

#+end_src


Now this is actually the method that builds our client object.
Some important little notes I can add here, but the sliding sync
version really just determines whether it is enabled or not.
If the version is anything but 0 then it'll use Sliding Sync.

#+begin_src clojurescript :tangle ../../src/worker/core.cljs
(defn build-client [hs passphrase? store-id? restore-or-login!]
  (p/let [sdk-root (if (.-ClientBuilder sdk) sdk (.-default sdk))
          ClientBuilder (.-ClientBuilder sdk-root)
          SSVBuilder    (.-SlidingSyncVersionBuilder sdk-root)
          IDBBuilder    (.-IndexedDbStoreBuilder sdk-root)
          store (SessionStore.)
          store-id   (or store-id? (.generateStoreId store))
          passphrase (or passphrase? (.generatePassphrase store))
          store-name (.getStoreName store store-id)
          store-config (-> (new IDBBuilder store-name)
                           (.passphrase passphrase))
          builder (-> (new ClientBuilder)
                      (.serverNameOrHomeserverUrl hs)
                      (.indexeddbStore store-config)
                      (.autoEnableCrossSigning true)
                      (cond-> (nil? passphrase?)
                        (.slidingSyncVersionBuilder (.-DiscoverNative SSVBuilder))))
          client  (.build builder)
          _ (restore-or-login! client)
          session (.session client)
          _ (or passphrase? (.save store session passphrase store-id))]
     client))
#+end_src



Now we can provide our application initialization and attempt to restore the previous login session.
If the previous login session is found, then we start-syncing and kick off the client's run.
#+begin_src clojurescript :tangle ../../src/worker/core.cljs
(worker/register :bootstrap
  (fn [{:keys [target-user-id]}]
    (go
      (try
        (<p! (p/let [data? (if target-user-id
                             (get-specific-session target-user-id)
                             (maybe-local-session))]
               (if data?
                 (p/let [session (.-session data?)
                         hs-url  (.-homeserverUrl session)
                         uid     (.-userId session)
                         token   (.-accessToken session)
                         dev-id  (.-deviceId session)
                         client  (build-client hs-url
                                               (.-passphrase data?)
                                               (.-storeId data?)
                                               #(.restoreSession % session))]
                   (reset! state/!media-cache nil)
                   (reset! state/!client client)
                   (set-auth-context! token hs-url)
                   {:status :success
                    :user-id uid
                    :hs-url hs-url
                    :session-data {:accessToken token
                                   :homeserverUrl hs-url
                                   :userId uid
                                   :deviceId dev-id}})
                 {:status :empty})))
        (catch :default e
          {:status :error :msg (str e)})))))


(worker/register :login
                 (fn [{:keys [hs user pass]}]
                   (go
                     (try
                       (<p! (p/let [client  (build-client hs nil nil #(.login % user pass))
                                    session (.session client)
                                    uid     (.-userId session)
                                    hs-url  (.-homeserverUrl session)
                                    token   (.-accessToken session)
                                    dev-id  (.-deviceId session)]
                              (reset! state/!client client)
                              (reset! state/!media-cache nil)
                              {:status :success
                               :user-id uid
                               :hs-url hs-url
                               :session-data {:accessToken token
                                              :homeserverUrl hs-url
                                              :userId uid
                                              :deviceId dev-id}}))
                       (catch :default e
                         {:status :error :msg (str e)})))))

#+end_src


This initializes many of the client services. They are somewhat better described
in their respective files, but in short the room list service handles
informing the sdk on what to sync. We just choose allRooms for ease now. I'm sure
that isn't exactly the most effective solution, but it'll do for now.

The space service would be more useful if the Space Room children worked properly,
but I'll probably have complaints about that throughout the project.
Either way, it is still useful for creating the parent-child relationships for
spaces and their rooms.

The sync service is the actual service that tries to sync with the home server.

#+begin_src clojurescript :tangle ../../src/worker/core.cljs
(worker/register :start-sync
                 (fn [_]
                   (go
                     (try
                       (<p! (p/let [client       @state/!client
                                    sync-service (-> (.syncService client) (.withOfflineMode) (.finish))
                                    rls-instance (.roomListService sync-service)
                                    room-list    (.allRooms rls-instance)
                                    space-service (.spaceService client)]
                              (rooms/start-room-list-sync! client room-list space-service)
                              (.start sync-service)
                              (spaces/init-space-service! client)
                              (setup-encryption-listeners! client)
                              )

                            )
                       {:status :success}
                       (catch :default e
                         {:status :error :msg (str e)})))))
#+end_src









Fetching the profile is a promise, so it is reasonable for now
to separate it into its own sort of call instead of just
bundling in the client context. I may revisit though.
#+begin_src clojurescript :tangle ../../src/worker/core.cljs
(worker/register :fetch-profile
                 (fn [_]
                   (go
                     (try
                       (let [client  @state/!client
                             user-id (.-userId (.session client))
                             profile (<p! (.getProfile client user-id))]
                         {:status :success
                          :profile {:user-id user-id
                                    :display-name (.-displayName profile)
                                    :avatar-url   (.-avatarUrl profile)}})
                       (catch :default e
                         {:status :error :msg (str e)})))))
#+end_src

This is more or less the same info we store in a session object, so we just neatly
want to provide the UI a way to request this info. It'll use it in a great number
of locations.
#+begin_src clojurescript :tangle ../../src/worker/core.cljs
(worker/register :get-client-context
                 (fn [_]
                   (go
                     (try
                       (if-let [client @state/!client]
                         (let [session (.session client)]
                           {:status :success
                            :session {:userId        (.-userId session)
                                      :deviceId      (.-deviceId session)
                                      :accessToken   (.-accessToken session)
                                      :homeserverUrl (.-homeserverUrl session)}})
                         {:status :error :msg "No active client"})
                       (catch :default e
                         {:status :error :msg (str e)})))))
#+end_src


***** Logging out

Currently the WASM doesn't let go of the DBs. For now we'll leave it orphaning... but
we need to look for the proper method to unmount them so to speak.

****** TODO Look for proper method to unmount IDBs from WASM in FFI bindings

#+begin_src clojurescript :tangle ../../src/worker/core.cljs
(worker/register :logout-client
  (fn [{:keys [user-id]}]
    (go
      (try
        (when-let [client @state/!client]
          (<p! (.logout client))
          (when (fn? (.-free client))
            (.free client))
          (reset! state/!client nil))

        (<p! (p/delay 1500))

        (when user-id
          (let [store (session-store/->SessionStore)]
            (<p! (.clear store user-id))
            (log/info "Worker successfully wiped OPFS session for:" user-id)))

        {:status "success"}
        (catch :default e
          (log/error "Worker Logout Panic:" e)
          {:status "error" :msg (str e)})))))




#+end_src

**** SCI Runner (not walker)

This just exposes the method to SCI so we can register
functions in the web worker from a plugin context.


#+begin_src clojurescript :tangle ../../src/worker/core.cljs

(worker/register :evaluate-worker-form
  (fn [{:keys [form-str]}]
    (sci/evaluate-worker-form form-str)))

#+end_src

**** Kickoff

Now we need to kick off the bootstrapping immediately, so we do so here.
#+begin_src clojurescript :tangle ../../src/worker/core.cljs
(worker/bootstrap)
#+end_src



