
** Worker Rooms

**** Preface


**** Imports


#+begin_src clojurescript :tangle ../../src/worker/rooms.cljs
(ns worker.rooms
  (:require
   [cljs-workers.worker :as worker]
   [clojure.string :as str]
   [promesa.core :as p]
   [taoensso.timbre :as log]
   ["ffi-bindings" :as sdk :refer [RoomListEntriesDynamicFilterKind RoomListFilterCategory]]
   [cljs.core.async.interop :refer-macros [<p!]]
   [client.diff-handler :refer [apply-matrix-diffs]]
   [navigation.rooms.room-summary :refer [build-room-summary]]
   [worker.state :as state])
  (:require-macros
   [cljs.core.async.macros :refer [go]]))
#+end_src


**** Sauce


**** Atoms

#+begin_src clojurescript :tangle ../../src/worker/rooms.cljs
(defonce !ui-controller (atom nil))
(defonce !bg-controller (atom nil))

(defonce !ui-list-result (atom nil))
(defonce !bg-list-result (atom nil))

(defonce !home-rooms (atom #js []))
(defonce !home-mutex (atom (p/resolved nil)))

(defonce !bg-rooms-array (atom #js []))
(defonce !bg-room-mutex (atom (p/resolved nil)))

(defonce !parent-queue (atom {}))
(defonce !parent-cache (atom {}))

(defonce !preview-promises (atom {}))
#+end_src


**** Parent Child Mapping Space Rooms

We need to create a queuing mechanism to properly load in the parentage for rooms.
If we do this correctly then we can build out the graph ourselves for determining
what a Space structure is. Currently we're using the assumption that the first
parent is the direct expected parent, but at some point we may want to try
to support more dynamic behavior.

Now we do this because when the Rust SDK starts, the SpaceService is still waiting
for the RoomListService to fully populate before it tries to make a DAG of the
Spaces. Even when it makes the DAG we can't really directly interact with it, so
instead we use the fact it exposes the parentage through a method named
joinedParentsOfChild. This is our key to building this 'tree' out.

Because we need the tree to calculate things from Space room list display
to calculating the notification total in the spaces, we do need to ensure
this works... and works well. So we build out our list and then pass it to our
queue here which periodically retries to populate the parentage for the given room.
After a number of fails we just simply determine that the room is an orphan and
remove it from the queue as well.

#+begin_src clojurescript :tangle ../../src/worker/rooms.cljs
(defn enqueue-parent-check! [room-id]
  (swap! !parent-queue update room-id #(if % % 0)))


(defn process-parent-queue! [client space-service]
  (let [queue @!parent-queue]
    (when (and space-service (seq queue))
      (-> (p/all
           (map (fn [[id attempts]]
                  (if-let [room (some #(when (= (:id %) id) %) @!bg-rooms-array)]
                    (-> (.joinedParentsOfChild space-service id)
                        (p/then (fn [parents]
                                  (if (pos? (alength parents))
                                    {:id id :status :success :parents parents :room room}
                                    {:id id :status :retry :attempts (inc attempts)})))
                        (p/catch (fn [e]
                                   (js/console.error "Queue FFI fail for" id e)
                                   {:id id :status :retry :attempts (inc attempts)})))
                    (p/resolved {:id id :status :drop})))
                queue))
          (p/then (fn [results]
                    (doseq [res results]
                      (when (= (:status res) :success)
                        (let [parents (:parents res)
                              first-parent-id (.-roomId (aget parents 0))]

                          (swap! !parent-cache assoc (:id res)
                                 {:parents parents
                                  :first-parent-id first-parent-id})

                          (swap! !bg-rooms-array
                                 (fn [rooms]
                                   (mapv (fn [r]
                                           (if (= (:id r) (:id res))
                                             (assoc r :first-parent-id first-parent-id)
                                             r))
                                         rooms)))

                          (worker/stream! {:type "room-parent-resolved"
                                           :room-id (:id res)
                                           :first-parent-id first-parent-id}))))

                    (let [to-keep (reduce (fn [acc res]
                                            (if (and (= (:status res) :retry) (< (:attempts res) 3))
                                              (assoc acc (:id res) (:attempts res))
                                              acc))
                                          {} results)]
                      (reset! !parent-queue to-keep)
                      (when (seq to-keep)
                        (js/setTimeout #(process-parent-queue! client space-service) 2000)))))))))
#+end_src


**** Loading Previews (Calls for now)

#+begin_src clojurescript :tangle ../../src/worker/rooms.cljs
(defn- extract-preview [preview-ffi]
  (when preview-ffi
    (let [is-call? (try
                     (let [info (.info preview-ffi)
                           type (some-> info .-roomType)]
                       (boolean
                        (and (= "Custom" (some-> type .-tag))
                             (= "org.matrix.msc3417.call" (some-> type .-inner .-value)))))
                     (catch :default _ false))]
      {:is-call? is-call?})))


(worker/register :get-room-preview
                 (fn [{:keys [room-id]}]
                   (go
                     (try
                       (if-let [preview-p (get @!preview-promises room-id)]
                         (let [preview-ffi (<p! preview-p)]
                           (if preview-ffi
                             {:status :success :preview (extract-preview preview-ffi)}
                             {:status :error :msg "Preview resolved to nil"}))
                         {:status :error :msg "No preview promise retained for this room"})
                       (catch :default e
                         {:status :error :msg (str e)})))))
#+end_src


**** Parsing Rust Room Objects

Parse the room into a useful CLJS form. Otherwise we have to work with
a JS room which isn't ideal. We could try being a bit more consistent
on this stipulation... but it isn't entirely essential now.

Unsettlingly, we use the space-service to determine the parentage
as we can't appropriately populate the SpaceRoomList.

Adding to this we also generate a room preview right here as it
makes more sense to do so during the room parsing. Odds are
in future versions we can more easily grab the room type, but
this is convenient enough... I guess... for now.

It is important to note we are leaving this as an unfulfilled promise.
If we tried to fulfill them all right here we add a potentially
significant delay that the user doesn't really care about. Instead
we can resolve that promise whenever we actually want to interact with
data associated with the RoomPreview. Otherwise it shouldn't matter.

#+begin_src clojurescript :tangle ../../src/worker/rooms.cljs
(defn parse-room [client space-service room-interface]
  (p/let [room-info     (if (fn? (.-roomInfo room-interface)) (.roomInfo room-interface) nil)
          latest-event  (.latestEvent room-interface)
          room-id       (if room-info (.-id room-info) "unknown-room")]
    (try
      (let [_ (when (and client (exists? (.-getRoomPreviewFromRoomId client)) (not= room-id "unknown-room"))
                (when-not (contains? @!preview-promises room-id)
                  (let [preview-p (try
                                    (p/promise (.getRoomPreviewFromRoomId client room-id #js []))
                                    (catch :default e
                                      (p/resolved nil)))]
                    (swap! !preview-promises assoc room-id preview-p)
                    (-> preview-p
                        (p/then (fn [ffi]
                                  (when-let [clean-preview (extract-preview ffi)]
                                    (worker/stream! {:type "room-preview-resolved"
                                                     :room-id room-id
                                                     :preview clean-preview}))))
                        (p/catch #(log/error "Background preview fetch failed:" %))))))
            summary       (build-room-summary room-interface room-info latest-event)
            cached-parent (get @!parent-cache room-id)
            first-parent  (:first-parent-id cached-parent)]
        (-> (js->clj summary :keywordize-keys true)
            (assoc :id room-id)
            (cond-> first-parent (assoc :first-parent-id first-parent))))
      (catch :default e
        (log/error "Failed to parse room:" room-id e)
        {:id room-id :name "Error parsing room"}))))

#+end_src




**** Rust Filters

We previously had filters in initial builds, but when we opted for a full reframe
style implementation we removed them. We'll add them back here. Effectively calling these
informs the Rust SDK that you wish to get a new Room List set.
As a result on space swapping we ALWAYS want to ensure we set back to "All" as
we rely on the list for our room list view behaviors (even if the space loads a
'dumb' version).

#+begin_src clojurescript :tangle ../../src/worker/rooms.cljs
(defn get-rust-filter [filter-id]
  (case filter-id
    "unread"
    (RoomListEntriesDynamicFilterKind.All.
     #js {:filters #js [(RoomListEntriesDynamicFilterKind.Unread.)
                        (RoomListEntriesDynamicFilterKind.DeduplicateVersions.)]})
    "people"
    (RoomListEntriesDynamicFilterKind.All.
     #js {:filters #js [(RoomListEntriesDynamicFilterKind.Category. #js {:expect RoomListFilterCategory.People})
                        (RoomListEntriesDynamicFilterKind.Joined.)
                        (RoomListEntriesDynamicFilterKind.DeduplicateVersions.)]})
    "favourite"
    (RoomListEntriesDynamicFilterKind.All.
     #js {:filters #js [(RoomListEntriesDynamicFilterKind.Favourite.)
                        (RoomListEntriesDynamicFilterKind.DeduplicateVersions.)]})
    "other"
    (RoomListEntriesDynamicFilterKind.All.
     #js {:filters #js [(RoomListEntriesDynamicFilterKind.Category. #js {:expect RoomListFilterCategory.Group})
                        (RoomListEntriesDynamicFilterKind.NonLeft.)
                        (RoomListEntriesDynamicFilterKind.DeduplicateVersions.)]})

    (RoomListEntriesDynamicFilterKind.All.
     #js {:filters #js [(RoomListEntriesDynamicFilterKind.NonLeft.)
                        (RoomListEntriesDynamicFilterKind.DeduplicateVersions.)]})))
#+end_src

#+begin_src clojurescript :tangle ../../src/worker/rooms.cljs
(worker/register :set-room-filter
  (fn [{:keys [filter-id]}]
    (if-let [ctrl @!ui-controller]
      (do
        (.setFilter ctrl (get-rust-filter filter-id))
        (.addOnePage ctrl)
        {:status :success})
      {:status :error :msg "Controller not initialized"})))
#+end_src


**** Home Room Lists

Prior we had a very verbose and repeated diffs check, but
as our timeline, spaces, and room list all share the same
general patterns to handling diffs we can consolidate them and
call them like so.
So all we need to do is ask reframe for the current global rooms
and call the diff check against those rooms and the updates
to set the "new" global rooms. This will make our global list
refresh automatically.
Later we can apply filters on it to induce specific behavior
like creating a DM grouping.

To add onto this, but we use a mutex to ensure that the rust-sdk
doesn't ever end up in a state where the diffs aren't readily
available to refresh our window. We don't slow the rust-sdk down,
but instead establish a queue for our code to process them
and notify reframe properly.

#+begin_src clojurescript :tangle ../../src/worker/rooms.cljs
(defn apply-home-diffs-async! [client space-service updates]
  (swap! !home-mutex
         (fn [prev-promise]
           (p/then prev-promise
                   (fn []
                     (-> (apply-matrix-diffs @!home-rooms updates #(parse-room client space-service %))
                         (p/then (fn [next-rooms]
                                   (reset! !home-rooms next-rooms)
                                   (worker/stream! {:type "home-rooms-diff" :rooms next-rooms})))
                         (p/catch (fn [err] (log/error "Global Diff Panic:" err)))))))))

#+end_src



**** Global Room Lists


This is our source of truth list. We don't ever mutate this with a filter
or expect to reload it. The only mutations are the ones the Rust SDK sends
us to update the shape of the list itself.
We also initialize the parent evaluation here so we can build out our
space trees


It's becoming apparent that swapping filters is really not great for performance.
Instead we should explore what a multi-subscription design would look like.
If we can just keep DMs fresh and an all list fresh... We'll be doing great.
Issue is when using filters on the all list... is that list is literally
our source of truth. So we really should just keep it pure.
If we want to filter a background list then we can do whatever to that one.

I initially wrote this and a comment mentioning that I didn't think we could
nicely do the parent-child relationship mapping, however, having gone back
and revised a good bit it is now easily done here and we generate a nice
mapped structure for use everywhere. So we can easily look up rooms at O(1)
as well.

#+begin_src clojurescript :tangle ../../src/worker/rooms.cljs
(defn apply-bg-rooms-diffs! [client space-service updates]
  (swap! !bg-room-mutex
         (fn [prev-promise]
           (p/then prev-promise
                   (fn []
                     (-> (apply-matrix-diffs @!bg-rooms-array updates #(parse-room client space-service %))
                         (p/then (fn [next-rooms]
                                   (reset! !bg-rooms-array next-rooms)
                                   (worker/stream! {:type "bg-rooms-diff" :rooms next-rooms})

                                   (doseq [r next-rooms]
                                     (when-not (:first-parent-id r)
                                       (enqueue-parent-check! (:id r))))
                                   (process-parent-queue! client space-service)))
                         (p/catch (fn [err] (log/error "Global Diff Panic:" err)))))))))
#+end_src




**** Initializing Room List Syncing

We can simplify (and diverge) from Aurora's implementation as View models are very rigid
and lock us into a certain pattern. Instead we'll just let reframe know the diff and let
it handle re-rendering directly.
This can be broken part a bit more for labeling purpose. For now though, it is easily
described as creating a set of entries (initializing the sliding sync frame size) and
then attaching an onUpdate to easily refresh those entries without much effort.
We apply a filter to ensure we don't end up with any duplication on the resulting room list and
apply it. Then we prompt the app to give us the first page for the controller.

#+begin_src clojurescript :tangle ../../src/worker/rooms.cljs
(defn start-room-list-sync! [client room-list space-service]
  (p/let [ui-result (.entriesWithDynamicAdapters room-list 200
                                                     #js {:onUpdate #(apply-home-diffs-async! client space-service %)})
          ui-controller (.controller ui-result)
          bg-result (.entriesWithDynamicAdapters room-list 200
                                                     #js {:onUpdate #(apply-bg-rooms-diffs! client space-service %)})
          bg-controller (.controller bg-result)]
    (reset! !ui-controller ui-controller)
    (reset! !bg-controller bg-controller)

    (reset! !ui-list-result ui-result)
    (reset! !bg-list-result bg-result)

    (.setFilter ui-controller (get-rust-filter "people"))
    (.addOnePage ui-controller)

    (.setFilter bg-controller (get-rust-filter "all"))
    (.addOnePage bg-controller)))
#+end_src

#+begin_src clojurescript :tangle ../../src/worker/rooms.cljs


(worker/register :paginate-room-list
  (fn [_]
    (if-let [ctrl @!ui-controller]
      (do (.addOnePage ctrl) {:status :success})
      {:status :error :msg "Controller not initialized"})))




#+end_src



**** Fetching the Space Hierarchy

Bit of an issue in the version of the sdk, but since we do need some state
events (as the sdk lacks a coherent method) we must do some operations
ourself. When we update I would imagine some of these will disappear.
For now though, to determine the actual hierarchy we need the hierarchy
end point itself which will easily allow us to sort Spaces.
We do eventually need to clean up the filter as this will cause
repeat fetches for the space rooms for now.

#+begin_src clojurescript :tangle ../../src/worker/rooms.cljs
(worker/register :fetch-space-hierarchy
                 (fn [{:keys [space-id]}]
                   (go
                     (try
                       (let [client     @state/!client
                             base-url   (.homeserver client)
                             session    (.session client)
                             token      (.-accessToken session)
                             clean-base (str/replace base-url #"/+$" "")
                             url        (str clean-base "/_matrix/client/v1/rooms/" space-id "/hierarchy")
                             resp       (<p! (js/fetch url #js {:headers #js {"Authorization" (str "Bearer " token)}}))
                             json       (<p! (.json resp))]
                         (if (.-ok resp)
                           {:status :success :rooms (:rooms (js->clj json :keywordize-keys true))}
                           {:status :error :msg (str "Hierarchy fetch failed: " (.-status resp))}))
                       (catch :default e
                         {:status :error :msg (str e)})))))
#+end_src
