
** Worker Settings

**** Preface

This actual pertains to functionalities that mostly are to be interacted
within the settings interface. Some examples would be verification status,
device management, user management, notification status, and more.

**** Imports

#+begin_src clojurescript :tangle ../../src/worker/settings.cljs
(ns worker.settings
  (:require
   [cljs-workers.worker :as worker]
   [client.session-store :refer [SessionStore]]
   [worker.state :as state]
   [utils.net :refer [set-auth-context!] :as net]
   [promesa.core :as p]
   [taoensso.timbre :as log]
   [clojure.string :as str]
   ["ffi-bindings" :as sdk]
   [cljs.core.async.interop :refer-macros [<p!]]
   [cljs.core.async :refer [go]]
   )
  )
#+end_src





***** Session Recovery (Verification)

The Rust-SDK actually neatly handles recovery keys. So we just pass it the module
it expects and then the recovery key... and that actually is it. It'll handle
Everything else from there.


#+begin_src clojurescript :tangle ../../src/worker/settings.cljs
(worker/register :recover-session
                 (fn [{:keys [recovery-key]}]
                   (go
                     (try
                       (if-let [client @state/!client]
                         (let [encryption-module (.encryption client)]
                           (log/info "Attempting session recovery with key length:" (count recovery-key))
                           (<p! (.recover encryption-module recovery-key))
                           (log/info "Session recovery successful!")
                           {:status :success})
                         {:status :error :msg "No active client"})
                       (catch :default e
                         (let [err-str (or (.-message e) (str e))]
                           (log/error "Recovery FFI Panic:" err-str)
                           {:status :error :msg err-str}))))))

(defonce !recovery-listener-handle (atom nil))

(defn setup-encryption-listeners! [client]
  (let [encryption-module (.encryption client)
        listener-obj #js {:onUpdate
                          (fn [state-enum]
                            (let [state-kw (cond
                                             (or (= state-enum 1) (= state-enum "Enabled"))    :enabled
                                             (or (= state-enum 2) (= state-enum "Disabled"))   :disabled
                                             (or (= state-enum 3) (= state-enum "Incomplete")) :incomplete
                                             :else :unknown)]
                              (log/info "Worker stream: Recovery state changed to:" state-enum "->" state-kw)
                              (worker/stream! {:type "recovery-state-update"
                                               :state state-kw})))}
        handle (.recoveryStateListener encryption-module listener-obj)]
    (reset! !recovery-listener-handle handle)))
#+end_src




***** Account Aggregation

For multi-account we need to neatly be able to aggregate the accounts we're signed
into.

#+begin_src clojurescript :tangle ../../src/worker/settings.cljs
(worker/register :get-available-accounts
                 (fn [_]
                   (go
                     (try
                       (<p! (p/let [store (SessionStore.)
                                    sessions (.loadSessions store)]
                              (let [accs (for [uid (js/Object.keys sessions)
                                               :let [data (aget sessions uid)
                                                     session (.-session data)]]
                                           {:userId uid
                                            :hs_url (.-homeserverUrl session)})]
                                {:status :success :accounts (vec accs)})))
                       (catch :default e
                         {:status :error :msg (str e)})))))
#+end_src


And of course we need to be able to grab the account data for an account as well.
#+begin_src clojurescript :tangle ../../src/worker/settings.cljs
(worker/register :get-account-data
                 (fn [{:keys [event-type]}]
                   (go
                     (try
                       (if-let [client @state/!client]
                         (let [data (<p! (.accountData client event-type))]
                           {:status :success :data data})
                         {:status :error :msg "No active client"})
                       (catch :default e
                         {:status :error :msg (str e)})))))
#+end_src





***** Pushers

Having written the service worker and notifications for another client before
these aren't exactly too different. I'll come back to these and document them
a bit better though. The service worker itself is decently covered though.

Looked closer at it, but I'm not entirely sure the SDK can handle web pushers, so
we will leave this as is.
Went ahead and at least used deletePusher as it doesn't really care what the pusher is.
If we could unify both I'll change it. For now though this remains.

I didn't see any getPushers like the JS-sdk has, so for now I suppose we can't
neatly provide clearing all the old pushers... So I guess we shouldn't mess up? Haha.

https://spec.matrix.org/latest/client-server-api/#get_matrixclientv3pushers

However, we could just hit this endpoint and delete them that way all the same.

#+begin_src clojurescript :tangle ../../src/worker/settings.cljs
(worker/register :register-pusher
  (fn [{:keys [p256dh auth endpoint app-id push-url app-name lang pushkey is-native platform]}]
    (go
      (try
        (let [client     @state/!client
              hs-url     (.homeserver client)
              token      (.-accessToken (.session client))
              clean-base (str/replace hs-url #"/+$" "")
              url        (str clean-base "/_matrix/client/v3/pushers/set")
              payload    (cond
                           (and is-native (= platform "ios"))
                           {:kind "http"
                            :app_id app-id
                            :pushkey pushkey
                            :app_display_name app-name
                            :device_display_name "iOS Device"
                            :lang lang
                            :append false
                            :data {:url push-url
                                   :format "event_id_only"
                                   :default_payload {:aps {:alert {:loc-key "New Message"}
                                                           :sound "default"
                                                           :badge 1
                                                           :content-available 1}}}}
                           (and is-native (= platform "android"))
                           {:kind "http"
                            :app_id app-id
                            :pushkey pushkey
                            :app_display_name app-name
                            :device_display_name "Android Device"
                            :lang lang
                            :append false
                            :data {:url push-url
                                   :format "event_id_only"
                                   }}
                           :else
                           {:kind "http"
                            :app_id app-id
                            :pushkey p256dh
                            :app_display_name app-name
                            :device_display_name "Web Browser"
                            :lang lang
                            :append false
                            :data {:url push-url
                                   :events_only true
                                   :endpoint endpoint
                                   :p256dh p256dh
                                   :auth auth}})
              resp       (<p! (net/fetch url #js {:method "POST"
                                                  :headers #js {"Authorization" (str "Bearer " token)
                                                                "Content-Type" "application/json"}
                                                  :body (js/JSON.stringify (clj->js payload))}))]
          (if (.-ok resp)
            {:status "success"}
            (let [err-body (<p! (.json resp))]
              {:status "error" :msg err-body})))
        (catch :default e
          {:status "error" :msg (str e)})))))

(worker/register :remove-pusher
  (fn [{:keys [pushkey app-id]}]
    (go
      (try
        (let [client      @state/!client
              identifiers #js {:pushkey pushkey :appId app-id}]
          (<p! (.deletePusher client identifiers))
          {:status "success"})
        (catch :default e
          {:status "error" :msg (str e)})))))


(worker/register :clear-all-pushers
  (fn [_]
    (go
      (try
        (let [client     @state/!client
              hs-url     (.homeserver client)
              token      (.-accessToken (.session client))
              clean-base (str/replace hs-url #"/+$" "")
              url        (str clean-base "/_matrix/client/v3/pushers")
              resp       (<p! (net/fetch url #js {:method "GET"
                                                  :headers #js {"Authorization" (str "Bearer " token)}}))]
          (if-not (.-ok resp)
            (let [err-body (<p! (.json resp))]
              {:status "error" :msg err-body})
            (let [data    (<p! (.json resp))
                  pushers (:pushers (js->clj data :keywordize-keys true))]
              (doseq [p pushers]
                (let [pushkey (:pushkey p)
                      app-id  (:app_id p)
                      identifiers #js {:pushkey pushkey :appId app-id}]
                  (try
                    (<p! (.deletePusher client identifiers))
                    (catch :default e
                      (log/warn "Failed to delete pusher" pushkey ":" e)))))
              {:status "success"})))
        (catch :default e
          {:status "error" :msg (str e)})))))

#+end_src

