
** Worker Spaces

**** Preface


**** Imports

#+begin_src clojurescript :tangle ../../src/worker/spaces.cljs
(ns worker.spaces
  (:require
   [cljs-workers.worker :as worker]
   [promesa.core :as p]
   [taoensso.timbre :as log]
   [client.diff-handler :refer [apply-matrix-diffs]]
   [worker.state :as state]
   [worker.rooms :refer [process-parent-queue!]]
   [cljs.core.async :refer [<!]]
   [cljs.core.async.interop :refer-macros [<p!]])
  (:require-macros
   [cljs.core.async.macros :refer [go]]))
#+end_src


**** Atoms

#+begin_src clojurescript :tangle ../../src/worker/spaces.cljs
(defonce !space-service (atom nil))
(defonce !global-space-sub (atom nil))
(defonce !space-list-subs (atom {}))

(defonce !global-spaces-array (atom #js []))
(defonce !global-space-mutex (atom (p/resolved nil)))

(defonce !space-rooms-arrays (atom {}))
(defonce !space-rooms-mutexes (atom {}))
#+end_src


**** Parsing Space Children

Handle space children which are much simpler than just room summaries.
It is interesting that they aren't just room objects, but they
aren't particularly useful in the current sdk.


#+begin_src clojurescript :tangle ../../src/worker/spaces.cljs
(defn parse-space-child [obj]
  (let [id       (or (.-roomId obj) (.-id obj))
        name     (or (.-displayName obj) (.-name obj) "Unknown")
        type-tag (some-> obj .-roomType .-tag)]
    (when id
      {:id         id
       :name       name
       :avatar-url (.-avatarUrl obj)
       :is-space?  (= type-tag "Space")
       })))
#+end_src



**** Diff Handling

We'll make this behavior global later. Room, timeline, and spaces can use it the same.
We describe it in the method doc, but effectively it provides a buffer to the reframe
without slowing don't the rust-sdk.
#+begin_src clojurescript :tangle ../../src/worker/spaces.cljs

(defn apply-space-rooms-diffs! [space-id updates]
  (swap! !space-rooms-mutexes update space-id #(or % (atom (p/resolved nil))))
  (let [!mutex (get @!space-rooms-mutexes space-id)]
    (swap! !mutex
           (fn [prev-promise]
             (p/then prev-promise
                     (fn []
                       (let [current-rooms (get @!space-rooms-arrays space-id #js [])]
                         (-> (apply-matrix-diffs current-rooms updates parse-space-child)
                             (p/then (fn [next-rooms]
                                       (swap! !space-rooms-arrays assoc space-id next-rooms)
                                       (worker/stream! {:type "space-rooms-diff"
                                                        :space-id space-id
                                                        :rooms next-rooms})))
                             (p/catch #(log/error "Space rooms diff panic:" %))))))))))


(defn apply-global-spaces-diffs! [updates]
  (swap! !global-space-mutex
         (fn [prev-promise]
           (p/then prev-promise
                   (fn []
                     (-> (apply-matrix-diffs @!global-spaces-array updates parse-space-child)
                         (p/then (fn [next-spaces]
                                   (reset! !global-spaces-array next-spaces)
                                   (worker/stream! {:type "global-spaces-diff"
                                                    :spaces next-spaces})
                                   (doseq [s next-spaces]
                                     (when (:id s)
                                       (boot-space-list! (:id s))))))
                         (p/catch #(log/error "Global spaces diff panic:" %))))))))
#+end_src


**** Initializing the Space Service

This is just using the space-service to start subscribing to the
top-level spaces for the user. We need these to start building
out the parent-child relationships.

#+begin_src clojurescript :tangle ../../src/worker/spaces.cljs
(defn init-space-service! [client]
  (p/let [space-service (.spaceService client)
          _             (reset! !space-service space-service)
          listener      #js {:onUpdate #(apply-global-spaces-diffs! %)}
          sub           (.subscribeToTopLevelJoinedSpaces space-service listener)]
    (reset! !global-space-sub sub)
    (process-parent-queue! client space-service)))
#+end_src



**** Paginate
Now the UI component will need to know to load enough to fill its area, so there needs to be a method to actually
paginate directly.
#+begin_src clojurescript :tangle ../../src/worker/spaces.cljs
(worker/register :paginate-space
  (fn [{:keys [space-id]}]
    (if-let [space-list (get-in @!space-list-subs [space-id :list])]
      (do (.paginate space-list)
          {:status :success})
      {:status :error :msg "Space list not booted"})))
#+end_src
