
** Media Component

**** Preface

This is should enable handling media in a more idiomatic manner across both
offloaded rendering and regular rendering. Both should able to use this
method more or less the same without consideration with how it might behave.

**** Imports

#+begin_src clojurescript :tangle ../../../src/paradise/media/component.cljs
(ns paradise.media.component
  (:require [reagent.core :as r]
            ["react" :as react]
            [re-frame.db :as db]
            [cljs.core.async :refer [go <!]]
            [paradise.shared.client.state :as state]
            [cljs-workers.core :as main]
            [cljs-workers.mesh :as mesh]
            [taoensso.timbre :as log]
            [goog.object]
            [clojure.string :as str]
            [promesa.core :as p]
            [net :refer [!auth-context] :as net]))
#+end_src


**** Mxc->Url/Url->Mxc

This just provides a mechanism to convert mxc urls to usable urls
according to the Matrix spec. Now it is convenient to be able
to force it to use a home-server, but we should likely swap to retrieval
from re-frame for the client to determine the home-server dynamically.
This works for now though.

#+begin_src clojurescript :tangle ../../../src/paradise/media/component.cljs
(defn mxc->url
  ([mxc-url] (mxc->url mxc-url {}))
  ([mxc-url {:keys [homeserver type width height method] :or {type :download}}]
   (when (and (string? mxc-url) (str/starts-with? mxc-url "mxc://"))
     (let [db       (try @re-frame.db/app-db (catch :default _ {}))
           base-url (or homeserver (:homeserver-url db))]
       (when base-url
         (let [server-base (str/replace base-url #"/+$" "")
               resource    (str/replace mxc-url #"^mxc://" "")
               base-path   (str "/_matrix/client/v1/media/" (name type) "/" resource)]
           (if (= type :thumbnail)
             (str server-base base-path
                  "?width="  (or width 48)
                  "&height=" (or height 48)
                  "&method=" (or method "crop"))
             (str server-base base-path))))))))


(defn url->mxc [url]
  (if (and (string? url) (str/includes? url "/_matrix/"))
    (let [parts (str/split url #"/media/(?:download|thumbnail)/")]
      (if (= (count parts) 2)
        (str "mxc://" (second parts))
        url))
    url))
#+end_src


#+begin_src clojurescript :tangle ../../../src/paradise/media/component.cljs
(defonce !ui-blob-cache (r/atom {}))
(defonce !in-flight (atom #{}))

(defn request-mxc! [mxc]
  (when (and mxc
             (not (get @!ui-blob-cache mxc))
             (not (contains? @!in-flight mxc)))
    (swap! !in-flight conj mxc)
    (let [url (if (str/starts-with? mxc "mxc://")
                (mxc->url mxc)
                mxc)]
      (if-not url
        (do
          (swap! !ui-blob-cache assoc mxc :error)
          (swap! !in-flight disj mxc))
        (-> (p/let [resp (net/fetch url)
                    buf  (.arrayBuffer resp)]
              (let [blob    (js/Blob. #js [buf])
                    obj-url (js/URL.createObjectURL blob)]
                (swap! !ui-blob-cache assoc mxc obj-url)))
            (p/catch (fn [e]
                       (js/console.error "MXC Fetch Error:" e)
                       (swap! !ui-blob-cache assoc mxc :error)))
            (p/finally (fn []
                         (swap! !in-flight disj mxc))))))))

#+end_src

While building out the virtualizer I began to realize the lack of uniformity in how we rendered
components still.

While mxc-image solves the problem in a blunt sort of manner... it would be more sensible that
it not define the tag it would be using. That way we can allow ANY mxc URL to have deferred
evaluation.

In a Matrix client that would be every URL that could be rendered on the screen.

Hence, any component defining a src block would be utilizing an mxc. It would then make more
sense to remove the burden of evaluation from the developer and instead treat components
in a natural form.

Now, a problem we encountered often was that the Hiccup compiler adds an annoying amount
of overhead that isn't necessary. Most of the time it is completely acceptable, but for
extremely performance driven components it is a liability.

It may then be reasonable to assume that we might find ourselves crafting the 'mxc-image'
as a raw React component.


**** Media Fetch

#+begin_src clojurescript :tangle ../../../src/paradise/media/component.cljs
(defonce !native-media-cache (js/Map.))

(defn execute-media-fetch! [node spinner-node cache-key mxc source-map mime-type fallback-url room-id event-id]
  (go
    (try
      (let [db   @re-frame.db/app-db
            res  (<! (mesh/do-with-thread! :media-pool
                                           {:handler :get-media
                                            :arguments {:room-id room-id
                                                        :event-id event-id
                                                        :source mxc
                                                        :source-map source-map
                                                        :hs-url (:auth/hs-url db)
                                                        :token (:auth/token db)}}))]
        (case (:status res)
          "unencrypted"
          (let [url (:url res)]
            (if-let [existing (.get !native-media-cache cache-key)]
              (do
                (set! (.-refs existing) (+ (.-refs existing) 1))
                (set! (.-src node) (.-url existing)))
              (do
                (.set !native-media-cache cache-key #js {:url url :refs 1})
                (set! (.-src node) url)))
            (when (and spinner-node (.-style spinner-node))
              (set! (.-display (.-style spinner-node)) "none")))

          "success"
          (let [buffer (:bytes res)
                blob   (js/Blob. #js [buffer] #js {:type mime-type})
                url    (js/URL.createObjectURL blob)]
            (if-let [existing (.get !native-media-cache cache-key)]
              (do
                (js/URL.revokeObjectURL url)
                (set! (.-refs existing) (+ (.-refs existing) 1))
                (set! (.-src node) (.-url existing)))
              (do
                (.set !native-media-cache cache-key #js {:url url :refs 1})
                (set! (.-src node) url)))
            (when (and spinner-node (.-style spinner-node))
              (set! (.-display (.-style spinner-node)) "none")))

          "error"
          (do
            (js/console.error "Media load failed:" (:msg res))
            (when fallback-url
              (set! (.-src node) fallback-url)))

          (js/console.error "Unknown status from worker:" res)))
      (catch :default e
        (js/console.error "GO BLOCK CRASH:" e)))))
#+end_src


**** Media Native Component
This is the component generated under the hood for deferred rendering.
We make sure we don't burden the main thread with evaluating components
as much as possible. Instead we just want to 'pop' the image in.

#+begin_src clojurescript :tangle ../../../src/paradise/media/component.cljs
(defn media-ref [node props]
  (let
      [mxc          (:mxc props)
        source-map   (or (:source-map props) (:sourceMap props))
        mime-type    (or (:mime-type props) (:mimeType props) "image/png")
        fallback-url (or (:fallback-url props) (:fallbackUrl props))
        room-id      (or (:room-id props) (:roomId props))
        event-id     (or (:event-id props) (:eventId props))
        cache-key    (or (get-in source-map [:file :url]) mxc)
        mounted?     (atom false)]
      (if node
    (when-not @mounted?
      (reset! mounted? true)
      (let [spinner-node (.-previousElementSibling node)]
        (if-let [cached (.get !native-media-cache cache-key)]
          (do
            (set! (.-refs cached) (+ (.-refs cached) 1))
            (set! (.-src node) (.-url cached))
            (when (and spinner-node (.-style spinner-node))
              (set! (.-display (.-style spinner-node)) "none")))
          (execute-media-fetch! node spinner-node cache-key mxc source-map mime-type fallback-url room-id event-id))))
    (when @mounted?
      (reset! mounted? false)
      (when-let [cached (.get !native-media-cache cache-key)]
        (set! (.-refs cached) (- (.-refs cached) 1))
        (when (<= (.-refs cached) 0)
          (js/setTimeout
           (fn []
             (let [latest-cached (.get !native-media-cache cache-key)]
               (when (and latest-cached (<= (.-refs latest-cached) 0))
                 (when (clojure.string/starts-with? (str (.-url latest-cached)) "blob:")
                   (js/URL.revokeObjectURL (.-url latest-cached)))
                 (.delete !native-media-cache cache-key))))
           10)))))))


(defn ^:react media-native [props]
  (let [tag-type     (or (:tag-type props) (:tagType props) "img")
        class        (or (:class props) (:className props) (:class-name props))
        style        (:style props)
        alt          (:alt props)
        on-error     (or (:on-error props) (:onError props))
        on-click     (or (:on-click props) (:onClick props))
        controls     (:controls props)]
    (react/createElement tag-type
                         #js {:className class
                              :style (clj->js style)
                              :alt alt
                              :controls controls
                              :onClick on-click
                              :loading (when (= tag-type "img") "lazy")
                              :decoding (when (= tag-type "img") "async")
                              :onError on-error
                              :ref #(media-ref % props)})))
#+end_src


**** Registering

#+begin_src clojurescript :tangle ../../../src/paradise/media/component.cljs
#_(swap! paradise.shared.client.registry/!components assoc
       "comp:paradise.media.component/media-native" media-native)

#_(goog.object/set media-native "$native_comp" "comp:paradise.media.component/media-native")

#+end_src


**** Wrapper Component

Wraps the media-native to enable simpler usage.

#+begin_src clojurescript :tangle ../../../src/paradise/media/component.cljs
(defn ^:ui media [props]
  [media-native
   props])
#+end_src
