
** Pins (but no needles)

**** Preface

Pins. Should be super straight-forward and simple. Apparently not.

Currently pins can't be easily supported in a way that makes sense. Most
avenues in the client itself shut down any approach
- Subscribing to Room Info and trying to listen for changes doesn't even update the pinnedEventIds
- Creating a timeline with PinnedEvents as the focus does not ever have an initial state
- Checking the pinned events from the server obviously proves they're populated... but we aren't going to probe for each entry
- pinnedEventIds is empty on the Room Info itself (so it isn't even initially populated)

These are limitations of the current version of the sdk.

#+begin_src clojurescript
 pinned-focus (new (.. sdk -TimelineFocus -PinnedEvents)
                                       #js {:maxEventsToLoad 100
                                            :maxConcurrentRequests 10
                                            })
#+end_src

This is likely the best way to prepare the timelines for the side panel.
We can also subscribe to the Room Info to actually detect new ones?
Doesn't matter how, but we need one of those to render the actual entries.



**** Imports

#+begin_src clojurescript :tangle ../../src/container/pins.cljs
(ns container.pins
  (:require
   [re-frame.core :as re-frame]
   [taoensso.timbre :as log]
   [cljs-workers.core :as main]
   [client.state :as state]
   [cljs.core.async :refer [go <!]]
   [reagent.core :as r]
   [utils.svg :as icons]
   [container.reusable :refer [message-preview-item]]))

#+end_src


#+begin_src clojurescript :tangle ../../src/container/pins.cljs


#+end_src



**** Reframe Subscriptions and Events

***** Fetching

#+begin_src clojurescript :tangle ../../src/container/pins.cljs
(re-frame/reg-event-fx
 :room/fetch-pinned-events
 (fn [{:keys [db]} [_ room-id]]
   (main/do-with-pool! @state/!engine-pool {:handler :get-pinned-events
                                            :arguments {:room-id room-id}})
   {}))

#+end_src


***** Saving and Getting

#+begin_src clojurescript :tangle ../../src/container/pins.cljs

(re-frame/reg-event-db
 :room/sync-pinned-ids
 (fn [db [_ room-id pinned-ids]]
   (let [current-pins (get-in db [:rooms/data room-id :pinned-events] {})
         valid-pins   (select-keys current-pins pinned-ids)]
     (assoc-in db [:rooms/data room-id :pinned-events] valid-pins))))

(re-frame/reg-event-db
 :room/update-pinned-event
 (fn [db [_ room-id event]]
   (assoc-in db [:rooms/data room-id :pinned-events (:id event)] event)))

(re-frame/reg-sub
 :room/pinned-events
 (fn [db [_ room-id]]
   (vals (get-in db [:rooms/data room-id :pinned-events] {}))))
#+end_src



**** Component


#+begin_src clojurescript :tangle ../../src/container/pins.cljs

(defn pins []
  (let [active-room @(re-frame/subscribe [:rooms/active-id])
        pins        @(re-frame/subscribe [:room/pinned-events active-room])
        tr          @(re-frame/subscribe [:i18n/tr])]
    [:div.sidebar-pins-container
     {:style {:display "flex" :flex-direction "column" :height "100%" :padding "16px"}}
     (if (empty? pins)
       [:div.empty-pins
        {:style {:text-align "center" :margin-top "40px" :opacity 0.5}}
        [icons/pins {:width "48px" :height "48px"}]
        [:p (tr [:container.pins/no-pins] "No pinned messages")]]
       [:div.pins-list
        {:style {:flex 1 :overflow-y "auto"}}
        (for [event pins]
          ^{:key (:id event)}
          [message-preview-item active-room event])])]))
#+end_src


#+begin_src css :tangle ../../css/pins.css
.sidebar-pins-container {
    display: flex;
    flex-direction: column;
    height: 100%;
    padding: 16px;
}

.pins-list {
    flex: 1;
    overflow-y: auto;
}

pins-empty-state {
    text-align: center;
    margin-top: 40px;
    opacity: 0.5;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 16px;
}

.pins-title {
    font-size: 1.1rem;
    font-weight: 600;
    margin-bottom: 20px;
    color: var(--text-primary);
}


#+end_src







