
** Notifications

**** Preface

So notifications for a good bit were just stashed into settings, but as
we scale this to work also on native platforms it makes a bit more
sense to centralize them.

They are technically an overlay, so we'll group them here also.



**** Imports

#+begin_src clojurescript :tangle ../../src/overlays/notifications.cljs
(ns overlays.notifications
(:require [re-frame.core :as re-frame]
            [taoensso.timbre :as log]
            [promesa.core :as p]
            [cljs.core.async :refer [go <!]]
            [cljs.core.async.interop :refer-macros [<p!]]
            ["@capacitor/core" :refer [Capacitor registerPlugin]]
            ["@capacitor/push-notifications" :refer [PushNotifications]]
            [client.state :refer [!config] :as state]
            [client.session-store :as store]
            [cljs-workers.core :as main]))
#+end_src


**** Shadow Client

So, since we're utilizing Clojurescript and the WASM we actually don't have a very
clean way to use native push notifs. Sygnal forwards them as silent notifications
effectively. Now, that could be worked around... but we stil would want to
decrypt the payload when it arrives. Or at least have the option to.

So what if we made a 'second' client of sorts to run natively. It could be quite
small and just perform the task of registering a pusher and decrypting a message.
Easy. We just need to make sure we name it eloquently (and likely we don't
want to actually allow the native main client to register its own pusher. There
would be no point.)


Now this is something I considered greatly, but given the current state of the FFI bindings
and the WASM... It isn't exactly easily feasible to just use the same device for our
native notifications if we wish to decrypt the notifications.

At a later point we can look to making a Capacitor plugin to spin up the WASM in its
own executable environment and let it use native storage. Then we can see
if it is reasonably performant enough to boot a WASM executable environment like WAMR.
Or even particularly reasonable. It may work better to actually just use the Kotlin
and Swift components respectively and make a clean mapping layer to make our code
nicely portable. For now though, this implementation will do.
Even if it changes, the plugin work for Capacitor is still needed anyway,
so it isn't as though this portion was exactly the tedious part.


A further consideration might be storing the client info in the same style we do
in the main application. So we wat to store them in a user-id key and activate
them using the user-id.
I don't know that we can easily allow multiple account notifications just due
to the expensive nature of the DBs in memory. It'll need some investgating
before implementation.
So we need to ensure there is visible clarity to this shortcoming provided
to the user.


#+begin_src clojurescript :tangle ../../src/overlays/notifications.cljs
(def shadow-device (registerPlugin "ShadowDevice"))

(re-frame/reg-event-fx
 :push/create-sleepy-shadow
 (fn [_ [_ credentials]]
   (log/info "Creating Sleepy Shadow Device...")
   (try
     (-> (.createSleepyShadow shadow-device
           #js {:homeserverUrl (:homeserver credentials)
                :username (:username credentials)
                :password (:password credentials)
                :userId (:userId credentials)
                })
         (.then #(log/info "Sleepy Shadow SUCCESS:" (.-status %)))
         (.catch #(log/error "Sleepy Shadow FAILED:" %)))
     (catch js/Error e
       (log/error "Synchronous CLJS Crash in createSleepyShadow:" e)))
   {}))

(re-frame/reg-sub
 :push/active-user
 (fn [db _] (:active-push-user db)))

(re-frame/reg-event-db
 :push/set-active-user
 (fn [db [_ user-id]]
   (assoc db :active-push-user user-id
             :push-status (if user-id :enabled :disabled))))

(re-frame/reg-sub
 :push/previews-enabled?
 (fn [db _]
   (:push/previews-enabled? db true)))

(re-frame/reg-event-fx
 :push/hydrate-previews-setting
 (fn [{:keys [db]} [_ enabled?]]
   {:db (assoc db :push/previews-enabled? (if (nil? enabled?) true enabled?))}))

(re-frame/reg-event-fx
 :push/toggle-previews
 (fn [{:keys [db]} [_ enabled?]]
   (store/set-setting! "show_previews" enabled?)
   (when (.isNativePlatform Capacitor)
     (-> (.setPreviewPreferences shadow-device #js {:enabled enabled?})
         (.catch #(log/error "Failed to save native preview prefs:" %))))
   {:dispatch [:push/hydrate-previews-setting enabled?]}))


(re-frame/reg-event-fx
 :push/activate-shadow
 (fn [{:keys [db]} [_ token]]
   (let [active-user (:active-user-id db)
         old-user    (:active-push-user db)]
     (when (and old-user (not= old-user active-user))
       (.deactivateShadow shadow-device #js {:pushToken token :userId old-user}))
     (try
       (-> (.activateShadow shadow-device
             #js {:pushToken token
                  :pushUrl (:push-url @!config)
                  :userId active-user})
           (.then (fn [res]
                    (re-frame/dispatch [:push/set-active-user active-user])))
           (.catch (fn [err]
                     (log/error "Shadow Activated FAILED:" err)
                     (re-frame/dispatch [:modal/open-shadow-login]))))
       (catch js/Error e
         (log/error "Synchronous CLJS Crash in activateShadow:" e)))
     {})))


(re-frame/reg-event-fx
 :push/deactivate-shadow
 (fn [{:keys [db]} _]
   (let [token (:native-token db)
         target-user (:active-push-user db)]
     (when target-user
       (try
         (-> (.deactivateShadow shadow-device
                                #js {:pushToken (or token "") :userId target-user})
             (.then (fn [res]
                      (re-frame/dispatch [:push/hydrate-status nil])))
             (.catch #(log/error "Shadow Deactivated FAILED:" %)))
         (catch js/Error e
           (log/error "Synchronous CLJS Crash in deactivateShadow:" e)))))
   {}))


(re-frame/reg-event-fx
 :push/verify-shadow
 (fn [_ [_ user-id recovery-key]]
   (when (.isNativePlatform Capacitor)
     (-> (.verifyShadow shadow-device #js {:userId user-id :recoveryKey recovery-key})
         (.catch #(log/error "Shadow verification failed:" %))))
   {}))


(re-frame/reg-event-fx
 :push/check-verification-status
 (fn [_ [_ user-id]]
   (when (.isNativePlatform Capacitor)
     (-> (.getShadowStatus shadow-device #js {:userId user-id})
         (.then (fn [res]
                  (when (.-isVerified res)
                    (log/info "Shadow client is already verified, skipping prompt.")
                    (re-frame/dispatch [:sdk/verification-success]))))
         (.catch #(log/error "Failed to fetch shadow status:" %))))
   {}))


#+end_src





**** Initialization

Now native push listeners aren't on the service worker.
In fact, on iOS we can't even have a service worker in a
reasonable manner.
Instead we have to register the listeners for the app
to utilize the nice features inside of Capacitor.

#+begin_src clojurescript :tangle ../../src/overlays/notifications.cljs
(re-frame/reg-event-fx
 :push/store-native-token
 (fn [{:keys [db]} [_ token]]
   {:db (assoc db :native-token token)
    :fx [[:dispatch [:push/activate-shadow token]]]}))

(re-frame/reg-sub
 :push/native-token
 (fn [db _]
   (:native-token db)))

(defn init! []
  (when (.isNativePlatform Capacitor)
    (.addListener PushNotifications "registration"
      (fn [token-res]
        (let [token (.-value token-res)]
          (log/info "Native Push Token Received:" token)
          (re-frame/dispatch [:push/store-native-token token]))))
    (.addListener PushNotifications "registrationError"
      (fn [err]
        (log/error "Native Push Registration Error:" (.-error err))))
    (.addListener PushNotifications "pushNotificationReceived"
      (fn [notification]
        (log/info "Foreground Push Received:" notification)))
    (.addListener PushNotifications "pushNotificationActionPerformed"
      (fn [action]
        (let [data    (.. action -notification -data)
              room-id (.-room_id data)]
          (when room-id
            (log/info "User tapped notification for room:" room-id)
            (re-frame/dispatch [:space/select-room room-id])))))))
#+end_src



**** Helper functions

Just some helper functions

#+begin_src clojurescript :tangle ../../src/overlays/notifications.cljs
(defn url-base64->uint8-array [base64-string]
  (let [padding (.repeat "=" (mod (- 4 (mod (.-length base64-string) 4)) 4))
        base64 (-> (.replace base64-string (js/RegExp. "-" "g") "+")
                   (.replace (js/RegExp. "_" "g") "/")
                   (str padding))
        raw-data (js/atob base64)
        output-array (js/Uint8Array. (.-length raw-data))]
    (dotimes [i (.-length raw-data)]
      (aset output-array i (.charCodeAt raw-data i)))
    output-array))

(defn- clean-url [base path]
  (str (str/replace base #"/+$" "")
       "/"
       (str/replace path #"^/+" "")))
#+end_src




**** Registers


We embed the registration in an easily callable reframe event.


***** Web


#+begin_src clojurescript :tangle ../../src/overlays/notifications.cljs
(re-frame/reg-event-fx
 :push/register-pusher
 (fn [_ [_ subscription]]
   (if-let [pool @state/!engine-pool]
     (let [sub-json (.toJSON subscription)
           p256dh   (.. sub-json -keys -p256dh)
           auth     (.. sub-json -keys -auth)
           endpoint (.-endpoint sub-json)
           app-id   (:app-id @!config)
           push-url (:push-url @!config)]
       (cond
         (not app-id)   (log/error "Missing app-id!")
         (not push-url) (log/error "Missing push-url!")
         (not p256dh)   (log/error "Missing p256dh key from browser subscription!")
         (not auth)     (log/error "Missing auth key from browser subscription!")
         :else
         (go
           (let [res (<! (main/do-with-pool! pool
                                             {:handler :register-pusher
                                              :arguments {:p256dh   p256dh
                                                          :auth     auth
                                                          :endpoint endpoint
                                                          :app-id   app-id
                                                          :push-url push-url
                                                          :app-name (:app-name @!config)
                                                          :lang     (or js/navigator.language "en")}}))]
             (if (= (:status res) "success")
               (do
                 (log/info "Web Pusher registered successfully!")
                 (re-frame/dispatch [:push/set-status :enabled]))
               (log/error "HS Rejected Web Pusher:" (:msg res)))))))
     (log/error "Cannot register pusher: no engine pool"))
   {}))
#+end_src


***** Status


#+begin_src clojurescript :tangle ../../src/overlays/notifications.cljs
(re-frame/reg-event-db
 :push/set-status
 (fn [db [_ status]]
   (assoc db :push-status status)))

(re-frame/reg-sub
 :push/status
 (fn [db _]
   (:push-status db :disabled)))
#+end_src


***** Push Enable (Prompt User)

#+begin_src clojurescript :tangle ../../src/overlays/notifications.cljs
(re-frame/reg-event-fx
 :push/enable
 (fn [_ _]
   (if (.isNativePlatform Capacitor)
     (go
       (try
         (let [perm (<p! (.requestPermissions PushNotifications))]
           (if (= (.-receive perm) "granted")
             (.register PushNotifications)
             (log/warn "Native notification permission denied.")))
         (catch js/Error e
           (log/error "Native Push setup failed:" e))))
     (if-not (and (exists? js/window.PushManager) (exists? js/navigator.serviceWorker))
       (do (log/error "Push messaging is not supported.") {})
       (-> (p/let [permission (js/Notification.requestPermission)]
             (if (= permission "granted")
               (p/let [reg (.-ready js/navigator.serviceWorker)
                       existing-sub (.getSubscription (.-pushManager reg))
                       sub (if existing-sub
                             existing-sub
                             (.subscribe (.-pushManager reg)
                                         #js {:userVisibleOnly true
                                              :applicationServerKey (url-base64->uint8-array (:vapid-key @!config))}))]
                 (re-frame/dispatch [:push/register-pusher sub]))
               (log/warn "Notification permission denied.")))
           (p/catch #(log/error "Push setup failed:" %)))))
   {}))
#+end_src

