#+begin_src clojurescript :tangle ../../src/room/room_list.cljs
(ns room.room-list
  (:require
   [clojure.string :as str]
   [promesa.core :as p]
            [re-frame.core :as re-frame]
            [taoensso.timbre :as log]
            [re-frame.db :as db]
            ["react-virtuoso" :refer [Virtuoso]]
            [promesa.core :as p]
            [reagent.core :as r]
            [reagent.dom.client :as rdom]
            [room.room-summary :refer [build-room-summary]]
            [client.diff-handler :refer [apply-matrix-diffs]]
            [utils.global-ui :refer [avatar]]
            ["generated-compat" :as sdk :refer [RoomListEntriesDynamicFilterKind RoomListFilterCategory RoomListLoadingState]])
  (:require-macros [utils.macros :refer [ocall oget]]))

#+end_src

Parse the room into a useful CLJS form. Otherwise we have to work with
a JS room which isn't ideal. We could try being a bit more consistent
on this stipulation... but it isn't entirely essential now.
#+begin_src clojurescript :tangle ../../src/room/room_list.cljs
(defn parse-room [space-service room-interface]
  (p/let [room-info     (if (fn? (.-roomInfo room-interface)) (.roomInfo room-interface) nil)
          latest-event  (.latestEvent room-interface)
          room-id       (.-id room-info)
           parents (if space-service
                    (.joinedParentsOfChild space-service room-id)
                    (p/resolved []))
          first-parent (get parents 0)
          first-parent-id (if first-parent (.-roomId first-parent) nil)
          ]
    (let [summary (build-room-summary room-interface room-info latest-event)]
      (aset summary "raw-room" room-interface)
      (aset summary "parents" parents)
      (log/debug summary)
      (aset summary "first-parent-id" first-parent-id)
      summary)))
#+end_src


Prior we had a very verbose and repeated diffs check, but
as our timeline, spaces, and room list all share the same
general patterns to handling diffs we can consolidate them and
call them like so.
So all we need to do is ask reframe for the current global rooms
and call the diff check against those rooms and the updates
to set the "new" global rooms. This will make our global list
refresh automatically.
Later we can apply filters on it to induce specific behavior
like creating a DM grouping.

To add onto this, but we use a mutex to ensure that the rust-sdk
doesn't ever end up in a state where the diffs aren't readily
available to refresh our window. We don't slow the rust-sdk down,
but instead establish a queue for our code to process them
and notify reframe properly.
#+begin_src clojurescript :tangle ../../src/room/room_list.cljs
(defonce !room-mutex (atom (p/resolved nil)))

(defn apply-global-diffs-async! [updates]
  (swap! !room-mutex
         (fn [prev-promise]
           (p/then prev-promise
                   (fn []
                     (let [db @re-frame.db/app-db
                           current-rooms (get db :rooms [])
                           space-service (:space-service db)]
                       (-> (apply-matrix-diffs current-rooms updates #(parse-room space-service %))
                           (p/then (fn [next-rooms]
                                     (re-frame/dispatch-sync [:sdk/set-global-rooms-sync next-rooms])
                                     (re-frame/dispatch [:sdk/set-global-rooms next-rooms])))
                           (p/catch (fn [err]
           (log/error "Global Diff Panic:" err)
           nil)))))))))
#+end_src


We previously had filters in initial builds, but when we opted for a full reframe
style implementation we removed them. We'll add them back here. Effectively calling these
informs the Rust SDK that you wish to get a new Room List set.
As a result on space swapping we ALWAYS want to ensure we set back to "All" as
we rely on the list for our room list view behaviors (even if the space loads a
'dumb' version).
#+begin_src clojurescript :tangle ../../src/room/room_list.cljs
(defn get-rust-filter [filter-id]
  (case filter-id
    "unread"
    (RoomListEntriesDynamicFilterKind.All.
      #js {:filters #js [(RoomListEntriesDynamicFilterKind.Unread.)
                         (RoomListEntriesDynamicFilterKind.DeduplicateVersions.)]})
    "people"
    (RoomListEntriesDynamicFilterKind.All.
      #js {:filters #js [(RoomListEntriesDynamicFilterKind.Category. #js {:expect RoomListFilterCategory.People})
                         (RoomListEntriesDynamicFilterKind.Joined.)
                         (RoomListEntriesDynamicFilterKind.DeduplicateVersions.)]})
    "favourite"
    (RoomListEntriesDynamicFilterKind.All.
      #js {:filters #js [(RoomListEntriesDynamicFilterKind.Favourite.)
                         (RoomListEntriesDynamicFilterKind.DeduplicateVersions.)]})

    (RoomListEntriesDynamicFilterKind.All.
      #js {:filters #js [(RoomListEntriesDynamicFilterKind.NonLeft.)
                         (RoomListEntriesDynamicFilterKind.DeduplicateVersions.)]})))
#+end_src




We can simplify (and diverge) from Aurora's implementation as View models are very rigid
and lock us into a certain pattern. Instead we'll just let reframe know the diff and let
it handle re-rendering directly.
This can be broken part a bit more for labeling purpose. For now though, it is easily
described as creating a set of entries (initializing the sliding sync frame size) and
then attaching an onUpdate to easily refresh those entries without much effort.
We apply a filter to ensure we don't end up with any duplication on the resulting room list and
apply it. Then we prompt the app to give us the first page for the controller.
#+begin_src clojurescript :tangle ../../src/room/room_list.cljs
(defn start-room-list-sync! [room-list]
  (log/debug "Starting Room List Sync!")
  (let [entries-result (.entriesWithDynamicAdapters room-list 200
                         #js {:onUpdate #(re-frame/dispatch [:sdk/global-rooms-diff %])})]
    (re-frame/dispatch [:sdk/save-room-list-handle entries-result])
    (let [controller (.controller entries-result)
          default-filter (get-rust-filter "people")]
      (.setFilter controller default-filter)
      (.addOnePage controller))
    (let [loading-result (.loadingState room-list
                           #js {:onUpdate #(re-frame/dispatch [:sdk/room-list-loading %])})]
      (re-frame/dispatch [:sdk/room-list-loading (.-state loading-result)]))))
#+end_src

This is just a simple filter method to deduplicate
#+begin_src clojurescript :tangle ../../src/room/room_list.cljs
(defn distinct-by [f coll]
  (let [!seen (atom #{})]
    (filterv (fn [x]
               (let [k (f x)]
                 (if (contains? @!seen k)
                   false
                   (do (swap! !seen conj k)
                       true))))
             coll)))
#+end_src


This provides a method to take the room map and turn it into a usable structure
to actually visualize our room lists. I'll come back and add more to this when
I add the call room previewing.
#+begin_src clojurescript :tangle ../../src/room/room_list.cljs
(defn flatten-tree [rooms-map children-map closed-drawers parent-id depth]
  (let [sdk-children   (get children-map parent-id)
        manual-children (->> (vals rooms-map)
                             (filter #(= (:first-parent-id %) parent-id))
                              (map (fn [r] {:id (or (:id r) (:roomId r)) :is-space? (:isSpace r)}))
                              (vec))
        child-refs (->> (concat sdk-children manual-children)
                        (distinct-by :id)
                        (vec))]
    (reduce
      (fn [acc {:keys [id is-space?]}]
        (let [rich-data (get rooms-map id)
              item      (merge rich-data
                               {:id id
                                :is-space? is-space?
                                :depth depth
                                :name (or (:name rich-data) "Loading...")})
              acc-with-item (conj acc item)]
          (if (and is-space? (not (contains? closed-drawers id)))
            (into acc-with-item (flatten-tree rooms-map children-map closed-drawers id (inc depth)))
            acc-with-item)))
      []
      child-refs)))


#+end_src

There are our reframe pieces. I'll go into detail on each of them later on. For now this
is effectively a functioning *stub*.
#+begin_src clojurescript :tangle ../../src/room/room_list.cljs
(re-frame/reg-sub
 :rooms/active-id
 (fn [db _]
   (:active-room-id db)))

(re-frame/reg-sub
 :rooms/all
 (fn [db _]
   (let [rooms (:rooms db)]
     (if (map? rooms) (vec (vals rooms)) (vec (or rooms []))))))

(re-frame/reg-sub
 :space-rooms
 (fn [db _]
   (vec (or (:space-rooms db) []))))

(re-frame/reg-sub
 :rooms/active-metadata
 :<- [:rooms/active-id]
 :<- [:rooms/all]
 :<- [:space-rooms]
 (fn [[active-id all-rooms space-rooms] _]
   (when active-id
     (let [all-known (into all-rooms space-rooms)]
       (some (fn [r]
               (let [rid (or (:id r)
                             (try (.-roomId r) (catch :default _ nil))
                             (try (.-id r) (catch :default _ nil)))]
                 (when (= rid active-id) r)))
             all-known)))))
#+end_src


Important to note that the Rust sdk delivers the resulting rooms in order
of recent activity. So if we use a broad stroke to handle all of them we lose
this valuable data. Instead we want to provide a simple 'parsed' map for
the DMs list or All rooms list as these are best served fresh first.
For the space rooms themselves we want to flatten as we have described
above.
#+begin_src clojurescript :tangle ../../src/room/room_list.cljs
(re-frame/reg-sub
 :rooms/map
 :<- [:rooms/all]
 (fn [rooms-list _]
   (into {}
         (for [room rooms-list]
           (let [r  (js->clj room :keywordize-keys true)
                 id (or (:id r) (:roomId r))]
             [id r])))))

(re-frame/reg-sub
 :rooms/indexed-map
 :<- [:rooms/all]
 (fn [rooms-list _]
   (into {}
         (for [room rooms-list]
           (let [r  (js->clj room :keywordize-keys true)
                 id (or (:id r) (:roomId r))]
             [id r])))))

(re-frame/reg-sub
 :rooms/ordered-list
 :<- [:rooms/all]
 (fn [rooms-list _]
   (mapv #(js->clj % :keywordize-keys true) rooms-list)))


(re-frame/reg-sub
 :rooms/current-view
 :<- [:spaces/active-id]
 :<- [:rooms/ordered-list]
 :<- [:rooms/indexed-map]
 :<- [:space-children/map]
 :<- [:rooms/closed-drawers]
 (fn [[active-id ordered-list indexed-map children-map closed-drawers] _]
   (if-not active-id
     ordered-list
     (flatten-tree indexed-map children-map closed-drawers active-id 0))))

#_(re-frame/reg-sub
 :rooms/current-view
 :<- [:spaces/active-id]
 :<- [:rooms/ordered-list]
 :<- [:rooms/indexed-map]
 :<- [:room-list/active-filter]
 :<- [:space-children/map]
 :<- [:rooms/closed-drawers]
 (fn [[active-id ordered-list indexed-map active-filter children-map closed-drawers] _]
   (cond
     (= active-filter "people")
     ordered-list
     :else
     (flatten-tree indexed-map children-map closed-drawers active-id 0))))

(re-frame/reg-event-db
 :rooms/toggle-drawer
 (fn [db [_ drawer-id]]
   (update-in db [:ui :closed-drawers]
              (fn [closed]
                (if (contains? closed drawer-id)
                  (disj closed drawer-id)
                  (conj (or closed #{}) drawer-id))))))

(re-frame/reg-sub
 :rooms/closed-drawers
 (fn [db _]
   (get-in db [:ui :closed-drawers] #{})))

(re-frame/reg-event-fx
 :sdk/global-rooms-diff
 (fn [_ [_ updates]]
   (apply-global-diffs-async! updates)
   {}))

(re-frame/reg-event-db
 :sdk/set-global-rooms-sync
 (fn [db [_ rooms]]
   (assoc db :rooms rooms)))

(re-frame/reg-event-fx
 :sdk/set-global-rooms
 (fn [_ [_ rooms]]
   (let [top-room-ids (take 2 (map #(.-id %) rooms))]
     {:dispatch [:sdk/preload-timelines top-room-ids]})))

(re-frame/reg-event-db
 :sdk/room-list-loading
 (fn [db [_ state-obj]]
   (assoc db :rooms-loading? (= "NotLoaded" (.-tag state-obj)))))

(re-frame/reg-sub
 :rooms/active-room-members
 :<- [:rooms/active-id]
 (fn [active-id db]
   (get-in db [:rooms/members active-id] [])))

(re-frame/reg-event-fx
 :rooms/fetch-members
 (fn [{:keys [db]} [_ room-id]]
   (let [client (:client db)]
     (when (and client room-id)
       (if-let [room (.getRoom client room-id)]
         (p/let [members (.membersNoSync room)
                 parsed  (map (fn [m]
                                {:user-id      (.userId m)
                                 :display-name (or (.displayName m) (.userId m))
                                 :avatar-url   (.avatarUrl m)})
                              members)]
           (re-frame/dispatch [:rooms/save-members room-id parsed]))
         (log/warn "Could not find room in client for members fetch:" room-id))))
   {}))

(re-frame/reg-event-db
 :rooms/save-members
 (fn [db [_ room-id members]]
   (assoc-in db [:rooms/members room-id] members)))


(re-frame/reg-event-fx
 :rooms/select
 (fn [{:keys [db]} [_ room-id]]
   (let [current-room (:active-room-id db)]
     (if (= current-room room-id)
       {:db (assoc-in db [:ui :sidebar-open?] false)}
       {:db (-> db
                (assoc :active-room-id room-id)
                (assoc-in [:ui :sidebar-open?] false))
        :dispatch-n (remove nil?
                            [(when current-room [:sdk/cleanup-timeline current-room])
                             [:sdk/boot-timeline room-id]
                             [:composer/load-draft room-id]])}))))

(re-frame/reg-event-db
 :sdk/hydrate-rooms
 (fn [db [_ js-rooms]]
   (let [rooms (js->clj js-rooms :keywordize-keys true)
         rooms-map (into {} (for [r rooms]
                              [(or (:id r) (:roomId r)) r]))]
     (assoc db :rooms rooms-map))))


(re-frame/reg-event-fx
 :sdk/restore-global-list
 (fn [{:keys [db]} _]
   (let [global-rooms (vals (:rooms db))]
     {:db (assoc db :space-rooms (vec global-rooms))})))

(re-frame/reg-event-db
 :sdk/save-room-list-handle
 (fn [db [_ result]]
   (assoc db
     :room-list-result result
     :room-list-controller (.controller result))))

(re-frame/reg-event-db
 :sdk/save-room-list-controller
 (fn [db [_ controller]]
   (assoc db :room-list-controller controller)))
#+end_src


While setting filters isn't the most resource friendly implementation
for now it is an easy and clean way to provide a sorted list to the
user. We'll have to see how it scales as I suspect it is causing the
entire room list to reload. Hopefully not.
*** TODO Investigate the behavior of Room Filters
#+begin_src clojurescript :tangle ../../src/room/room_list.cljs
(re-frame/reg-event-db
 :room-list/set-filter
 (fn [db [_ filter-id]]
   (assoc db :active-filter-id filter-id)))

(re-frame/reg-sub
 :room-list/active-filter
 (fn [db _]
   (get db :active-filter-id "people")))

(re-frame/reg-event-fx
 :room-list/apply-filter
 (fn [{:keys [db]} [_ filter-id]]
   (let [current-filter (:active-filter-id db)
         controller     (:room-list-controller db)]
     (cond
       (= current-filter filter-id)
       (do (log/debug "Filter already set to:" filter-id)
           {})

       (not controller)
       (do (log/warn "Filter swap failed: No room-list-controller found.")
           {})

       :else
       (do
         (log/debug "Swapping filter from" current-filter "to" filter-id)
         (.setFilter controller (get-rust-filter filter-id))
         (.addOnePage controller)
         {:db (assoc db :active-filter-id filter-id)})))))
#+end_src


#+begin_src clojurescript :tangle ../../src/room/room_list.cljs
(defn filter-toggle-bar []
  (let [active-filter @(re-frame/subscribe [:room-list/active-filter])]
    [:div.filter-bar
     (for [[id label] [["all" "All"] ["unread" "Unread"] ["people" "People"]]]
       ^{:key id}
       [:button.filter-btn
        {:class    (when (= active-filter id) "active")
         :on-click #(re-frame/dispatch [:room-list/apply-filter id])}
        label])]))
#+end_src





Our virtualized room list. We ensure our rooms are in an array form
for consumption by Virtuoso and then instruct Virtuoso to ask
reframe for the next "page" upon reaching the end of its display.
We assign the data to be represented as the room array itself.
Now, we can also add nifty behavior for the content itself by then
checking for the "kind" of room. For now though, this is plenty sufficient.
#+begin_src clojurescript :tangle ../../src/room/room_list.cljs
(defn virtualized-room-list [room-array space-id active-room closed-drawers]
  (let [active-filter @(re-frame/subscribe [:room-list/active-filter])]
    [:> Virtuoso
     {:style {:height "100%" :width "100%"}
      :data room-array
      :endReached #(re-frame/dispatch [:room-list/paginate-global])
      :itemContent
      (fn [index room]
        (r/as-element
         (let [{:keys [id name is-space? depth notification-count]} room
               avatar-url (:avatar room)
               _ (log/debug room)
               depth   (or depth 0)
               indent  (* depth 12)
               _ (js/console.log is-people?)
               is-closed? (contains? closed-drawers id)]
           (if is-space?
             [:div.room-drawer-header
              {:style {:padding-left (str indent "px")}
               :class (when is-closed? "collapsed")
               :on-click #(re-frame/dispatch [:rooms/toggle-drawer id])}
              [:span.drawer-arrow "▼"]
              [:span.drawer-name (str/upper-case name)]]
             [:div.room-item
              {:style {:padding-left (str indent "px")}
               :class (when (= id active-room) "active")
               :on-click #(re-frame/dispatch [:rooms/select id])}
              (if (= active-filter "people")
                 [avatar {:id id :name name :url avatar-url :size 24 :status :online}]
                 [:span.room-hash "# "])
              [:span.room-name name]
              (when (> (or notification-count 0) 0)
                [:div.badge notification-count])]))))}]))
#+end_src

Now for our room list component itself, we have three subscriptions requested from reframe
We want to make sure the component updates if our rooms change, our active space changes,
or our active room changes. We then add some decorating Hiccup around it to round out the
component.
#+begin_src clojurescript :tangle ../../src/room/room_list.cljs
(defn room-list []
  (let [rooms          @(re-frame/subscribe [:rooms/current-view])
        active-room    @(re-frame/subscribe [:rooms/active-id])
        active-space-id   @(re-frame/subscribe [:spaces/active-id])
        active-space    @(re-frame/subscribe [:spaces/active-metadata])
        closed-drawers @(re-frame/subscribe [:rooms/closed-drawers])
        room-array     (to-array rooms)]

    [:div.sidebar-rooms
     {:style {:display "flex" :flex-direction "column" :height "100%"}}
     [:h3.rooms-header {:style {:padding "8px"}}
      (if active-space
        [:<> [:h3 {:style {:margin 0 :font-size "1.1rem"}} (:name active-space)]])]
     (when-not active-space
       [filter-toggle-bar])
     (if (or (nil? room-array) (== (alength room-array) 0))
       [:div.empty-state "No rooms here..."]
       [:div.room-collection {:style {:flex 1 :min-height 0}}
        [virtualized-room-list room-array active-space active-room closed-drawers]])]))
#+end_src


