
** Timeline


**** Preface

Obviously a Matrix client needs a timeline. For now we'll scaffold out a design similar to the other components
we've made interop with the WASM bindings.


**** Imports



#+begin_src clojurescript :tangle ../../../src/container/timeline/base.cljs
(ns container.timeline.base
  (:require [re-frame.core :as re-frame]
            [taoensso.timbre :as log]
            [clojure.string :as str]
            [re-frame.db :as db]
            [cljs-workers.core :as main]
            [cljs.core.async :refer [go <!]]
            ["virtua" :refer [Virtualizer]]
            [reagent.core :as r]
            [client.state :as state]
            [reagent.dom.client :as rdom]
            [utils.images :refer [mxc->url]]
            [utils.helpers :refer [sanitize-custom-html format-divider-date format-readers join-names get-status-string]]
            [utils.global-ui :refer [avatar long-press-props swipe-to-action-wrapper]]
            [utils.svg :as icons]
            [container.timeline.item :refer [event-tile connected-event-tile]]
            [container.timeline.virtualizer :refer [test-timeline]]
            [container.reusable :refer [room-header]]
            [input.base :refer [message-input]]))
#+end_src




**** Reframe event and subscriptions

This is a functional stub for now. I'll go back and split and describe
each of these later.
****** TODO Describe these
#+begin_src clojurescript :tangle ../../../src/container/timeline/base.cljs
(defn get-event-id [e]
  (cond
    (and (= (:type e) :virtual) (str/includes? (str (:tag e)) "Div"))
    (str "virtual-divider-" (format-divider-date (:ts e)))

    (= (:type e) :virtual)
    (str "virtual-" (:tag e) "-" (:ts e))

    (not-empty (:id e))
    (:id e)

    :else
    (:internal-id e)))

(defn enrich-timeline-items [items]
  (let [clean-items (remove #(and (= (:type %) :virtual)
                                  (= (:tag %) "ReadMarker"))
                            items)]
    (loop [remaining clean-items
           processed []
           last-msg  nil]
      (if (empty? remaining)
        processed
        (let [curr         (first remaining)
              curr-is-msg? (= (:content-tag curr) "MsgLike")
              stable-id    (get-event-id curr)
              can-merge?   (and curr-is-msg?
                                last-msg
                                (= (:sender-id curr) (:sender-id last-msg))
                                (< (- (:ts curr) (:ts last-msg)) 300000))
              new-item     (assoc curr
                                  :id stable-id
                                  :merge-with-prev? can-merge?)]
          (recur (rest remaining)
                 (conj processed new-item)
                 (if curr-is-msg? new-item nil)))))))

#+end_src



#+begin_src clojurescript :tangle ../../../src/container/timeline/base.cljs
(re-frame/reg-sub
 :timeline/raw-events
 (fn [db [_ room-id]]
   (let [focused-data (get-in db [:timeline-data room-id :focused] [])
         live-data    (get-in db [:timeline-data room-id :live] [])]
;;     live-data
(if (and (vector? focused-data) (empty? focused-data))
  live-data
  focused-data

 ;;    (if (empty? focused-data) focused-data live-data)
     ))))


(re-frame/reg-event-db
 :sdk/update-timeline
 (fn [db [_ room-id source new-raw-events]]
   (assoc-in db [:timeline-data room-id source] new-raw-events)))



(re-frame/reg-sub
 :timeline/sorted-events
 (fn [[_ active-room]]
   (re-frame/subscribe [:timeline/raw-events active-room]))
 (fn [raw-events _]
   raw-events
   ))

(re-frame/reg-sub
 :timeline/current-events
 (fn [[_ active-room]]
   (re-frame/subscribe [:timeline/sorted-events active-room]))
 (fn [sorted-events]
   (enrich-timeline-items sorted-events)
   ))

(re-frame/reg-sub
 :timeline/events-map
 (fn [[_ room-id]]
   (re-frame/subscribe [:timeline/current-events room-id]))
 (fn [events _]
   (into {} (map (juxt :id identity) events))))

(re-frame/reg-event-fx
 :sdk/boot-timeline
 (fn [{:keys [db]} [_ room-id]]
   (if (get-in db [:timeline-subs room-id])
     (do (log/warn "Prevented duplicate timeline boot for:" room-id) {})
     (do
       (main/do-with-pool! @state/!engine-pool
                           {:handler :boot-timeline
                            :arguments {:room-id room-id :mode :live}})
       {:db (assoc-in db [:timeline-subs room-id] true)}))))

(re-frame/reg-event-fx
 :room/boot-focused-timeline
 (fn [{:keys [db]} [_ room-id event-id]]
   (main/do-with-pool! @state/!engine-pool
                       {:handler :boot-timeline
                        :arguments {:room-id room-id :mode :focused :event-id event-id}})
   {:db (assoc-in db [:timeline-subs room-id :focused] true)}))


(re-frame/reg-event-fx
 :room/boot-pinned-timeline
 (fn [{:keys [db]} [_ room-id]]
   (main/do-with-pool! @state/!engine-pool
                       {:handler :boot-timeline
                        :arguments {:room-id room-id :mode :pins}})
   {:db (assoc-in db [:timeline-subs room-id :pins] true)}))

(re-frame/reg-event-fx
 :sdk/cleanup-timeline
 (fn [{:keys [db]} [_ room-id]]
   (main/do-with-pool! @state/!engine-pool {:handler :cleanup-timeline
                                            :arguments {:room-id room-id}})
   {:db (-> db
            (update :timeline-subs dissoc room-id)
            (update :timeline-data dissoc room-id))}))

(re-frame/reg-sub
 :timeline/pinned-events
 (fn [db [_ room-id]]
   (get-in db [:timeline-data room-id :pins] [])))

(re-frame/reg-event-fx
 :sdk/back-paginate
 (fn [{:keys [db]} [_ room-id]]
   (let [loading-back?    (get-in db [:timeline/loading-more? room-id])
         loading-forward? (get-in db [:timeline/loading-forward? room-id])]
     (if (and room-id (not loading-back?) (not loading-forward?))
       (do
         (log/info "Triggering Worker Back Paginate for" room-id)
         (go
           (let [res (<! (main/do-with-pool! @state/!engine-pool
                                             {:handler :paginate-timeline
                                              :arguments {:room-id room-id :direction :back :amount 25}}))]
             (re-frame/dispatch [:sdk/pagination-complete room-id])))
         {:db (assoc-in db [:timeline/loading-more? room-id] true)})
       {}))))

(re-frame/reg-event-fx
 :sdk/forward-paginate
 (fn [{:keys [db]} [_ room-id]]
   (let [loading-back?    (get-in db [:timeline/loading-more? room-id])
         loading-forward? (get-in db [:timeline/loading-forward? room-id])]
     (if (and room-id (not loading-back?) (not loading-forward?))
       (do
         (log/info "Triggering Worker Forward Paginate for" room-id)
         (go
           (let [res (<! (main/do-with-pool! @state/!engine-pool
                                             {:handler :paginate-timeline
                                              :arguments {:room-id room-id :direction :forward :amount 25}}))]
             (re-frame/dispatch [:sdk/pagination-complete room-id])))
         {:db (assoc-in db [:timeline/loading-forward? room-id] true)})
       {}))))


(re-frame/reg-event-db
 :timeline/set-loading
 (fn [db [_ room-id loading?]]
   (assoc-in db [:timeline/loading-more? room-id] loading?)))

(re-frame/reg-event-db
 :sdk/pagination-complete
 (fn [db [_ room-id]]
   (-> db
       (assoc-in [:timeline/loading-more? room-id] false)
       (assoc-in [:timeline/ui-metadata room-id :pending-anchor] nil))))

(re-frame/reg-event-db
 :sdk/forward-pagination-complete
 (fn [db [_ room-id]]
   (assoc-in db [:timeline/loading-forward? room-id] false)))

(re-frame/reg-event-db
 :sdk/forward-pagination-dead
 (fn [db [_ room-id]]
   (-> db
       (assoc-in [:timeline/loading-forward? room-id] false)
       (assoc-in [:timeline/forward-dead? room-id] true))))

(re-frame/reg-event-db
 :sdk/update-pagination-status
 (fn [db [_ room-id status]]
   (assoc-in db [:timeline-pagination room-id] status)))

(re-frame/reg-event-fx
 :room/pretty-jump
 (fn [{:keys [db]} [_ room-id event-id]]
   {:db (assoc-in db [:timeline/ui-state room-id :animating-jump?] true)
    :dispatch-later [{:ms 300
                      :dispatch [:room/execute-deep-jump room-id event-id]}]}))

(re-frame/reg-event-fx
 :room/execute-deep-jump
 (fn [{:keys [db]} [_ room-id event-id]]
   {:db (assoc-in db [:timeline/jump-target-id room-id] event-id)
    :dispatch-n [[:sdk/cleanup-timeline room-id]
                 [:room/boot-focused-timeline room-id event-id]]}))

(re-frame/reg-event-fx
 :room/jump-to-live-bottom
 (fn [{:keys [db]} [_ room-id]]
   {:db (-> db
            (assoc-in [:timeline/ui-state room-id :animating-jump?] true)
            (update :timeline/jump-target-id dissoc room-id))
    :dispatch-later [{:ms 300
                      :dispatch [:room/execute-return-to-live room-id]}]}))
(re-frame/reg-event-fx
 :room/execute-return-to-live
 (fn [{:keys [db]} [_ room-id]]
   {:dispatch-n [[:sdk/cleanup-timeline room-id]
                 [:sdk/boot-timeline room-id]]}))

(re-frame/reg-event-fx
 :room/jump-to-present
 (fn [{:keys [db]} [_ room-id]]
   (main/do-with-pool! @state/!engine-pool {:handler :cleanup-timeline
                                            :arguments {:room-id room-id}})
   {:db (-> db
            (update-in [:timeline-subs room-id] dissoc :focused-timeline :focused-handle)
            (assoc-in [:timeline-data room-id :focused] [])
            (assoc-in [:timeline/ui-state room-id :animating-jump?] true))
    :dispatch-later [{:ms 50
                      :dispatch [:room/jump-to-live-bottom room-id]}]}))

(re-frame/reg-sub
 :timeline/ui-state
 (fn [db [_ room-id]]
   (get-in db [:timeline/ui-state room-id] {})))

(re-frame/reg-sub
 :timeline/jump-target-id
 (fn [db [_ room-id]]
   (get-in db [:timeline/jump-target-id room-id])))

(re-frame/reg-sub
 :timeline/loading-forward?
 (fn [db [_ room-id]]
   (get-in db [:timeline/loading-forward? room-id] false)))

(re-frame/reg-sub
 :timeline/ui-metadata
 (fn [db [_ room-id]]
   (get-in db [:timeline/ui-metadata room-id] {})))

(re-frame/reg-sub
 :timeline/loading-more?
 (fn [db [_ room-id]]
   (get-in db [:timeline/loading-more? room-id] false)))

(re-frame/reg-sub
 :room/is-focused?
 (fn [db [_ room-id]]
   (some? (get-in db [:timeline/jump-target-id room-id]))))

#+end_src


***** Timeline Merging?

This is important to do as we must normalize the list coming from the
Rust SDK. Otherwise sliding sync will provide us duplicate unique
IDs and cause the Timeline rendering to freak out.
In addition to normalizing on the id, we need to ensure we
only render the LATEST version of an id (yes the timeline will
have two objects with the same unique ID if for example there
is an edit)



**** Chat Follower Indicators


When no readers are present we use a line break that won't get optimized
away.

#+begin_src clojurescript :tangle ../../../src/container/timeline/base.cljs
(defn followers-indicator [active-room]
  (let [reader-ids  @(re-frame/subscribe [:timeline/latest-readers])
        members-map @(re-frame/subscribe [:room/members-map active-room])
        has-readers? (boolean (seq reader-ids))
        names (when has-readers?
                (map (fn [id] (or (:display-name (get members-map id)) id))
                     reader-ids))]
    [:div.followers-indicator
     {:class (when has-readers? "is-visible")}
     (when has-readers?
       [icons/double-check {:width "14px" :height "14px"}])
     [:span.text
      (if has-readers?
        (format-readers names)
        "\u00A0")]
     ]))
#+end_src


It is important we reserve the space for this as if we don't
the user may be typing and it'll bump the composer when it appears.


#+begin_src css :tangle ../../../css/timeline.css
.followers-indicator {
      font-size: 0.75rem;
      color: var(--cp-text-muted);
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 6px;
      user-select: none;
      height: 24px;
      transition: opacity 0.2s ease-in-out;
      opacity: 0;
  }

  .followers-indicator.is-visible {
      opacity: 1;
  }

  .followers-indicator .text {
      line-height: 1;
}
#+end_src


**** Typing Indicators (and Readers)

Typing notifications or typing indicators provide the user visual feedback when someone is typing.
They are rather straight forward in the rust-sdk thankfully, so we just subscribe to the room's listener.
As I started writing this I realized we could actually treat the area we use for read-by like Emacs
uses the mini-buffer. A nice status indicator.

***** Reframe Subscriptions and Events

#+begin_src clojurescript :tangle ../../../src/container/timeline/base.cljs
(re-frame/reg-event-db
 :sdk/clear-stale-typing
 (fn [db [_ room-id]]
   (let [data (get-in db [:typing-users room-id])]
     (if (and data (> (- (js/Date.now) (:last-update data)) 6000))
       (update db :typing-users dissoc room-id)
       db))))

(re-frame/reg-event-fx
 :sdk/update-typing-users
 (fn [{:keys [db]} [_ room-id user-ids]]
   (let [users (js->clj user-ids)]
     (if (empty? users)
       {:db (update db :typing-users dissoc room-id)}
       {:db (assoc-in db [:typing-users room-id]
                      {:users users
                       :last-update (js/Date.now)})
        :dispatch-later [{:ms 7000
                          :dispatch [:sdk/clear-stale-typing room-id]}]}))))

(re-frame/reg-sub
 :room/typing-users
 (fn [db [_ room-id]]
   (let [data (get-in db [:typing-users room-id])]
     (if (and data
              (< (- (js/Date.now) (:last-update data)) 6000))
       (:users data)
       []))))
#+end_src



We want to subscribe to a single room's events to have the read indicators for it.
We then just want to filter out the event objects and get the read-by from inside.
We also don't want to list our own name, so we remove that too.

#+begin_src clojurescript :tangle ../../../src/container/timeline/base.cljs

(re-frame/reg-sub
 :timeline/latest-readers
 (fn [[_ room-id _]]
   [(re-frame/subscribe [:timeline/current-events room-id])
    (re-frame/subscribe [:sdk/profile])])
 (fn [[events profile] _]
   (let [my-id         (:user-id profile)
         actual-events (filter #(= (:type %) :event) events)
         latest-event  (last actual-events)
         read-by       (or (:read-by latest-event) [])
         others        (remove #(= % my-id) read-by)]
     others)))

#+end_src



***** Component

#+begin_src clojurescript :tangle ../../../src/container/timeline/base.cljs
(defn status-indicator [active-room]
  (let [tr            @(re-frame/subscribe [:i18n/tr])
        typing-info   @(re-frame/subscribe [:room/typing-users active-room])
        reader-ids    @(re-frame/subscribe [:timeline/latest-readers active-room])
        members-map   @(re-frame/subscribe [:room/members-map active-room])
        profile       @(re-frame/subscribe [:sdk/profile])
        my-id         (:user-id profile)
        typing-ids    (if (map? typing-info) (:users typing-info) typing-info)
        others-typing (filterv #(not= % my-id) (or typing-ids []))
        get-name      #(or (:display-name (get members-map %)) %)
        typing-names  (map get-name others-typing)
        reader-names  (map get-name reader-ids)

        has-typists?  (not-empty typing-names)
        has-readers?  (not-empty reader-names)
        is-visible?   (or has-typists? has-readers?)]
    [:div.followers-indicator
     {:class (when is-visible? "is-visible")
      :key (str active-room "-status-bar")}
     (cond
       has-typists?
       [:div.status-content {:key "typing"}
        [icons/typing-dots {:style {:color "var(--cp-text-muted)"}}]
        [:span.text (get-status-string tr :typing typing-names)]]
       has-readers?
       [:div.status-content {:key "readers"}
        [icons/double-check {:width "14px" :height "14px"}]
        [:span.text (get-status-string tr :reading reader-names)]]
       :else
       [:span.text {:key "empty"} "\u00A0"])]))
#+end_src


**** Jump To? Paginate? Focus Boot? Oh my.

#+begin_src clojurescript :tangle ../../../src/container/timeline/base.cljs




#+end_src



**** Virtuoso Timeline Component



Similar to Spaces and RoomLists we do a Virtuoso component here.
We ensure the array that will compose its table of individual elements
is a JS array and then we move on with defining the actual
behavior for the timeline.
****** TODO Timeline is currently not performant for a few reasons
We need to button up this better, as this was the most recently added thing
from the enter refactoring of the "application view"

The table itself asks reframe to trigger the back pagination when the "start"
is reached. This should probably also have a somewhat automatic trigger until
size is reached, but the behavior may be impacted by the performant issue
mentioned above. Should be easily sorted, however.


For fleshing out the timeline itself we want to consider a few key details.
What should happen when the user reaches the top? Back paginate.

The timeline should NEVER shift upon loading more entries.

There isn't inherently just one way to do elegant rendering.
However, most virtual lists only provide one to us though.
They pre-calculate the items in the list and then render according
to those calculations. Really fancy ones opt to even re-calculate
after loads.
Done well, this is more or less sufficient

So the most important detail that our timeline should then follow is:
never change the user's current rendered element's unless it is smoothly
bringing element's *UP*. One might think this to be the behavior
for media without size info. In those cases still, we will simply
use default sizing and just render from that.
So still we can easily avoid any load issues.

The actual problematic items are edits, reactions, and deletes.

These can immediately change what is on the screen and change the size
of items that were already calculated. The reaction row itself
adds an entire row always and deletes will entirely remove a message.

So it'll be important to guard against these cases.

Now the best advice I can give for building out a timeline renderer is
to ensure that at each step you ensure the components play well with
whatever you're jamming them into.

Now I tried a number of implementations. Virtuoso for a long while, but
I could not get it to co-exist calmly with our lovely reframe.

I then toyed with trying to neatly create a simple native rendering
sliding window. Where we could dispose of the contents as we go.
This worked for everything... except inertia scrolling.

So... Virtua seems rational. The virtualizer in it seemed perfect.
I've seen use of it and the mechanism seems thoughtful.

I wasn't a fan of Virtuoso having a paid license for their message
list for use cases like this either.

#+begin_src clojurescript :tangle ../../../src/container/timeline/base.cljs
(defn timeline-loading-overlay []
  [:div {:style {:position "absolute"
                 :top "20px"
                 :width "100%"
                 :display "flex"
                 :justify-content "center"
                 :z-index 100
                 :pointer-events "none"}}
   [:div {:style {:background "var(--bg-color, white)"
                  :padding "8px"
                  :border-radius "50%"
                  :box-shadow "0 2px 10px rgba(0,0,0,0.1)"}}
    [:div.spinner]]])

(defn timeline-empty-state [room-id]
  (let [tr @(re-frame/subscribe [:i18n/tr])]
    [:div.timeline-empty {:style {:padding "40px" :text-align "center"}}
     (if room-id
         (tr [:container.timeline/loading])
         (tr [:container.timeline/no-room])
         )]))


(defn timeline-jump-button [do-jump! focus-mode?]
  (let [tr @(re-frame/subscribe [:i18n/tr])]
    [:button.jump-to-bottom
     {:style {:position "absolute"
              :bottom "20px"
              :right "24px"
              :z-index 10
              :display "flex"
              :align-items "center"
              :gap "8px"}
      :on-click do-jump!}
     [:span (if focus-mode?
              (tr [:container.timeline/return-to-live])
              (tr [:container.timeline/jump-to-bottom]))]]))
#+end_src



****** TODO Need to check if we can paginate and recur until a scrollbar (unless it is a short room thus paginate check)

#+begin_src clojurescript :tangle ../../../src/container/timeline/base.cljs
(defn virtualized-timeline [initial-room-id]
  (r/with-let [!virtua-ref    (r/atom nil)
               set-virtua-ref #(reset! !virtua-ref %)
               !scroll-ref    (atom nil)
               set-scroll-ref #(reset! !scroll-ref %)
               !current-room  (r/atom initial-room-id)
               !at-bottom?    (r/atom true)
               !show-jump?    (r/atom false)
               !prev-first-id (atom nil)
               !prev-last-id  (atom nil)
               !initialized?  (r/atom false)
               !scroll-timer  (atom nil)]

    (fn [room-id]
      (when (not= room-id @!current-room)
        (reset! !current-room room-id)
        (reset! !initialized? false)
        (reset! !prev-first-id nil)
        (reset! !prev-last-id nil)
        (reset! !at-bottom? true)
        (reset! !show-jump? false))

      (let [events           @(re-frame/subscribe [:timeline/current-events room-id])
            event-array      (to-array events)
            cnt              (count event-array)
            loading?         @(re-frame/subscribe [:timeline/loading-more? room-id])
            loading-forward? @(re-frame/subscribe [:timeline/loading-forward? room-id])
            jump-target      @(re-frame/subscribe [:timeline/jump-target-id room-id])
            focus-mode?      @(re-frame/subscribe [:room/is-focused? room-id])

            real-events      (filter #(not= (:type %) :virtual) events)
            current-first-id (:id (first real-events))
            current-last-id  (:id (last real-events))

            did-prepend?     (boolean (and @!prev-first-id
                                           (not= current-first-id @!prev-first-id)
                                           (= current-last-id @!prev-last-id)))

            new-msg-arrived? (boolean (and @!prev-last-id
                                           (not= current-last-id @!prev-last-id)
                                           (not did-prepend?)))

            check-fill-viewport! (fn []
                                   (when-let [target @!scroll-ref]
                                     (let [max-scroll (- (.-scrollHeight target) (.-clientHeight target))]
                                       (when (and (<= max-scroll 0) (not loading?))
                                         (re-frame/dispatch [:sdk/back-paginate room-id])))))

            do-jump!         (fn []
                               (if focus-mode?
                                 (re-frame/dispatch [:room/jump-to-live-bottom room-id])
                                 (some-> @!virtua-ref (.scrollToIndex (dec cnt) #js {:align "end"}))))]

        (reset! !prev-first-id current-first-id)
        (reset! !prev-last-id current-last-id)

        (when (and (not @!initialized?) (pos? cnt) @!virtua-ref)
          (let [target-idx (if jump-target
                             (let [idx (.findIndex event-array #(= (:id %) jump-target))]
                               (if (not= idx -1) idx (dec cnt)))
                             (dec cnt))
                align-opt  (if jump-target #js {:align "center"} #js {:align "end"})]
            (some-> @!virtua-ref (.scrollToIndex target-idx align-opt))
            (js/setTimeout #(do
                              (some-> @!virtua-ref (.scrollToIndex target-idx align-opt))
                              (reset! !initialized? true)
                              (check-fill-viewport!))
                           300)))

        (when (and @!initialized? did-prepend?)
          (js/setTimeout check-fill-viewport! 100))

        (when (and @!initialized?
                   @!at-bottom?
                   new-msg-arrived?
                   (not focus-mode?))
          (js/requestAnimationFrame
           (fn []
             (some-> @!virtua-ref (.scrollToIndex (dec cnt) #js {:align "end"}))
             (js/setTimeout #(some-> @!virtua-ref (.scrollToIndex (dec cnt) #js {:align "end"})) 200))))

        [:div.virtua-timeline-wrapper
         {:style {:flex 1
                  :position "relative"
                  :display "flex"
                  :flex-direction "column"
                  :min-height 0
                  :opacity (if @!initialized? 1 0)
                  :transition "opacity 0.15s ease-in-out"}}

         [:div.timeline-messages
          {:ref set-scroll-ref
           :class (when jump-target "jumping-animation")
           :style {:display "flex"
                   :flex-direction "column"
                   :flex 1
                   :height "100%"
                   :overflow-y "auto"
                   :overflow-anchor "none"}
           :on-scroll (fn [e]
                        (let [target           (.-currentTarget e)
                              scroll-top       (.-scrollTop target)
                              max-scroll       (- (.-scrollHeight target) (.-clientHeight target))
                              dist-from-bottom (- max-scroll scroll-top)]
                          (when-not @!scroll-timer
                            (reset! !scroll-timer
                                    (js/setTimeout
                                     (fn []
                                       (reset! !scroll-timer nil)
                                       (reset! !show-jump? (> dist-from-bottom 600))
                                       (reset! !at-bottom? (<= dist-from-bottom 10))

                                       (when (and @!initialized?
                                                  (> max-scroll 0)
                                                  (<= scroll-top 500)
                                                  (not loading?))
                                         (re-frame/dispatch [:sdk/back-paginate room-id]))

                                       (when (and focus-mode?
                                                  (<= dist-from-bottom 500)
                                                  (not loading-forward?))
                                         (re-frame/dispatch [:sdk/forward-paginate room-id])))
                                     10)))))}

          (when loading?
            [timeline-loading-overlay])

          (if (zero? cnt)
            [timeline-empty-state room-id]
            (into [:> Virtualizer
                   {:ref set-virtua-ref
                    :shift did-prepend?}]
                  (for [item event-array]
                    ^{:key (:id item)}
                    [:div.virtua-item-wrapper
                     {:style {:margin "0"
                              :min-height "32px"
                              :width "100%"}}
                     [:div.timeline-item
                      {:class (when (= (:id item) jump-target) "is-jump-target")
                       :style {:margin "0"}}
                      [connected-event-tile room-id item]]])))
          (when (and focus-mode? loading-forward?)
            [:div {:style {:min-height "60px"
                           :display "flex"
                           :align-items "center"
                           :justify-content "center"
                           :padding-bottom "20px"}}
             [:div.spinner]])]
         (when (and @!show-jump? (not @!at-bottom?))
           [timeline-jump-button do-jump! focus-mode?])]))))
#+end_src


**** Timeline Component

The timeline component itself. It subscribes to the active room id
and the active room's metadata. This way we can easily and effortless
update the timeline via reframe being told when the Rust SDK has
received an update.
***** TODO dig into the display-name

#+begin_src clojurescript :tangle ../../../src/container/timeline/base.cljs
(defn timeline [& {:keys [compact? hide-header?]}]
  (let [active-id    @(re-frame/subscribe [:rooms/active-id])
        room-meta    @(re-frame/subscribe [:rooms/active-metadata])
        display-name (when active-id (or (when room-meta (.-name room-meta)) active-id))]
    [:div.timeline-container
     (when-not hide-header?
       [room-header {:display-name display-name
                     :compact?     compact?
                     :active-id    active-id}])

     (if-not active-id
       [timeline-empty-state active-id]
       [:<>
;;        ^{:key active-id}

        [test-timeline active-id]
;;        [virtualized-timeline active-id]
        [message-input]
        [status-indicator active-id]])]))
#+end_src




**** CSS Dump

I will segment these another time

#+begin_src css :tangle ../../../css/timeline.css

  .timeline-container {
      display: flex;
      flex-direction: column;
      flex: 1;
      height: 100%;
      min-height: 0;
  }




  .message-item:hover {
      background-color: var(--surface-hover, rgba(255, 255, 255, 0.04));
  }


  .message {
      padding: 2px 16px;
  }

  .sender {
      color: #ffffff;
      font-size: 1rem;
      font-weight: 600;
      padding-right: 8px;
      display: inline-block;
      max-width: 100%;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
      vertical-align: bottom;
  }




  .timeline-reply-banner {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 0.85rem;
    color: var(--text-muted, #888);
    background: rgba(0, 0, 0, 0.03);
    padding: 6px 10px;
    padding-bottom: 6px;
    border-radius: 6px;
    border-left: 3px solid var(--accent-color, #aaa);
    cursor: pointer;
    transition: background 0.15s ease;
    max-width: 100%;
  }


  .message-render-wrapper {
      display: inline;
  }
  .message-list {
      flex: 1;
      overflow-y: auto;
  }

  .virtuoso-list {
      flex: 1;
      height: 100% !important;
      width: 100%;
  }



  .virtuoso-scroller {
      overflow-anchor: none !important;
  }

  @media (max-width: 768px) {
      .message-hover-toolbar {
          display: none !important;
      }
  }








#+end_src




