
** Macros


**** Preface

So we need some helper macros to cover a number of circumstances whether that be
just shortening or cleaning up usage to patching Vite and other incompatibilities.


**** Imports

#+begin_src clojurescript :tangle ../../../../src/paradise/shared/utils/macros.cljc
(ns paradise.shared.utils.macros
  (:require [clojure.java.io :as io]
            [clojure.edn :as edn]
            [cljs.analyzer.api :as ana]
            [cljs.env :as env]
            ))
#+end_src


**** Safe Rust Object Prototype Calling

These macros are effectively just wrappers that provide clean
interop with the underlying Rust objects as the Rust objects
tend to utilize prototypes heavily as a result of how UniFFI
outputs them.
#+begin_src clojurescript :tangle ../../../../src/paradise/shared/utils/macros.cljc
(defmacro ocall
  [obj method & args]
  `(let [obj# ~obj
         m# ~(name method)
         f# (js/goog.object.get obj# m#)]
     (if (fn? f#)
       (.apply f# obj# (cljs.core/array ~@args))
       (throw (js/Error. (str "Method " m# " is not a function (is it a property?)"))))))


(defmacro oget
  "Property access for WASM objects that hides behind prototypes."
  [obj prop]
  `(js/goog.object.get ~obj ~(name prop)))
#+end_src


**** Plugin Macros

Plugins need some macros for compile time behavior adjustments.
The main two being providing namespaces to plugins to consume
in their code for more idiomatic code and a macro to declare
a UI component. Elegently written we can create a coherent
registry of components instead of manually aggregating them.

#+begin_src clojurescript :tangle ../../../../src/paradise/shared/utils/macros.cljc

(defmacro register-and-capture [fn-hash form]
  (let [locals (keys &env)
        clean-ks (remove #(clojure.string/includes? (name %) "__") locals)
        env-map (into {} (map (fn [k] [(keyword (name k)) k]) clean-ks))
        bind-syms (mapv symbol (map name clean-ks))
        bind-form (if (empty? bind-syms) '_ `{:keys ~bind-syms})]
    `(do
       (clojure.core/swap! paradise.shared.client.registry/!anon-fns clojure.core/assoc ~fn-hash
                           (fn [~bind-form] ~form))
       (clojure.core/let [f# ~form]
         (clojure.core/aset f# "$fn_ptr" ~fn-hash)
         (clojure.core/aset f# "$env" ~env-map)
         f#))))



(defmacro defoverride [comp-name args & body]
  (list 'do
        (list* 'defn comp-name args body)
        (list 'swap! 'paradise.shared.client.registry/!active-overrides 'assoc (keyword (name comp-name))
              (list 'hash-map :plugin-id (list 'deref 'paradise.shared.sci-runner.ui/!current-eval-plugin) :fn comp-name))))


(defmacro expose-ns [ns-sym]
  (let [public-vars (keys (ana/ns-publics env/*compiler* ns-sym))]
    (into {}
          (map (fn [v]
                 [`(quote ~v) (symbol (str ns-sym "/" v))])
               public-vars))))



(defmacro defui [comp-name args & body]
  (let [kw           (keyword comp-name)
        default-name (symbol (str comp-name "-default"))]
    `(do
       (defn ~default-name ~args ~@body)
       (swap! paradise.shared.client.registry/!components #(if (contains? % ~kw) % (assoc % ~kw ~default-name)))
       (defn ~comp-name [& args#]
         (let [override# (get @paradise.shared.client.registry/!active-overrides ~kw)
               live#     (if override#
                           (:fn override#)
                           (get @paradise.shared.client.registry/!components ~kw))]
           (into [live#] args#))))))


#+end_src



Load our static macros and provide them globally
#+begin_src clojurescript :tangle ../../../../src/paradise/shared/utils/macros.cljs
(ns paradise.shared.utils.macros
  (:require-macros [paradise.shared.utils.macros :refer [load-static-config]]))
(def config (load-static-config "config.edn"))
(def i18n-data (load-static-config "i18n.edn"))
#+end_src

Loading non-secret variables at runtime is fairly straightforward.
We can declare them as a EDN (extensible data notation) file and then
write them as a Clojure map to easily consume at start.
This way we don't have to convert or do anything odd to have consistently
usable configs across the application.


**** Config EDN Loading

#+begin_src clojurescript :tangle ../../../../src/paradise/shared/utils/macros.cljc
(defmacro load-static-config [path]
  (edn/read-string (slurp path)))
#+end_src
