
** Reframe DB


**** Preface

This may need changing the parent directory name or
figuring out a better spot for these. Library
mods aren't something I plan to make commonplace.

We actually need to replace the core behavior of the app-db
to enable Eve to actually create a SharedArrayBuffer version
of it.

A very cool pattern enabled by Clojure is that namespaces
are loaded and treated as last in. Library namespaces
are evaluated before program namespaces and so we can
define the same exact namespace and overwrite how it behaves
globally, even within the library that originally
defined it.

**** Imports

#+begin_src clojurescript :tangle ../../src/re_frame/db.cljs
(ns re-frame.db
  (:require [re-frame.interop :refer [ratom]]))
#+end_src


#+begin_src clojurescript :tangle ../../src/re_frame/db.cljs
(defonce !reactive-state (ratom {}))
(defonce !eve-ref (atom nil))
#+end_src


We need to create a loop cycle to consistently keep the app-db synced
and so that it triggers subscribes.

#+begin_src clojurescript :tangle ../../src/re_frame/db.cljs
(defn start-sab-sync-loop! []
  (let [sync-fn (fn []
                  (when-let [ea @!eve-ref]
                    (let [latest-state @ea]
                      (when-not (identical? @!reactive-state latest-state)
                        (cljs.core/reset! !reactive-state latest-state)))))]
    (if (exists? js/window)
      (let [tick (fn tick []
                   (sync-fn)
                   (js/requestAnimationFrame tick))]
        (tick))
      (js/setInterval sync-fn 16))))
#+end_src


Internally we establish an eve-atom which actually acts as the container
for the app-db

We may wish to define the Eve atom itself here, but I'm still feeling out
the organizational structure for these.

#+begin_src clojurescript :tangle ../../src/re_frame/db.cljs
(defn set-eve-atom! [eve-atom]
  (cljs.core/swap! eve-atom
                   (fn [sab-state]
                     (reduce-kv assoc (or sab-state {}) @!reactive-state)))

  (reset! !eve-ref eve-atom)
  (cljs.core/reset! !reactive-state @eve-atom)
  (start-sab-sync-loop!))
#+end_src


Similar to the actual namespace declared in the re-frame library
we define an app-db to be used as a drop-in replacement for the normal
app-db.

#+begin_src clojurescript :tangle ../../src/re_frame/db.cljs
(def app-db
  (reify
    cljs.core/IDeref
    (-deref [_]
      (cljs.core/deref !reactive-state))
    cljs.core/IReset
    (-reset! [_ new-val]
      (if-let [ea @!eve-ref]
        (let [res (cljs.core/reset! ea new-val)]
          (cljs.core/reset! !reactive-state res)
          res)
        (cljs.core/reset! !reactive-state new-val)))
    cljs.core/ISwap
    (-swap! [_ f]
      (if-let [ea @!eve-ref]
        (let [res (cljs.core/swap! ea f)]
          (cljs.core/reset! !reactive-state res)
          res)
        (cljs.core/swap! !reactive-state f)))
    (-swap! [_ f a]
      (if-let [ea @!eve-ref]
        (let [res (cljs.core/swap! ea f a)]
          (cljs.core/reset! !reactive-state res)
          res)
        (cljs.core/swap! !reactive-state f a)))
    (-swap! [_ f a b]
      (if-let [ea @!eve-ref]
        (let [res (cljs.core/swap! ea f a b)]
          (cljs.core/reset! !reactive-state res)
          res)
        (cljs.core/swap! !reactive-state f a b)))
    (-swap! [_ f a b xs]
      (if-let [ea @!eve-ref]
        (let [res (apply cljs.core/swap! ea f a b xs)]
          (cljs.core/reset! !reactive-state res)
          res)
        (apply cljs.core/swap! !reactive-state f a b xs)))
    cljs.core/IWatchable
    (-notify-watches [_ old new] (cljs.core/-notify-watches !reactive-state old new))
    (-add-watch [_ key f] (cljs.core/-add-watch !reactive-state key f))
    (-remove-watch [_ key] (cljs.core/-remove-watch !reactive-state key))))

#+end_src
