
** Message Input


**** Preface
Obviously a core part of a chat experience is the input mechanism itself.
The decision for rich text-editing fields is a lengthy list of pros and
cons for each editor. However, to avoid lengthy articulation on editors
we opted for the one that seemed the most pleasant and familiarly mold-able.
So, TapTap! It actually seems perfect for our case too as without going into
too much detail it is headless, so we can theme and customize it without much friction.


**** Imports

#+begin_src clojurescript :tangle ../../src/input/base.cljs
(ns input.base
  (:require [promesa.core :as p]
            [re-frame.core :as re-frame]
            [taoensso.timbre :as log]
            [clojure.string :as str]
            [input.drafts :refer [attachment-preview]]
            [input.composer :refer [tiptap-component get-matrix-formatted-body prepare-html-for-editor]]
            [input.emotes :refer [emoji-sticker-board]]
            [input.autocomplete :refer [suggestion-menu]]
            [reagent.core :as r]
            [utils.helpers :refer [mxc->url truncate-name]]
            [utils.svg :as icons]
            [cljs.core.async :refer [go <!]]
            [cljs-workers.core :as main]
            [client.login :as login]))
#+end_src



**** Upload Reframe Event

We'll need a way to generically upload to Matrix for anything from updating avatars, to sticker packs, or to files.
#+begin_src clojurescript :tangle ../../src/input/base.cljs
(re-frame/reg-event-fx
 :sdk/upload-media
 (fn [_ [_ file on-success-event]]
   (let [reader (js/FileReader.)]
     (if file
       (do
         (set! (.-onload reader)
               (fn [e]
                 (let [buffer (.. e -target -result)
                       mime   (.-type file)]
                   (if-let [pool @login/!engine-pool]
                     (go
                       (let [res (<! (main/do-with-pool! pool {:handler :upload-media
                                                               :arguments {:mime mime :buffer buffer}}))]
                         (if (= (:status res) "success")
                           (re-frame/dispatch (conj on-success-event (:url res)))
                           (log/error "Upload failed:" (:msg res)))))
                     (log/error "No engine pool for upload")))))
         (.readAsArrayBuffer reader file)
         {:db (assoc (re-frame/db) :uploading-files? true)})
       (do (log/warn "Missing file for upload") {})))))

#+end_src



**** File Upload

Through a bit of trial and error (and exploring the FFI bindings)
we can start to flesh out a file upload. Now direct file uploading is almost
always undesirable. However, it does help us get a feel for the most complex
message action possible. So we establish it as a reframe event, then we needed
to determine what the correct input for the file-info was. We did  this by
directly just checking the FFI bindings. Same for the upload-source, and the
upload-params. Since we're a good bit behind the current version of the sdk
we can't just use their published docs sadly. Though, when the sdk version
used is updated those are an excellent source to aid in visualizing how
these map with decently descriptive documentation surrounding.

https://matrix-org.github.io/matrix-rust-sdk/

#+begin_src clojurescript :tangle ../../src/input/base.cljs


#+end_src



In order to send images or videos appropriately, we need to ensure we're providing
the info section. Now while spec doesn't explicitly require this, it does ease
viewing for other clients. However, even if we don't clients will natively handle
it.
Important to note we must do this here as this is when the browser is loading the
buffer of data so we can actually check the data associated and pass it on.
#+begin_src clojurescript :tangle ../../src/input/base.cljs

(defn extract-metadata [raw-file]
  (p/create
   (fn [resolve _]
     (let [mime      (.-type raw-file)
           is-image? (str/starts-with? mime "image/")
           is-video? (str/starts-with? mime "video/")
           reader    (js/FileReader.)]
       (set! (.-onload reader)
             (fn [e]
               (let [buffer      (.. e -target -result)
                     base-att    {:buffer      buffer
                                  :mime        mime
                                  :filename    (.-name raw-file)
                                  :size        (.-size raw-file)
                                  :preview-url (js/URL.createObjectURL raw-file)}]
                 (if (or is-image? is-video?)
                   (let [el  (if is-image? (js/Image.) (js/document.createElement "video"))
                         url (js/URL.createObjectURL raw-file)]
                     (if is-image?
                       (set! (.-onload el)
                             (fn []
                               (js/URL.revokeObjectURL url)
                               (resolve (assoc base-att :width (.-width el) :height (.-height el)))))
                       (set! (.-onloadedmetadata el)
                             (fn []
                               (js/URL.revokeObjectURL url)
                               (resolve (assoc base-att :width (.-videoWidth el) :height (.-videoHeight el))))))
                     (set! (.-src el) url))
                   (resolve base-att)))))
       (.readAsArrayBuffer reader raw-file)))))

(re-frame/reg-event-fx
 :sdk/handle-file-drop
 (fn [_ [_ room-id files]]
   (doseq [raw-file files]
     (-> (extract-metadata raw-file)
         (p/then (fn [attachment]
                   (re-frame/dispatch [:composer/add-attachment room-id attachment])))))
   {}))
#+end_src




**** Message Submit


#+begin_src clojurescript :tangle ../../src/input/base.cljs



**** Message Submit


#+begin_src clojurescript :tangle ../../src/input/base.cljs
(re-frame/reg-event-fx
 :composer/submit
 (fn [{:keys [db]} [_ room-id text html]]
   (let [client      (:client db)
         timeline    (get-in db [:timeline-subs room-id :timeline])
         room        (when client (.getRoom client room-id))
         attachments (get-in db [:drafts room-id :attachments])
         context     (get-in db [:input-context room-id])]
     (cond
       (or (not timeline) (not room))
       (do (log/error "Room or Timeline missing for" room-id) {})
       (seq attachments)
       (do
         (-> (send-attachments! sdk timeline room attachments text html)
             (.then #(re-frame/dispatch [:composer/clear-after-submit room-id]))
             (.catch #(log/error "Failed to send attachments:" %)))
         {})
:else
       (try
         (let [payload (.messageEventContentFromHtml sdk text (or html text))]
           (if context
             (let [action     (:mode context)
                   raw-id-obj (-> context :target :event-or-transaction-id)
                   target-id  (if (= (.-tag raw-id-obj) "EventId")
                                (.. raw-id-obj -inner -eventId)
                                (.. raw-id-obj -inner -transactionId))
                   id-enum    (if (str/starts-with? target-id "$")
                                #js {:tag "EventId" :inner #js {:eventId target-id}}
                                #js {:tag "TransactionId" :inner #js {:transactionId target-id}})]
               (log/debug "Executing:" action "on" target-id)
               (cond
                 (= action :reply)
                 (.sendReply timeline payload target-id js/undefined)
                 (= action :edit)
                 (.edit timeline id-enum payload js/undefined)))
             (.send timeline payload js/undefined))
           (.clearComposerDraft room js/undefined)
           {:db (-> db
                    (assoc-in [:composer room-id] {:text "" :html "" :loaded-text ""})
                    (update :input-context dissoc room-id))})
         (catch :default e (log/error "Send error:" e) {}))))))
#+end_src


**** Sending Stickers


Stickers are actually an annoying special case. Inside the Rust-sdk
as of this version they are actually a stubbed method.

#+begin_src Typescript
    class Sticker_ extends UniffiEnum implements Sticker__interface {
        /**
         * @private
         * This field is private and should not be used, use `tag` instead.
         */
        readonly [uniffiTypeNameSymbol] = "MessageLikeEventContent";
        readonly tag = MessageLikeEventContent_Tags.Sticker;
        constructor() {
            super("MessageLikeEventContent", "Sticker")
        }

        static new(): Sticker_ {
            return new Sticker_()
        }

        static instanceOf(obj: any): obj is Sticker_ {
            return obj.tag === MessageLikeEventContent_Tags.Sticker
        }
    }
#+end_src

As you can note... the constructor has no parameters among other issues.
So instead, we must inform the server that we are sending a Sticker directly.
Later on this ideally will be changed, but for now this is the only path
forward.

#+begin_src clojurescript :tangle ../../src/input/base.cljs
(re-frame/reg-event-fx
 :sdk/send-sticker
 (fn [{:keys [db]} [_ room-id mxc alt-text info]]
   (let [client  (:client db)
         session (when client (.session client))]
     (if-not (and client session)
       (log/error "Cannot send raw sticker: No active session")
       (let [token   (.-accessToken session)
             hs      (str/replace (.-homeserverUrl session) #"/+$" "")
             txn-id  (str "stk-" (.getTime (js/Date.)) "-" (rand-int 10000))
             url     (str hs "/_matrix/client/v3/rooms/"
                          (js/encodeURIComponent room-id)
                          "/send/m.sticker/" txn-id)
             clean-body (cond
                          (keyword? alt-text) (name alt-text)
                          (string? alt-text) alt-text
                          :else "Sticker")
             info-obj (js-obj "mimetype" (or (:mimetype info) "image/png"))
             _        (when (:w info) (aset info-obj "w" (js/Number (:w info))))
             _        (when (:h info) (aset info-obj "h" (js/Number (:h info))))

             payload  #js {:body clean-body
                           :url  mxc
                           :info info-obj}]

         (log/info "Sending RAW m.sticker event to:" url)
         (-> (js/fetch url #js {:method  "PUT"
                                :headers #js {:Authorization (str "Bearer " token)
                                              :Content-Type  "application/json"}
                                :body    (js/JSON.stringify payload)})
             (.then (fn [resp]
                      (if (.-ok resp)
                        (log/info "Raw Sticker sent successfully!")
                        (log/error "Server rejected raw sticker:" (.-status resp)))))
             (.catch #(log/error "Sticker network error:" %)))))
     {})))
#+end_src


**** Reframe events and subscriptions


#+begin_src clojurescript :tangle ../../src/input/base.cljs
(re-frame/reg-event-db
 :sdk/upload-complete
 (fn [db _]
   (assoc db :uploading-files? false)))

(re-frame/reg-sub
 :input/uploading?
 (fn [db _]
   (:uploading-files? db false)))

(re-frame/reg-event-db
 :input/set-context
 (fn [db [_ room-id mode target-item]]
   (assoc-in db [:input-context room-id]
             {:mode mode
              :target target-item})))

(re-frame/reg-event-db
 :input/clear-context
 (fn [db [_ room-id]]
   (update db :input-context dissoc room-id)))

(re-frame/reg-sub
 :input/context
 (fn [db [_ room-id]]
   (get-in db [:input-context room-id])))
#+end_src


**** Inline Editor Component

This is the editor used for editing to be specific. Outside that it likely won't
be used.

#+begin_src clojurescript :tangle ../../src/input/base.cljs
(defn inline-editor [item active-id]
  (r/with-let [!editor (r/atom nil)]
    (fn [item active-id]
      (let [m-content    (get-in item [:content :inner :content])
            raw-html     (:html m-content)
            initial-text (if (seq raw-html)
                           (prepare-html-for-editor raw-html)
                           (or (:body m-content) ""))
            _ (log/debug initial-text)
            _ (log/debug raw-html)
            ]
        [:div.inline-editor-wrapper
         [:div.inline-editor-box
          [:> tiptap-component
           #js {:activeId active-id
                :loadedText initial-text
                :onEditorReady #(reset! !editor %)
                :onSend (fn [text html]
                          (let [matrix-html (get-matrix-formatted-body @!editor)]
                            (re-frame/dispatch [:msg/edit active-id item text matrix-html])
                            (re-frame/dispatch [:input/clear-context active-id])))}]]
         [:div.inline-editor-hint
          "escape to "
          [:span.link-btn {:on-click #(re-frame/dispatch [:input/clear-context active-id])} "cancel"]
          " • enter to "
          [:span.link-btn {:on-click (fn []
                                       (when-let [ed @!editor]
                                         (let [text (.getText ed)
                                               matrix-html (get-matrix-formatted-body ed)]
                                           (re-frame/dispatch [:msg/edit active-id item text matrix-html])
                                           (re-frame/dispatch [:input/clear-context active-id]))))} "save"]]]))))
#+end_src


**** Message Input Component

This is the main composer the user will interact with.
It is important that this provides a clean and fluid experience.
Ideally, we should break this apart more later.

***** TODO Placeholder text isn't update on i18n language change


***** Component

#+begin_src clojurescript :tangle ../../src/input/base.cljs
(defn message-input []
  (r/with-let [!picker-open? (r/atom false)
               !editor       (r/atom nil)
               !sug-command  (r/atom nil)]
    (fn []
      (let [active-id   @(re-frame/subscribe [:rooms/active-id])
            uploading?  @(re-frame/subscribe [:input/uploading?])
            attachments @(re-frame/subscribe [:composer/attachments active-id])
            loaded-text @(re-frame/subscribe [:composer/loaded-text active-id])
            context     @(re-frame/subscribe [:input/context active-id])
            tr          @(re-frame/subscribe [:i18n/tr])
            ]

        [:div.timeline-input-outer
         [suggestion-menu
          (fn [item]
            (when-let [cmd @!sug-command]
              (cmd #js {:props item})))]
         (when @!picker-open?
           [emoji-sticker-board
            {:on-close #(reset! !picker-open? false)
             :on-send-sticker
             (fn [mxc alt-text info]
               (re-frame/dispatch [:sdk/send-sticker active-id mxc alt-text info])
               (reset! !picker-open? false))
             :on-insert-native
             (fn [unicode-char]
               (when-let [ed @!editor]
                 (-> ed .chain .focus (.insertContent unicode-char) .run)))
             :on-insert-emoji
             (fn [shortcode url]
               (when-let [ed @!editor]
                 (-> ed .chain .focus
                     (.insertContent #js {:type "customEmote"
                                          :attrs #js {:shortcode shortcode
                                                      :src (mxc->url url)
                                                      :mxc url}})
                     .run))
               (reset! !picker-open? false))}])
         (when (and context (= (:mode context) :reply))
           (let [
                 sender-name (truncate-name (-> context :target :sender-name) 32)
                 ]
             [:div.input-context-banner
              [:div.context-info
               [:span (tr [:composer/replying-to] [sender-name])]]
              [:button.context-cancel-btn
               {:on-click #(re-frame/dispatch [:input/clear-context active-id])} [icons/exit]]]))

         [:div.timeline-input-wrapper
          (when (seq attachments)
            [:div.composer-attachments
             (doall
              (map-indexed (fn [idx att]
                             ^{:key (str "att-" idx)}
                             [attachment-preview active-id att idx])
                           attachments))])

          (when uploading?
            ^{:key "upload-indicator"}
            [:div.upload-indicator
             [:span.upload-text (tr [:composer/uploading])]
             [:div.upload-progress-bar [:div.upload-progress-fill]]])

          ^{:key "composer-input-row"}
          [:div.timeline-input-row
           [:label.timeline-upload-btn
            {:title (tr [:composer/upload-tooltip])}
            [:input {:type "file"
                     :multiple true
                     :style {:display "none"}
                     :on-change (fn [e]
                                  (let [files      (.. e -target -files)
                                        file-array (js/Array.from files)]
                                    (when (seq file-array)
                                      (re-frame/dispatch [:sdk/handle-file-drop active-id file-array]))
                                    (set! (.-value (.-target e)) "")))}]
            [icons/plus]]
           [:div.timeline-editor-container
            [:> tiptap-component
             #js {:activeId active-id
                  :key (str "editor-" active-id)
                  :loadedText loaded-text
                  :onChange (fn [text html]
                              (re-frame/dispatch [:composer/on-change active-id text html]))
                  :onSend (fn [text html]
                            (let [matrix-html (get-matrix-formatted-body @!editor)
                                  can-send? (or (not (str/blank? text))
                                                (str/includes? matrix-html "<img")
                                                (seq attachments))]
                              (if can-send?
                                (do
                                  (re-frame/dispatch [:composer/submit active-id text matrix-html])
                                  true)
                                false)))

                  :onFiles (fn [files]
                             (let [file-array (js/Array.from files)]
                               (re-frame/dispatch [:sdk/handle-file-drop active-id file-array])))
                  :placeholder (tr [:composer/placeholder]) ;; Not sure if needed since we use loaded-text
                  :onEditorReady #(reset! !editor %)
                  :onSuggestionStart (fn [cmd] (reset! !sug-command cmd))
                  :onSuggestionExit  (fn [] (reset! !sug-command nil))}]]
           [:button.timeline-emoji-btn
            {:on-click (fn [e]
                         (.stopPropagation e)
                         (swap! !picker-open? not))}
            [icons/smiley]]]]]))))
#+end_src

***** CSS

#+begin_src css :tangle ../../css/base-composer.css
.timeline-upload-btn,
.timeline-emoji-btn,
.timeline-send-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    background: transparent;
    border: none;
    color: var(--text-muted);
    transition: color 0.2s;
}

.timeline-upload-btn:hover,
.timeline-emoji-btn:hover {
    color: var(--text-main);
}

.timeline-send-btn {
    color: var(--accent-color);
}

.timeline-send-btn:hover {
    filter: brightness(1.2);
}

#+end_src


