
** Build

**** Preface

This actually isn't meant to be used within the repository itself.
It's construct made for plugins developers to utilize for their
plugins to behave correctly.

This is a solution to the limitation of the Small Clojure Interpreter
in which it can't expand compile time macros. So to facilitate that
behavior for plugin devs and avoid them needing to write in a manner
that they would find non-idiomatic... We have to provide them with
a simple compilation step in which we expand the macros and return
their ClojureScript code back to them with said expanded macros.

Done correctly and we can keep our SCI implementation and avoid
trying to make a AOT compilation of plugins the only solution.
That was another path I explored, but it proves to be
extremely brittle as the Google Closure library will end up
crafting code that is likely to break even between simple
versions. More so, it makes the dev and prod behavior...
untenable to say the least.

Another solution explored was Andare which would allow the Go blocks to
correctly expand at runtime and avoid the need for the JVM...
However, it is a bit out of date and would require being updated which
would've eaten a non-trivial amount of time. More so, it doesn't solve
the problem for OTHER macros. After all, our plugin devs may wish to
use macros freely.

So, I pondered the concepts and realized that we need to do some AOT work
in the form of macro expansion, but we don't actually need the compiled
javascript at all. This way we can let SCI do what it does best.

This proved remarkably effective as SCI was already doing quite well for
everything but macros in our plugin system. It neatly sandboxes behavior,
and it provides a much more well thought out solution for runtime
evaluation than I'd ever come up with on my own.

So the following file is the result of the above experimentation.
Effectively we've made a build script that traverse the AST and just
expands the macros as it encounters them. It is extremely likely it'll
need improvements as time goes on, but for just proving the concept
and providing the base feature set... It is perfect.

One regret is that I didn't write more on this topic.


**** Imports


#+begin_src clojurescript :tangle ../../src/utils/build.clj
(ns utils.build
  (:require
   [utils.macros]
   [clojure.java.io :as io]
   [clojure.edn :as edn]
   [clojure.walk :as walk]
   [clojure.string :as str]
   [cljs.tagged-literals :as tags]
   [clojure.core.async]
   [clojure.tools.analyzer.passes.jvm.validate]))
#+end_src


**** Sanitization

We need to ensure we don't leak any Java specific namespaces into the code
as well as ensuring no invalid CLJS pieces are evaluated

#+begin_src clojurescript :tangle ../../src/utils/build.clj
(defn sanitize-ast [form]
  (walk/prewalk
    (fn [x]
      (cond
        (or (seq? x) (vector? x) (map? x) (set? x) (list? x)) x
        (or (symbol? x) (keyword? x) (string? x) (number? x) (boolean? x) (nil? x)) x
        (instance? java.util.regex.Pattern x) x
        (instance? cljs.tagged_literals.JSValue x)
        (list 'cljs.core/clj->js (:val x))
        (instance? java.lang.Class x)
        (symbol (.getName ^java.lang.Class x))
        (instance? clojure.lang.Var x)
        (symbol (str (.name (.ns ^clojure.lang.Var x)) "/" (.sym ^clojure.lang.Var x)))
        :else
        (do
          (println "\n SCRUBBED JVM OBJECT \n")
          (println "Type: " (type x))
          (println "Value:" x)
          (println "----------------------------------\n")
          (symbol (str "ROGUE_OBJECT_" (.getSimpleName (type x)))))))
    form))


(defn scrub-jvm-artifacts [form]
  (walk/prewalk
    (fn [x]
      (cond
        (and (seq? x) (= (first x) 'clojure.lang.Var/getThreadBindingFrame)) nil
        (and (seq? x) (= (first x) 'clojure.lang.Var/resetThreadBindingFrame)) nil
        (and (seq? x) (= (first x) 'java.util.concurrent.atomic.AtomicReferenceArray.)) (list 'clojure.core/make-array (second x))
        (= x 'java.lang.Throwable) ':default
        (and (seq? x) (symbol? (first x)) (= (name (first x)) "return-chan"))
        (let [state-arr (second x)
              ret-val   (nth x 2)]
          (list 'let ['c (list 'clojure.core/aget state-arr 5)]
                (list 'if-not (list 'nil? ret-val)
                      (list 'cljs.core.async/put! 'c ret-val (list 'fn ['_] (list 'cljs.core.async/close! 'c)))
                      (list 'cljs.core.async/close! 'c))
                'c))

        (and (seq? x) (symbol? (first x)) (= (name (first x)) "aget-object") (str/includes? (namespace (first x)) "ioc-macros"))
        (cons 'clojure.core/aget (rest x))

        (and (seq? x) (symbol? (first x)) (= (name (first x)) "aset-object") (str/includes? (namespace (first x)) "ioc-macros"))
        (cons 'clojure.core/aset (rest x))

        (= x 'clojure.core/identical?) 'cljs.core/keyword-identical?

        (symbol? x)
        (let [ns-str   (namespace x)
              name-str (name x)]
          (cond
            (and ns-str (str/includes? ns-str "ioc-macros") (str/ends-with? name-str "-IDX"))
            (case name-str
              "STATE-IDX" 1
              "EXCEPTION-IDX" 2
              "BINDINGS-IDX" 3
              "RUN-FN-IDX" 4
              "USER-START-IDX" 5
              x)

            ns-str
            (let [cljs-ns  (str/replace ns-str #"^clojure" "cljs")
                  final-ns (if (= cljs-ns "cljs.core.async.impl.ioc-macros")
                             "cljs.core.async.impl.ioc-helpers"
                             cljs-ns)]
              (symbol final-ns name-str))

            :else x))
        :else x))
    form))
#+end_src


**** Macro Expansion

This is our rather brittle and hard-coded macro expansion statement.
For now, adding custom macros on the plugin devs end isn't exactly
easily done. It'll be something that needs to be revisited.

#+begin_src clojurescript :tangle ../../src/utils/build.clj

(defn custom-macro? [sym]
  (when (symbol? sym)
    (let [macro-var (ns-resolve 'utils.macros (symbol (name sym)))]
      (and macro-var
           (:macro (meta macro-var))
           (= (ns-name (:ns (meta macro-var))) 'utils.macros)))))

(defn expand-macros [form]
  (with-redefs [clojure.tools.analyzer.passes.jvm.validate/validate identity]
    (walk/prewalk
      (fn [x]
        (if (seq? x)
          (let [sym (first x)]
            (cond
              (#{'go 'cljs.core.async/go} sym)
              (let [qualified (walk/prewalk #(case % <! 'clojure.core.async/<! put! 'clojure.core.async/put! timeout 'clojure.core.async/timeout alts! 'clojure.core.async/alts! %) (rest x))
                    expanded  (macroexpand-1 `(clojure.core.async/go ~@qualified))]
                (scrub-jvm-artifacts expanded))

              (custom-macro? sym)
              (let [qualified-macro (symbol "utils.macros" (name sym))]
                (macroexpand-1 (cons qualified-macro (rest x))))
 w
              :else x))
          x))
      form)))

#+end_src


**** Running



#+begin_src clojurescript :tangle ../../src/utils/build.clj
(defn read-cljs [s]
  (binding [*data-readers* tags/*cljs-data-readers*]
    (read-string s)))

(defn process-and-expand-file [file-path]
  (let [raw-code     (slurp file-path)
        wrapped-text (str "(do\n" raw-code "\n)")
        ast-form     (read-cljs wrapped-text)
        expanded-ast (expand-macros ast-form)
        pure-ast     (sanitize-ast expanded-ast)]
    (pr-str pure-ast)))
#+end_src


#+begin_src clojurescript :tangle ../../src/utils/build.clj
(defn -main [& args]
  (let [metadata        (edn/read-string (slurp "manifest.edn"))
        ui-form-str     (process-and-expand-file "src/ui.cljs")
        worker-form-str (process-and-expand-file "src/worker.cljs")
        payload         (assoc metadata
                               :ui-form-str ui-form-str
                               :worker-form-str worker-form-str)

        out-dir         (io/file "dist")
        out-file        (io/file out-dir "plugin.edn")]

    (when-not (.exists out-dir)
      (.mkdir out-dir))

    (spit out-file (pr-str payload))
    (println "Plugin packed and AOT-expanded successfully to" (.getPath out-file))))
#+end_src



On the plugin dev's side they don't really have to think deeply on this. For the most part,
they might not even need the macro-expansion build.

All that is needed in the template repo deps.edn is:
#+begin_src clojurescript
  :aliases {
   :build {:main-opts ["-m" "utils.build"]}}

#+end_src

Which, of course, is provided for them.




