
** Macros


**** Preface

So we need some helper macros to cover a number of circumstances whether that be
just shortening or cleaning up usage to patching Vite and other incompatibilities.


**** Imports

#+begin_src clojurescript :tangle ../../src/utils/macros.cljc
(ns utils.macros
  (:require [clojure.java.io :as io]
            [clojure.edn :as edn]))
#+end_src


**** Safe Rust Object Prototype Calling

These macros are effectively just wrappers that provide clean
interop with the underlying Rust objects as the Rust objects
tend to utilize prototypes heavily as a result of how UniFFI
outputs them.
#+begin_src clojurescript :tangle ../../src/utils/macros.cljc
(defmacro ocall
  [obj method & args]
  `(let [obj# ~obj
         m# ~(name method)
         f# (js/goog.object.get obj# m#)]
     (if (fn? f#)
       (.apply f# obj# (cljs.core/array ~@args))
       (throw (js/Error. (str "Method " m# " is not a function (is it a property?)"))))))


(defmacro oget
  "Property access for WASM objects that hides behind prototypes."
  [obj prop]
  `(js/goog.object.get ~obj ~(name prop)))
#+end_src



**** Generating Translation map (Depreciated)

This allows us to aggregate the language JSONs from the node_modules
in order to serve them properly to users. It's just a fancy way
to write a dynamic import of JSONs for ClojureScript.
#+begin_src clojurescript :tangle ../../src/utils/macros.cljc
(defmacro gen-translation-map [dir-path]
  (let [files (filter #(.endsWith (.getName %) ".json") 
                      (file-seq (io/file dir-path)))
        mapping (into {} (for [f files]
                           (let [lang (second (re-find #"([^/]+)\.json$" (.getPath f)))]
                             [lang `(fn [] (js/import ~(.getPath f)))])))]
    mapping))
#+end_src


Load our static macros and provide them globally
#+begin_src clojurescript :tangle ../../src/utils/macros.cljs
(ns utils.macros
  (:require-macros [utils.macros :refer [load-static-config]]))
(def config (load-static-config "config.edn"))
(def i18n-data (load-static-config "i18n.edn"))
#+end_src

Loading non-secret variables at runtime is fairly straightforward.
We can declare them as a EDN (extensible data notation) file and then
write them as a Clojure map to easily consume at start.
This way we don't have to convert or do anything odd to have consistently
usable configs across the application.


**** Config EDN Loading

#+begin_src clojurescript :tangle ../../src/utils/macros.cljc
(defmacro load-static-config [path]
  (edn/read-string (slurp path)))
#+end_src
