
** Net

**** Preface

We need a convenient way to pass functionality around between native and web. We can easily do this by
making wrapper functions to catch the specific calls needed.

**** Imports

#+begin_src clojurescript :tangle ../../src/utils/net.cljs
(ns utils.net
  (:require ["@capacitor/core" :refer [Capacitor CapacitorHttp]]
            [promesa.core :as p]
            [taoensso.timbre :as log]
            [clojure.string :as str]
            ))
#+end_src

**** Auth Context


This is a mechanism we can use to set in both the web worker thread and the
main thread. It isn't entirely optimal, but it does ensure
that we can easily update the fetches to use the correct client.

We may need to check to ensure we're disposing of the previous
client when the account is swapped (among other reset operations).
#+begin_src clojurescript :tangle ../../src/utils/net.cljs
(defonce !auth-context (atom {:token nil :hs-url nil}))

(defn set-auth-context! [token hs-url]
  (reset! !auth-context {:token token :hs-url hs-url}))
#+end_src


Similar to how we do in the service worker, we want to be certain we never send
the token to an endpoint that doesn't need it.

#+begin_src clojurescript :tangle ../../src/utils/net.cljs
(defn- safe-auth-path? [request-url hs-url]
  (try
    (let [req-obj (js/URL. request-url)
          hs-obj  (js/URL. hs-url)
          path    (.-pathname req-obj)]
      (and (= (.-origin req-obj) (.-origin hs-obj))
           (str/includes? path "/_matrix/client/v1/media/")))
    (catch :default _ false)))

(defn ensure-protocol [hs-url]
  (if (or (str/starts-with? hs-url "http://")
          (str/starts-with? hs-url "https://"))
    hs-url
    (str "https://" hs-url)))
#+end_src


We need a clean method to swap between using the generic fetch and the Capacitor.
To be clear, this is only needed because iOS still does not expose the service
worker in their web views in a rational manner. The AppBound setting is highly
restrictive and not consistent either.

More readings:
https://capacitorjs.com/docs/config
https://webkit.org/blog/10882/app-bound-domains/
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker

In an ideal world, we wouldn't even need this.
I considered just monkey patching the global JS item, but since
we do some level of URL validation in the service worker this may be
more sensible.
I can later revise the SW to use this mechanism instead to remove the duplication.
#+begin_src clojurescript :tangle ../../src/utils/net.cljs
(defn- wait-for-auth []
  (p/create
   (fn [resolve]
     (let [{:keys [token hs-url]} @!auth-context]
       (if (and token hs-url)
         (resolve true)
         (let [watch-key (keyword (gensym "auth-watch"))
               timer     (js/setTimeout #(do
                                           (remove-watch !auth-context watch-key)
                                           (resolve false))
                                        2000)]
           (add-watch !auth-context watch-key
                      (fn [_ _ _ new-state]
                        (when (and (:token new-state) (:hs-url new-state))
                          (js/clearTimeout timer)
                          (remove-watch !auth-context watch-key)
                          (resolve true))))))))))

(defn fetch
  ([url] (fetch url nil))
  ([raw-url options]
   (p/let [opts         (cond
                          (nil? options) #js {}
                          (map? options) (reduce-kv (fn [acc k v]
                                                      (aset acc (name k) v) acc)
                                                    #js {} options)
                          :else (js/Object.assign #js {} options))
           is-absolute? (or (str/starts-with? raw-url "http://")
                            (str/starts-with? raw-url "https://"))
           needs-wait?  (or (.-auth opts)
                            (str/includes? raw-url "/_matrix/client/v1/media/"))
           _            (when needs-wait?
                          (wait-for-auth))
           {:keys [token hs-url]} @!auth-context
           method       (or (.-method opts) "GET")
           headers      (or (.-headers opts) #js {})
           safe-headers (js/Object.assign #js {} headers)
           wants-auth?  (or (.-auth opts)
                            is-media?
                            (and is-absolute?
                                 hs-url
                                 (safe-auth-path? raw-url hs-url)))]
     (when (and token wants-auth?)
       (aset safe-headers "Authorization" (str "Bearer " token)))
     (js-delete opts "auth")
     (aset opts "headers" safe-headers)
     (js/fetch raw-url opts))))
#+end_src


