
** Core

The initial namespace in which we start the application.
We'll aim to keep everything neatly segmented, but as we start scaffolding
components it is likely that there will be some residual items until we finalize
pieces.

**** Imports

#+begin_src clojurescript :tangle ../../src/client/core.cljs
(ns client.core
  (:require
   [utils.logger :as logger]
   [re-frame.core :as re-frame]
   [app :as app]
   [promesa.core :as p]
   [client.state :as state]
   [client.session-store :as store]
   [cljs-workers.core :as main]
   [cljs.core.async :refer [go <!]]
   [taoensso.timbre :as log]))
#+end_src


**** The Web Worker

So we need to initialize the web worker more or less immediately

Now we want these to behave as a stream, so we register them and what
reframe event they should trigger here.
#+begin_src clojurescript :tangle ../../src/client/core.cljs
(defn handle-worker-stream! [data]
  (let [msg-type (:type data)]
    (case msg-type
      "home-rooms-diff"      (re-frame/dispatch [:room-list/set-home-rooms-sync (:rooms data)])
      "bg-rooms-diff"        (re-frame/dispatch [:room-list/set-bg-rooms-sync (:rooms data)])
      "global-spaces-diff"   (re-frame/dispatch [:sdk/set-spaces-list-sync (:spaces data)])
      "space-rooms-diff"     (re-frame/dispatch [:sdk/update-space-view (:space-id data) (:rooms data)])
      "room-parent-resolved" (re-frame/dispatch [:rooms/apply-parent-resolution (:room-id data) (:first-parent-id data)])
      "room-preview-resolved"  (re-frame/dispatch [:rooms/set-preview (:room-id data) (:preview data)])
      "timeline-diff"
      (let [source (keyword (:source data))
            events (mapv (fn [e]
                           (-> e
                               (assoc :timeline-source source)
                               (update :type keyword)))
                         (:events data))]
        (re-frame/dispatch [:sdk/update-timeline (:room-id data) source events]))

      "widget-message"    (re-frame/dispatch [:call/recv-widget-message (:data data)])
      "recovery-state-update"  (re-frame/dispatch [:sdk/handle-recovery-stream (keyword (:state data))])
      "timeline-loading"  (re-frame/dispatch [:timeline/set-loading (:room-id data) (:loading? data)])
      "typing-update"     (re-frame/dispatch [:sdk/update-typing-users (:room-id data) (:users data)])
      "pagination-status" (re-frame/dispatch [:sdk/update-pagination-status (:room-id data) (:status data)])
      nil)))
#+end_src

Now we want to just create a pool of one for the rust-sdk to execute on.
#+begin_src clojurescript :tangle ../../src/client/core.cljs
(defn init-worker! []
  (when-not @state/!engine-pool
    (reset! state/!engine-pool
            (main/create-pool 1 "engine.js"
                              {:worker-opts #js {:type "module"}
                               :on-stream handle-worker-stream!}))))
#+end_src


**** Bootstrapping and Sync Reframe events

We intend to this to be passed as a callback where needed and handle any client
operations here up until the point in which the client is 'started'.
#+begin_src clojurescript :tangle ../../src/client/core.cljs
(re-frame/reg-event-fx
 :app/bootstrap
 (fn [_ [_ target-user-id]]
   (log/debug "Bootstrapping:" target-user-id)
   (init-worker!)
   (go
     (let [pool @state/!engine-pool
           init-res (<! (main/do-with-pool! pool {:handler :init-wasm}))]
       (if (= (:status init-res) "success")
         (let [boot-res (<! (main/do-with-pool! pool {:handler :bootstrap
                                                      :arguments {:target-user-id target-user-id}}))]
           (case (:status boot-res)
             "success" (re-frame/dispatch [:auth/login-success boot-res])
             "empty"   (re-frame/dispatch [:auth/set-status :logged-out])
             "error"   (log/error "Bootstrap failed:" (:msg boot-res))))
         (log/error "WASM failed to load!" (:msg init-res)))))
   {}))

(re-frame/reg-event-fx
 :sdk/start-sync
 (fn [_ _]
   (go
     (let [pool @state/!engine-pool
           res  (<! (main/do-with-pool! pool {:handler :start-sync}))]
       (if (= (:status res) "success")
         (log/info "Matrix sync loop started successfully.")
         (log/error "Failed to start sync:" (:msg res)))))
   {}))

(re-frame/reg-event-fx
 :sdk/ignite-session
 (fn [_ _]
   {:fx [[:dispatch [:sdk/start-sync]]
         [:dispatch [:sdk/fetch-own-profile]]
         [:dispatch [:sdk/fetch-all-emotes]]]}))
#+end_src

**** Initialize the application!

Provides the entry-point for the application that Vite and the index.html enter from.
#+begin_src clojurescript  :tangle ../../src/client/core.cljs
(defn ^:export init []
  (app/init)
  (logger/init!)
  (log/debug  "Entering Paradise!")
  )
#+end_src

