#+begin_src clojurescript :tangle ../../src/client/session_store.cljs
(ns client.session-store
  (:require [promesa.core :as p]
            [taoensso.timbre :as log]
            ["ffi-bindings" :as sdk]))
#+end_src

*** Constants and Utilities

First, we define the file used in OPFS.
This is the "root" file under which all user sessions will be serialized.
#+begin_src clojurescript :tangle ../../src/client/session_store.cljs
(def ^:private file-name "mx_session_v3.json")
#+end_src


We need a helper to verify we can actually find the Rust classes.
This grabs the Session constructor from the matrix_sdk namespace within our bundle.
#+begin_src clojurescript :tangle ../../src/client/session_store.cljs
(defn- get-session-class []
  (let [sdk-root (if (.-Session sdk) sdk (.-default sdk))]
    (if sdk-root
      (.-Session sdk-root)
      (log/error "FATAL: Could not find Session class on root SDK object."))))
#+end_src


*** Persistence Helpers

We need standard low-level helpers to read and write raw JSON to the OPFS.
We keep these as simple JavaScript object operations to avoid unnecessary overhead from
converting back and forth to Clojure maps constantly.
#+begin_src clojurescript :tangle ../../src/client/session_store.cljs
(defn- load-raw-sessions-opfs []
  (p/let [dir (.. js/navigator -storage getDirectory)
          file-handle (.getFileHandle dir file-name #js {:create true})
          sync-handle (.createSyncAccessHandle file-handle)]
    (try
      (let [size (.getSize sync-handle)]
        (if (zero? size)
          #js {}
          (let [buffer (js/Uint8Array. size)]
            (.read sync-handle buffer #js {:at 0})
            (let [decoder (js/TextDecoder.)
                  text (.decode decoder buffer)]
              (.parse js/JSON text)))))
      (finally
        (.close sync-handle)))))

(defn- save-raw-sessions-opfs! [sessions-obj]
  (p/let [dir (.. js/navigator -storage getDirectory)
          file-handle (.getFileHandle dir file-name #js {:create true})
          sync-handle (.createSyncAccessHandle file-handle)]
    (try
      (let [encoder (js/TextEncoder.)
            text (.stringify js/JSON sessions-obj)
            buffer (.encode encoder text)]
        (.truncate sync-handle 0)
        (.write sync-handle buffer #js {:at 0})
        (.flush sync-handle))
      (finally
        (.close sync-handle)))))
#+end_src

We also need a cryptographic implementation for generating passphrases.
The Rust SDK uses this passphrase to encrypt the IndexedDB where the actual keys and messages live.
#+begin_src clojurescript :tangle ../../src/client/session_store.cljs
(defn generate-passphrase []
  (let [array (js/Uint8Array. 32)]
    (.getRandomValues js/crypto array)
    (js/btoa (.apply js/String.fromCharCode nil array))))
#+end_src


#+begin_src clojurescript :tangle ../../src/client/session_store.cljs
(defn- generate-uuid []
  (if (and (exists? js/crypto) (exists? (.-randomUUID js/crypto)))
    (.randomUUID js/crypto)
    (let [template "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx"]
      (.replace template
                (js/RegExp. "[xy]" "g")
                (fn [c]
                  (let [r (bit-or (* (js/Math.random) 16) 0)
                        v (if (= c "x") r (bit-or (bit-and r 0x3) 0x8))]
                    (.toString v 16)))))))
#+end_src


****** Settings IndexedDB

 We will need to persist settings for the applications usage.
Webviews or browsers, IndexedDB will work just fine for this.
OPFS is unideal for the main thread to use and we don't really
*need* it.


*** IndexedDB Management

This function handles the deletion of the encrypted database.
It wraps the raw IDBRequest in a Promise so we can await its
completion before clearing the session metadata.
We standardize on the name prefix closura-store-.
#+begin_src clojurescript :tangle ../../src/client/session_store.cljs
(defn- delete-store-impl! [store-id]
  (let [store-name (str "paradise-store-" store-id)]
    (js/Promise.
     (fn [resolve _]
       (let [request (.deleteDatabase js/indexedDB store-name)]
         (set! (.-onsuccess request) #(resolve true))
         (set! (.-onerror request) #(resolve false))
         (set! (.-onblocked request) #(resolve false)))))))
#+end_src


There is a need to provide the token to the service workers if we're to
provide rich message data to the user. Using the IndexedDB is convenient
here as we can provide multi-account notification support without much
overhead by baking the preparation into the session handling.
It should be noted that the vulnerability is the same here as it would be
in the local storage. Any cross site scripting attack will impact either,
so the choice to do this isn't inherently worse.

This is removed. Will clean up in the future.

#+begin_src clojurescript :tangle ../../src/client/session_store.cljs
#_(defn- sync-to-sw-vault! [sessions-obj]
  (let [user-keys (js/Object.keys sessions-obj)]
    (when (pos? (.-length user-keys))
      (let [request (.open js/indexedDB "sw-vault" 1)]
        (set! (.-onupgradeneeded request)
              (fn [e]
                (let [db (.. e -target -result)]
                  (.createObjectStore db "tokens" #js {:keyPath "userId"}))))
        (set! (.-onsuccess request)
              (fn [e]
                (let [db (.. e -target -result)
                      tx (.transaction db #js ["tokens"] "readwrite")
                      store (.objectStore tx "tokens")]
                  (.clear store)
                  (doseq [user-id user-keys]
                    (let [data (aget sessions-obj user-id)
                          session (aget data "session")
                          token (aget session "accessToken")
                          device-id (aget session "deviceId")
                          hs-url (aget session "homeserverUrl")]
                      (.put store #js {:userId    user-id
                                       :token      token
                                       :deviceId  device-id
                                       :hsUrl     hs-url
                                       :updatedAt (js/Date.now)}))))))))))



#+end_src


*** Implementation Logic

These functions form the "brain" of the store.
They are defined outside the deftype for easier testing and cleaner syntax.


This re-hydrates the Rust Session objects. The data in localStorage is just JSON;
we must pass it into Session.new() so the SDK can use it.
#+begin_src clojurescript :tangle ../../src/client/session_store.cljs
(defn- load-sessions-impl []
  (p/let [sessions (load-raw-sessions-opfs)
          Session (get-session-class)]
    (when Session
      (doseq [user-id (js/Object.keys sessions)]
        (let [data (aget sessions user-id)]
          (aset sessions user-id
                #js {:session (.new Session (aget data "session"))
                     :passphrase (aget data "passphrase")
                     :storeId (aget data "storeId")}))))
    sessions))
#+end_src

Updates a specific user's session while preserving others.
#+begin_src clojurescript :tangle ../../src/client/session_store.cljs
(defn- save-session-impl! [session passphrase store-id]
  (p/let [user-id (.-userId session)
          sessions (load-raw-sessions-opfs)
          existing (aget sessions user-id)
          final-pass (or passphrase (when existing (aget existing "passphrase")))
          final-id   (or store-id   (when existing (aget existing "storeId")))]
    (when (and final-pass final-id)
      (aset sessions user-id #js {:session session
                                  :passphrase final-pass
                                  :storeId final-id})
      (save-raw-sessions-opfs! sessions))))
#+end_src

Removed

#+begin_src clojurescript :tangle ../../src/client/session_store.cljs
#_(defn- clear-sw-vault-user! [user-id]
  (let [request (.open js/indexedDB "sw-vault" 1)]
    (set! (.-onsuccess request)
          (fn [e]
            (let [db (.. e -target -result)
                  tx (.transaction db #js ["tokens"] "readwrite")
                  store (.objectStore tx "tokens")]
              (.delete store user-id))))))
#+end_src

Removes the specific user's database and metadata.
#+begin_src clojurescript :tangle ../../src/client/session_store.cljs
(defn- clear-session-impl! [user-id]
  (p/let [sessions (load-raw-sessions-opfs)
          data (aget sessions user-id)]
    (when-let [sid (and data (aget data "storeId"))]
      (delete-store-impl! sid))
    (js-delete sessions user-id)
    (save-raw-sessions-opfs! sessions)))
#+end_src


*** The SessionStore Class

Finally, we wrap everything in a deftype. This compiles to a JavaScript class,
making it compatible with the patterns expected by the Matrix SDK and UI layers.
We use Object to implement the methods directly on the prototype.
#+begin_src clojurescript :tangle ../../src/client/session_store.cljs
(deftype SessionStore []
  Object
  (loadSessions [this]
    (load-sessions-impl))

  (save [this session passphrase store-id]
    (save-session-impl! session passphrase store-id))

  (generatePassphrase [this]
    (generate-passphrase))

  (generateStoreId [this]
    (generate-uuid))

  (getStoreName [this store-id]
    (str "paradise-store-" store-id))

  (clear [this user-id]
    (clear-session-impl! user-id)))

#+end_src
