
* App


After having explored setting up and interfacing with the Rust sdk I believe we're in a good state to actually
start building out the *actual* UI.
Now re-frame more or less trivializes this and enables us to write a UI and then wire it up later.


**** Preface

For base functionality I would define the minimum usable product as:
- Spaces navigation (and DMs)
- Room navigation
- Timeline
- Message box
- Login

So these would be the first things to build on.
We'll continue to keep our minimalist login page, but we'll start trying to do a bit more polish on the
actual UI components themselves.


**** Imports

#+begin_src clojurescript :tangle ../src/app.cljs
(ns app
  (:require
   [re-frame.core :as re-frame]
   [taoensso.timbre :as log]
   [promesa.core :as p]
   [clojure.string :as str]
   [reagent.core :as r]
   [reagent.dom.client :as rdom]
   [navigation.spaces.bar :refer [spaces-sidebar]]
   [client.key-handler :refer [global-key-listener]]
   [overlays.notifications :as notifications]
   [overlays.settings]
   [overlays.quick-switcher]
   [overlays.lightbox]
   [overlays.profiles]
   [overlays.reactions]
   [auth.events :refer [login-screen]]
   [container.call.call-container :refer [persistent-call-container]]
   [client.config :refer [load-config check-remote-version load-i18n]]
   [client.state :refer [!config]]
   [client.session-store :as store]
   [taoensso.tempura :as tempura :refer [tr]]
   [utils.global-ui :refer [global-reaction-picker modal-root popover-root global-context-menu satellite-overlay make-swipe-handlers]]
   ["@capacitor/status-bar" :refer [StatusBar]]
   ["@capacitor/app" :refer [App]]
   [utils.macros :refer [i18n-data]]
   [utils.svg :as icons]
   [navigation.rooms.room-list :refer [room-list]]
   [container.base :refer [container]]
   ))
#+end_src


**** Reframe DB declaration

For testing purposes we'd want to stage a general UI to template against.
This also serves as a good example of where to start with modifying the UI
#+begin_src clojurescript :tangle ../src/app.cljs
#_(def default-db
  {:spaces {"!space1:example.com" {:id "!space1:example.com" :name "Main Space" :parent-id nil}
            "!space2:example.com" {:id "!space2:example.com" :name "Sub Space" :parent-id "!space1:example.com"}
            "!space3:example.com" {:id "!space3:example.com" :name "Other Space" :parent-id nil}}
   :rooms {"!room1:example.com" {:id "!room1:example.com" :name "general" :parent-id "!space1:example.com"}
           "!room2:example.com" {:id "!room2:example.com" :name "random" :parent-id "!space1:example.com"}
           "!room3:example.com" {:id "!room3:example.com" :name "cljs-dev" :parent-id "!space2:example.com"}}
   :active-space-id "!space1:example.com"
   :active-room-id "!room1:example.com"})


(def default-db
  {:spaces {}
   :rooms  {}
   :active-space-id nil
   :active-room-id  nil
   :auth-status :checking
   :login-error nil
   :client nil
   :config {:version "0.0.0"}
   :locale :en
   :dictionary {}
   :update-available? false}
   )
#+end_src

This is the initializer for the global reframe object
For some more info you can look here:
https://day8.github.io/re-frame/application-state/
#+begin_src clojurescript :tangle ../src/app.cljs
(re-frame/reg-event-db
 :initialize-db
 (fn [_ _]
   default-db
   ))
#+end_src


**** UI Reframe Events and Subscriptions


#+begin_src clojurescript :tangle ../src/app.cljs

(re-frame/reg-fx
 :ui/blur-active
 (fn [_]
   (when-let [active-el (.-activeElement js/document)]
     (.blur active-el))))

(re-frame/reg-event-db
 :ui/clear-overlays
 (fn [db _]
   (-> db
       (assoc-in [:ui :sidebar-open?] false)
       (assoc-in [:active-popover] nil)
       (assoc-in [:active-modal] nil))))


(re-frame/reg-event-fx
 :ui/set-sidebar
 (fn [{:keys [db]} [_ open?]]
   (if open?
     (let [dispatches (cond-> []
                        (:active-modal db)   (conj [:ui/close-modal])
                        (:active-popover db) (conj [:ui/close-popover]))]
       (merge
        {:db (assoc-in db [:ui :sidebar-open?] true)
         :native/hide-keyboard nil
         :ui/blur-active nil}
        (when (seq dispatches)
          {:dispatch-n dispatches})))
     {:db (assoc-in db [:ui :sidebar-open?] false)})))


(re-frame/reg-event-db
 :ui/toggle-sidebar
 (fn [db _]
   (update-in db [:ui :sidebar-open?] not)))

(re-frame/reg-sub
 :ui/sidebar-open?
 (fn [db _]
   (get-in db [:ui :sidebar-open?] false)))

(re-frame/reg-event-db
 :ui/window-resized
 (fn [db [_ width]]
   (assoc-in db [:ui :mobile?] (< width 768))))

(re-frame/reg-sub
 :ui/mobile?
 (fn [db _]
   (get-in db [:ui :mobile?] false)))


(re-frame/reg-event-db
 :app/config-loaded
 (fn [db [_ config]]
   (assoc db :config config
             :update-available? false)))

(re-frame/reg-event-fx
 :app/poll-version
 (fn [{:keys [db]} [_ manual?]]
   (let [current-v (get-in db [:config :version])]
     (when current-v
       (-> (check-remote-version)
           (p/then (fn [remote-v]
                     (cond
                       (and remote-v (not= remote-v current-v))
                       (re-frame/dispatch [:app/update-detected])
                       manual?
                       (js/alert (str "You are up to date! (v" current-v ")"))))))
     {}))))

(re-frame/reg-event-db
 :app/update-detected
 (fn [db _]
   (assoc db :update-available? true)))

(re-frame/reg-sub
 :app/update-available?
 (fn [db _]
   (:update-available? db false)))

(re-frame/reg-sub
 :app/version
 (fn [db _]
   (get-in db [:config :version] "Unknown")))


(re-frame/reg-sub
 :i18n/tr
 (fn [db _]
   (let [locale (:locale db)
         dictionary (:dictionary db)]
     (partial tempura/tr {:dict dictionary} [locale :en]))))


#+end_src


***** i18n
So we utilize a library written by the same individual who created the logging solution we use.
It is called Tempura. It provides a nice and easy way to actually create mappings to entries
and easy use around the repository to utilize them.

We want to be sure with the reframe components that we don't call unnecessarily. So segmenting
locale and dictionary allows us to only ever update strings if we explicitly change the
displayed language.
#+begin_src clojurescript :tangle ../src/app.cljs
(re-frame/reg-sub
 :i18n/locale
 (fn [db _] (:locale db)))

(re-frame/reg-sub
 :i18n/dictionary
 (fn [db _] (:dictionary db)))

(re-frame/reg-sub
 :i18n/tr
 (fn [db _]
   (let [locale (get db :locale :en)
         dictionary (get db :dictionary {})]
     (if (empty? dictionary)
       (fn [k & _] (str "[" (name (last k)) "]"))
       (partial tempura/tr {:dict dictionary} [locale :en])))))

(re-frame/reg-event-db
 :i18n/set-dictionary
 (fn [db [_ dict]]
   (assoc db :dictionary dict)))

(re-frame/reg-event-db
 :i18n/set-locale
 (fn [db [_ locale]]
   (assoc db :locale locale)))


#+end_src




**** CSS Swapping

We want to provide style switching (and even layout behavior later)
This at least begins starting that off by providing some useful enough defaults.

#+begin_src clojurescript :tangle ../src/app.cljs
(re-frame/reg-event-fx
 :ui/hydrate-theme
 (fn [{:keys [db]} [_ theme-val]]
   {:dispatch [:ui/switch-theme theme-val]}))

(re-frame/reg-sub
 :ui/current-theme
 (fn [db _]
   (:ui/current-theme db "default")))

(re-frame/reg-event-fx
 :ui/reset-theme
 (fn [{:keys [db]} _]
   {:db (assoc db :ui/current-theme "default")
    :settings/save ["theme" "default"]
    :ui/hotswap-css "css/app.css"}))


(re-frame/reg-fx
 :ui/hotswap-css
 (fn [new-href]
   (if-let [link (.getElementById js/document "app-theme")]
     (do
       (set! (.-href link) new-href)
       (log/info "Swapped CSS to:" new-href))
     (log/error "Theme stylesheet link #app-theme not found!"))))

(re-frame/reg-event-fx
 :ui/switch-theme
 (fn [{:keys [db]} [_ theme-val]]
   (let [safe-theme (or theme-val "default")
         theme-str  (if (keyword? safe-theme) (name safe-theme) safe-theme)
         is-url?    (str/starts-with? theme-str "http")
         href       (if is-url?
                      theme-str
                      (str "css/" (case (keyword theme-str)
                                    :discord "cordlike.css"
                                    :matrix  "matrix.css"
                                    :retro   "retro.css"
                                    "app.css")))]
     {:db (assoc db :ui/current-theme theme-str)
      :settings/save ["theme" theme-str]
      :ui/hotswap-css href})))

#+end_src




**** Boot Screen / Loading Screen

We need a boot up screen for those moments where we're not quite ready.
Making sure this is dynamic, but abstract is important for now.
#+begin_src clojurescript :tangle ../src/app.cljs
(defn booting-screen []
  (let [tr @(re-frame/subscribe [:i18n/tr])]
    [:div.boot-container
     [:div.boot-content
      [:div.boot-logo-wrapper
       [icons/transition {:size "100px"}]
       ]
      [:div.boot-loading-text
       [:span (tr [:boot/loading-text])]]]]))
#+end_src

**** Base CSS

#+begin_src css :tangle ../css/app.css

@import "icons.css";
@import "room-list-entry.css";
@import "room-list.css";
@import "room-header.css";
@import "avatar.css";
@import "settings.css";
@import "emojis.css";
@import "settings.css";
@import "composer.css";
@import "timeline.css";
@import "virtualizer.css";
@import "space.css";
@import "container.css";
@import "space-icons.css";
@import "calls.css";
@import "attachments.css";
@import "drafts.css";
@import "global.css";
@import "lightbox.css";
@import "login.css";
@import "keyframes.css";
@import "member-list.css";
@import "base-composer.css";
@import "update-banner.css";
@import "reaction-modal.css";
@import "profiles.css";
@import "search.css";
@import "pins.css";
@import "plugin.css";
@import "switcher.css";


html, body {
    margin: 0;
    padding: 0;
    width: 100dvw;
    height: 100dvh;
    overflow: hidden;
    box-sizing: border-box;
    background-color: #313338;
    color: #dbdee1;
    font-family: sans-serif;
}

*, *::before, *::after {
    box-sizing: inherit;
}

#app {
    height: 100%;
    width: 100%;
    background: #1e1f22;
}

.app-root {
    display: flex;
    height: 100dvh;
    width: 100dvw;
    overflow: hidden;
}




[data-virtuoso-scroller="true"]::-webkit-scrollbar-thumb {
    background-clip: padding-box;
    border: 4px solid transparent;
    border-radius: 20px;
    background-color: transparent;
    transition: background-color 0.2s ease;
}

[data-virtuoso-scroller="true"]:hover::-webkit-scrollbar-thumb,
.is-scrolling [data-virtuoso-scroller="true"]::-webkit-scrollbar-thumb {
    background-color: rgba(255, 255, 255, 0.1);
}

[data-virtuoso-scroller="true"]::-webkit-scrollbar-thumb:hover {
    background-color: rgba(255, 255, 255, 0.4) !important;
}

[data-virtuoso-scroller="true"]::-webkit-scrollbar-thumb:active {
    background-color: rgba(255, 255, 255, 0.6) !important;
}


.mobile-menu-btn {
    display: none;
    background: none;
    border: none;
    color: #dbdee1;
    font-size: 24px;
    margin-right: 12px;
    cursor: pointer;
}


@media (max-width: 768px) {
    .mobile-menu-btn {
        display: block;
    }
}


@media (max-width: 768px) {
    .app-root {
        position: relative;
        overflow: hidden;
        padding-top: env(safe-area-inset-top, 0px);
        padding-bottom: 0px;
    }

    .timeline-container {
        width: 100vw;
        flex: 1;
    }

    .sidebar-spaces,
    .sidebar-rooms {
        position: absolute;
        display: flex;
        z-index: 100;
        min-height: 0;
        overflow-y: auto;
        top: env(safe-area-inset-top, 0px);
        bottom: 0;
        transform: translateX(-100%);
        transition: transform 0.3s ease;
    }


    .sidebars-open .sidebar-spaces {
        transform: translateX(0);
    }

    .sidebars-open .sidebar-rooms {
        transform: translateX(72px);
    }

    .mobile-overlay {
        position: fixed;
        padding-top: env(safe-area-inset-top, 0px);
/*
        bottom: env(safe-area-inset-bottom, 0px);
*/
        inset: 0;
        background: rgba(0, 0, 0, 0.5);
        z-index: 90;
        animation: fadeIn 0.2s ease;
    }
}

#+end_src


#+begin_src css :tangle ../css/update-banner.css
.global-update-banner {
  position: fixed;
  left: 0;
  right: 0;
  top: env(safe-area-inset-top, 0px);
  z-index: 9999999;
  background: var(--accent-primary);
  color: white;
  padding: 8px 16px;
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 12px;
  font-size: 14px;
  box-shadow: 0 2px 10px rgba(0,0,0,0.3);
}

.global-update-banner button {
  background: white;
  color: var(--accent-primary);
  border: none;
  padding: 4px 12px;
  border-radius: 4px;
  font-weight: bold;
  cursor: pointer;
}

#+end_src



**** Android Back

This just provides some basic behavior to the back button on Android.

****** TODO Add history to the DB so the back button can navigate around?

#+begin_src clojurescript :tangle ../src/app.cljs
(re-frame/reg-event-fx
 :native/hardware-back
 (fn [{:keys [db]} _]
   (cond
     (get-in db [:active-modal])
     {:dispatch [:ui/close-modal]}

     (get-in db [:active-popover])
     {:dispatch [:ui/close-popover]}

     (get-in db [:ui :sidebar-open?])
     {:dispatch [:ui/set-sidebar false]}

     ;; :else
     ;; {:dispatch [:nav/go-back]}
     )))

(defn init-capacitor-listeners! []
  (.addListener App "backButton"
                (fn [_]
                  (re-frame/dispatch [:native/hardware-back]))))
#+end_src






**** Application Layout

Now this is the actual code that handles rendering. Short, yeah?
It doesn't actually need to be overtly verbose. Reframe let's us
just focus on the part we actually care about. The benefits of Clojure
providing the encapsulation and parsing for us.


#+begin_src clojurescript :tangle ../src/app.cljs
(defn set-status-bar! []
  (.setBackgroundColor StatusBar #js {:color
                                      "#1e1f22"})
  (.setStyle StatusBar #js {:style "DARK"}))


(defn main-layout []
  (r/with-let [!drag-state (r/atom {:start-x nil :dx 0})]
    (let [auth-status   @(re-frame/subscribe [:auth/status])
          sidebar-open? @(re-frame/subscribe [:ui/sidebar-open?])
          update-ready? @(re-frame/subscribe [:app/update-available?])
          platform         (.getPlatform js/Capacitor)
          cushion       (if (= platform "ios")
                          "8px"
                          "max(env(safe-area-inset-bottom, 0px), 8px)")
          swipe-props (make-swipe-handlers
                       !drag-state
                       {:on-end (fn [dx]
                                  (let [start-x (:start-x @!drag-state)]
                                    (cond
                                      (and (not sidebar-open?) #_ (< start-x 40) (> dx 60))
                                      (re-frame/dispatch [:ui/set-sidebar true])
                                      (and sidebar-open? (< dx -60))
                                      (re-frame/dispatch [:ui/set-sidebar false]))))})]

      (case auth-status
        :checking [booting-screen]
        (:logged-out :authenticating) [login-screen]
        :logged-in
        [:<>
         (when update-ready?
           [:div.global-update-banner
            [:span "A new version of the app is available!"]
            [:button {:on-click #(re-frame/dispatch [:app/apply-update])}
             "Refresh"]])

         [persistent-call-container]
         (into [:div.app-root
                (merge {:class (when sidebar-open? "sidebars-open")
                        :style {:touch-action "pan-y"
                                :padding-bottom cushion
                                }}
                       swipe-props)]
               [[spaces-sidebar]
                [room-list]
                (when sidebar-open?
                  [:div.mobile-overlay {:on-click #(re-frame/dispatch [:ui/set-sidebar false])}])
                [container]
                ])
         [modal-root]
         [popover-root]
         [global-key-listener]
         [global-context-menu]]
        [:div "Unknown State"]))))

#+end_src


**** Resizing the Application


#+begin_src clojurescript :tangle ../src/app.cljs
(defn init-window-size-listener! []
  (re-frame/dispatch [:ui/window-resized (.-innerWidth js/window)])

  (let [resize-handler (goog.functions/debounce
                        #(re-frame/dispatch [:ui/window-resized (.-innerWidth js/window)])
                        150)]
    (.addEventListener js/window "resize" resize-handler)))

#+end_src


**** Mounting the Application

This is to mount our application at the element with the ID "root" inside
our index.html. It's effectively just an attachment point for us to latch
onto.
Also inside is th init function which informs reframe to start up
as well as a method that instructs shadow-cljs how to handle the re-render
when we detatch and reload (basically when you hit control + s to save).
#+begin_src clojurescript :tangle ../src/app.cljs
(defonce root (atom nil))

(defn mount-root []
 (re-frame/dispatch [:ui/switch-theme])
  (re-frame/clear-subscription-cache!)
  (let [container (.getElementById js/document "root")]
    (when-not @root
      (reset! root (rdom/create-root container)))
    (init-window-size-listener!)
    (init-capacitor-listeners!)

    (.render @root (r/as-element [main-layout]))))

(defn ^:export init []
  (re-frame/dispatch-sync [:initialize-db])
  (re-frame/dispatch [:app/load-settings-by-stage :boot])
  (re-frame/dispatch [:app/start-boot-sequence])
  (mount-root))


(re-frame/reg-event-fx
 :app/start-boot-sequence
 (fn [_ _]
   (-> (load-config)
       (p/then (fn [config]
                 (reset! !config config)
                 (re-frame/dispatch-sync [:app/config-loaded config])
                 (log/info "Config loaded:" config)
                 (load-i18n)))
       (p/then (fn [_]
                 (let [params  (js/URLSearchParams. js/window.location.search)
                       room-id (.get params "room")]
                   (when room-id
                     (log/info "Deep link detected on boot:" room-id)
                     (re-frame/dispatch [:nav/lock-deep-link room-id])
                     (.replaceState js/window.history #js {} "" (.. js/window -location -pathname)))

                   (p/let [saved-user (store/get-setting "last_active_user")]
                     (re-frame/dispatch [:app/bootstrap saved-user]))

                   (notifications/init!)
                   (js/setInterval #(re-frame/dispatch [:app/poll-version false]) (* 1000 60 15)))))
       (p/catch #(log/error "App initialization failed:" %)))
   {}))

(re-frame/reg-event-db
 :nav/lock-deep-link
 (fn [db [_ room-id]]
   (assoc db :deep-link-room room-id)))

(re-frame/reg-event-fx
 :nav/route-from-push
 (fn [{:keys [db]} [_ room-id]]
   (if (= (:auth-status db) :logged-in)
     {:dispatch [:rooms/select room-id]}
     {:dispatch [:nav/lock-deep-link room-id]})))

(re-frame/reg-event-fx
 :app/restore-user-session
 (fn [{:keys [db]} [_ user-id]]
   (let [deep-room (:deep-link-room db)]
     (if deep-room
       {:dispatch-n [[:auth/set-status :logged-in]
                     [:rooms/select deep-room]
                     [:sdk/ignite-session]]}
       (do
         (p/let [[room-id space-id] (p/all [(store/get-setting (str "last_room_" user-id))
                                            (store/get-setting (str "last_space_" user-id))])]
           (if room-id
             (do
               (log/info "Restoring session for" user-id "-> Space:" space-id "| Room:" room-id)
               (when space-id
                 (re-frame/dispatch [:space/select space-id]))
               (re-frame/dispatch [:auth/set-status :logged-in])
               (re-frame/dispatch [:rooms/select room-id])
               (re-frame/dispatch [:sdk/ignite-session]))
             (do
               (re-frame/dispatch [:auth/set-status :logged-in])
               (re-frame/dispatch [:sdk/ignite-session]))))
         {})))))



(defn ^:after-load re-render []
  (mount-root))
#+end_src




