
** The Service Worker


**** Preface

So a web-based matrix client usually follows the pattern of using service workers
to provide long-lived functionality. This includes background behavior when we
say use it even as a native app or a PWA on phones. It is through the service
worker that we can asynchronously fetch images from the server or deliver push notifications.
It is safe to say that the service worker is a very important component to
most web applications, not just web-based Matrix clients.


**** Service Worker


***** Imports

Now workbox-precaching is set up through Vite (but is its own npm package mind you).
This is an elegant way to ensure our caching mechanism is working well.
We do not want the user to download the WASM ever again unless we change it.
#+begin_src clojurescript :tangle ../src/service_worker.cljs
(ns service-worker
  (:require [clojure.string :as str]
            [promesa.core :as p]
            ["workbox-precaching" :refer [precacheAndRoute cleanupOutdatedCaches]]))
#+end_src


***** Message Event

The message event is how the client communicates with the service worker.
It passes 'messages' to the service worker and the service worker passes
'messages' to the client. It is not too dissimilar to postMessage for
communicating with iframes.

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage


****** Workbench cache and constants

Now we go a bit further and store the client-id of the session in-case
later we wish to provide multi-session functionality more implicitly.
This also provides a level of security ensuring we don't accidentally
send data to the wrong client instance. By having the full session on
hand we have the home-server and the token used too.
#+begin_src clojurescript :tangle ../src/service_worker.cljs
(defonce active-sessions (atom {}))
(defonce session-resolvers (atom []))
(def MAX_CACHE_ITEMS 50)
(def cache-name "matrix-media-v1")
(let [manifest (or js/self.__WB_MANIFEST #js [])]
  (precacheAndRoute manifest))
#+end_src


****** Event

#+begin_src clojurescript :tangle ../src/service_worker.cljs
(.addEventListener js/self "message"
                   (fn [event]
                     (let [data      (.-data event)
                           msg-type  (.-type data)
                           source-id (.. event -source -id)]
                       (cond
                         (= msg-type "SKIP_WAITING")
                         (do
                           (js/console.log "SW: Received SKIP_WAITING, taking control...")
                           (.skipWaiting js/self))

                         (= msg-type "SET_SESSION")
                         (let [session-data (:session (js->clj data :keywordize-keys true))
                               full-session (assoc session-data :client-id source-id)]
                           (swap! active-sessions assoc source-id full-session)
                           (js/console.log "SW: Session synced for" source-id)
                           (doseq [resolve-fn @session-resolvers]
                             (resolve-fn true))
                           (reset! session-resolvers []))))))
#+end_src


****** Session waiting

We need to wait until a session is available to start performing fetches.
Without this, the user could end up seeing broken images purely from their
client loading too fast and trying to fetch.
#+begin_src clojurescript :tangle ../src/service_worker.cljs
(defn wait-for-session! []
  (if (not-empty @active-sessions)
    (p/resolved true)
    (js/Promise. (fn [resolve _]
                   (swap! session-resolvers conj resolve)))))
#+end_src


****** Vault Token Retrieval

Now this is great if we want to do simple behavior, but the moment we expect
long-living persistence we might wish to instead check against the IndexedDB
for individual sessions for a user. This way we can actually support
multiple accounts at once reliably for even our notification purposes.

Now the immediate thought is that because the Rust SDK pickles our data at
rest we'd need some way to actually unlock it. So the second part of this
is to create a small entry in our IndexedDB in which we create entries
with the access token.

#+begin_src clojurescript :tangle ../src/service_worker.cljs
(defn- get-token-from-vault [user-id]
  (p/create
   (fn [resolve _]
     (let [req (.open js/indexedDB "sw-vault" 1)]
       (set! (.-onsuccess req)
             (fn [e]
                 (let [db (.. e -target -result)
                       tx (try (.transaction db #js ["tokens"] "readonly") (catch :default _ nil))
                       store (when tx (.objectStore tx "tokens"))
                       get-req (if (and store user-id)
                                 (.get store user-id)
                                 (when store (.getAll store)))]
                   (if-not get-req
                     (resolve nil)
                     (set! (.-onsuccess get-req)
                           (fn [res]
                             (let [result (.. res -target -result)]
                               (if (array? result)
                                 (resolve (some-> (first result) .-token))
                                 (resolve (some-> result .-token))))))))))
       (set! (.-onerror req) #(resolve nil))))))
#+end_src


****** Old cache management


If possible we want to manage the cache and we want to also make sure we don't
cache items that are too old. By caching we provide a level of offline access.

One might wonder about the cache security. It is true that on desktop
the cache is not encrypted by default, but it is however isolated and secure.

The browser ensures this much at least. It would be the expectation of the
user to encrypt their device. The performance impact of encrypting and
decrypting the cache would be noticeable to the performance of the application.
Not to mention entirely impractical as if an attacker has access to the cache then
they also have access to the key to decrypt it.

For mobile users can take solace we can rely on the fact their operating system
encrypt the disk at rest (Full Disk Encryption).

#+begin_src clojurescript :tangle ../src/service_worker.cljs
(defn prune-cache! [name max-items]
  (p/let [cache (js/caches.open name)
          keys  (.keys cache)]
    (when (> (.-length keys) max-items)
      (p/let [_ (.delete cache (first keys))]
        (prune-cache! name max-items)))))
#+end_src


***** Fetch Event

The fetch event is vital for the client to asynchronously 'fetch' images from a
server so that we may allow the client to worry simply on the elements it can
render immediately.

We only want to bother fetching authenticated media with the expected
media endpoints. We validate the URL to ensure we don't leak info unexpectedly.

Some important readings for this:
https://spec.matrix.org/latest/client-server-api/#matrix-content-mxc-uris

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/fetch_event

We also want to utilize a cache so that users don't bother endlessly re-fetching assets on reloads.
We make sure that we split the logic into two branches. Non-authenticated media and authenticated media.
For any other browser fetch we want to simply return it back to the browser to handle.
#+begin_src clojurescript :tangle ../src/service_worker.cljs
(js/self.addEventListener "fetch"
  (fn [event]
    (let [request      (.-request event)
          method       (.-method request)
          request-url  (js/URL. (.-url request))
          path         (.-pathname request-url)
          auth-path?   (str/includes? path "/_matrix/client/v1/media/")
          legacy-path? (or (str/includes? path "/_matrix/media/v3/")
                           (str/includes? path "/_matrix/media/v1/"))]
      (when (= method "GET")
        (cond
          auth-path?
          (.respondWith event
            (p/let [cache  (js/caches.open cache-name)
                    cached (.match cache request)]
              (if cached
                cached
                (p/let [_       (wait-for-session!)
                        session (or (get @active-sessions (.-clientId event))
                                    (first (vals @active-sessions)))
                        token   (or (:accessToken session) (:token session))
                        hs-url  (or (:homeserverUrl session) (:hsUrl session) (:hs_url session))]
                  (if (or (not token)
                          (not hs-url)
                          (not= (.-origin request-url) (.-origin (js/URL. hs-url))))
                    (js/Response.error)
                    (let [headers (js/Headers. (.-headers request))]
                      (.set headers "Authorization" (str "Bearer " token))
                      (p/let [resp (js/fetch request-url #js {:headers headers
                                                              :mode "cors"
                                                              :credentials "omit"})]
                        (when (and (.-ok resp) (< (js/parseInt (.get (.-headers resp) "content-length") 10) 10485760))
                          (.put cache request (.clone resp)))
                        resp)))))))

          legacy-path?
          (.respondWith event
            (p/let [cache  (js/caches.open cache-name)
                    cached (.match cache request)]
              (if cached
                cached
                (p/let [resp (js/fetch request-url #js {:mode "cors"
                                                        :credentials "omit"})]
                  (when (and (.-ok resp) (< (js/parseInt (.get (.-headers resp) "content-length") 10) 10485760))
                    (.put cache request (.clone resp)))
                  resp))))
          :else nil)))))


#+end_src


***** Install Event

The install event is the first event in the lifecycle of a service worker.
Once this goes off the service worker starts to come alive.
#+begin_src clojurescript :tangle ../src/service_worker.cljs
#_(js/self.addEventListener "install"
  (fn [event]
    (.skipWaiting js/self)))
#+end_src


***** Activate Event

So the service worker needs to be 'activated' and then once activated we want to
immediately claim all clients so we can start fetching for them.
This also happens to be the best time to check the cache to ensure we don't allow it
to grow too large.
#+begin_src clojurescript :tangle ../src/service_worker.cljs
(js/self.addEventListener "activate"
  (fn [event]
    (.waitUntil event
      (p/all [(.clients.claim js/self)
              (prune-cache! cache-name MAX_CACHE_ITEMS)]))))
#+end_src





***** Push Notifications

So an important part to the service worker use is providing the web application
a way to receive notifications from the background. The general standard implementation
is WebPush denoted below:
https://developer.mozilla.org/en-US/docs/Web/API/Push_API

Now the implementation for these is relatively standardized (though for Clojurescript
perhaps a bit less so).
We want to simply add the push event listener and then parse the data out.
We handle the requests in the form Sygnal delivers (though I'm unsure if
the form is entirely ubiquitous across any push gateway implementation).
For the sake of these docs currently, I'll be referring to them in the
context of the Matrix solution Sygnal.
https://github.com/element-hq/sygnal/blob/main/docs/applications.md#webpush

We also go on to include a notification click in order to provide the future
behavior on which clicking a notification brings that message into focus.
Currently, however, it won't be functional as we have not implemented a go-to
method for messages yet.

It does seem unfortunately that we have no way to determine the recipient of a push...
Perhaps I'll spend more time on the problem another time, but it is best we get
this functional first.
#+begin_src clojurescript :tangle ../src/service_worker.cljs
(def default-icon "/public/res/apple/apple-touch-icon-180x180.png")
(def default-badge "/public/res/apple/apple-touch-icon-72x72.png")

#_(defn- get-session-from-vault [user-id]
  (p/create
   (fn [resolve reject]
     (let [req (.open js/indexedDB "sw-vault" 1)]
       (set! (.-onsuccess req)
             (fn [e]
               (let [db    (.. e -target -result)
                     tx    (.transaction db #js ["tokens"] "readonly")
                     store (.objectStore tx "tokens")]
                 (if user-id
                   (let [get-req (.get store user-id)]
                     (set! (.-onsuccess get-req) #(resolve (.. % -target -result)))
                     (set! (.-onerror get-req) #(resolve nil)))
                   (let [all-req (.getAll store)]
                     (set! (.-onsuccess all-req)
                           (fn [ae]
                             (let [results (vec (.. ae -target -result))]
                               (if (empty? results)
                                 (resolve nil)
                                 (resolve (->> results
                                               (sort-by #(.-updated_at %) >)
                                               first)))))))))))))))

(defn- get-session-from-opfs [user-id]
  (p/let [dir         (.. js/navigator -storage getDirectory)
          file-handle (p/catch (.getFileHandle dir "mx_session_v3.json") (fn [_] nil))]
    (if-not file-handle
      nil
      (p/let [file     (.getFile file-handle)
              text     (.text file)
              sessions (try (.parse js/JSON text) (catch :default _ #js {}))
              keys     (js/Object.keys sessions)
              target-id (or user-id (when (pos? (.-length keys)) (aget keys 0)))]

        (if target-id
          (let [data (aget sessions target-id)]
            (if data
              (let [session (aget data "session")]
                #js {:token  (aget session "accessToken")
                     :hs_url (aget session "homeserverUrl")})
              nil))
          nil)))))

(defn- fetch-avatar-url [hs-url token mxc-uri]
  (if (and hs-url token mxc-uri)
    (let [media-id (clojure.string/replace mxc-uri "mxc://" "")
          thumb-url (str hs-url "/_matrix/media/v3/thumbnail/" media-id
                         "?width=96&height=96&method=crop")]
      (-> (js/fetch thumb-url #js {:headers #js {:Authorization (str "Bearer " token)}
                                   :mode "cors"
                                   :credentials "omit"})
          (p/then (fn [resp]
                    (if (.-ok resp)
                      (p/let [blob (.blob resp)]
                        (js/URL.createObjectURL blob))
                      nil)))
          (p/catch (fn [_] nil))))
    (p/resolved nil)))

(defn- fetch-event-content [hs-url token room-id event-id]
  (let [url (str hs-url "/_matrix/client/v3/rooms/" (js/encodeURIComponent room-id)
                 "/context/" (js/encodeURIComponent event-id) "?limit=0")]
    (-> (js/fetch url #js {:headers #js {:Authorization (str "Bearer " token)}
                           :mode "cors"
                           :credentials "omit"})
        (p/then (fn [resp]
                  (if (.-ok resp)
                    (.json resp)
                    (throw (js/Error. "Failed to fetch event context")))))
        (p/then (fn [json]
                  (let [event (.-event json)]
                    {:body (get-in (js->clj event) ["content" "body"])
                     :sender (or (.-sender event) "Someone")}))))))

(defn- show-smart-notification [push-data token hs-url]
  (let [sender        (or (.-sender_display_name push-data) (.-sender push-data) "Someone")
        room-name     (.-room_name push-data)
        room-id       (.-room_id push-data)
        unread-count  (.-unread push-data)
        encrypted?    (= (.-type push-data) "m.room.encrypted")
        avatar-mxc    (or (some-> push-data .-content .-avatar_url)
                          (some-> push-data .-sender_avatar_url))
        body          (if encrypted?
                        "🔒 Encrypted Message"
                        (or (some-> push-data .-content .-body) "New Message"))
        title         (if room-name (str sender " in " room-name) sender)]

    (when (exists? js/navigator.setAppBadge)
      (if (and unread-count (pos? unread-count))
        (.setAppBadge js/navigator unread-count)
        (when (= unread-count 0)
          (.clearAppBadge js/navigator))))

    (p/let [;icon-url (fetch-avatar-url hs-url token avatar-mxc)
            ]
      (.showNotification js/self.registration title
        #js {:body   body
             :icon   (or icon-url default-icon)
             :badge  default-badge
             :tag    (or room-id "matrix-chat")
             :data   #js {:room_id room-id}}))))


#+end_src


***** Push Event

#+begin_src clojurescript :tangle ../src/service_worker.cljs
(js/self.addEventListener "push"
  (fn [event]
    (log/error "Fake error")
    (let [data (try (.. event -data json) (catch :default _ nil))]
      (when data
        (let [user-id (.-user_id data)]
          (.waitUntil event
            (p/let [session (get-session-from-opfs user-id)
                    token   (some-> session .-token)
                    hs-url  (some-> session .-hs_url)]
              (show-smart-notification data token hs-url))))))))
#+end_src


***** Notification Click Event

#+begin_src clojurescript :tangle ../src/service_worker.cljs
(js/self.addEventListener "notificationclick"
  (fn [event]
    (let [notification (.-notification event)
          room-id      (.. notification -data -room_id)]
      (.close notification)

      (.waitUntil event
        (p/let [clients (.matchAll js/self.clients #js {:type "window" :includeUncontrolled true})
                tab (first clients)]
          (if tab
            (do
              (.focus tab)
              (.postMessage tab #js {:type "NAVIGATE_TO_ROOM"
                                     :room_id room-id}))
            (.openWindow js/self.clients "/")))))))




;; Bloop




#+end_src


***** Shadow-CLJS Nuance

Shadow-cljs seems to be a bit opinionated in how it generates the service worker file.
That and the documentation for web-workers isn't amazingly clear, nonetheless it does
provide enough info continue anyway.
https://shadow-cljs.github.io/docs/UsersGuide.html#_web_workers
/In fact the documentation here states it'd generate a file named worker.js yet, we're getting a
sw.js/

Not a large issue, but one I felt needed to be clarified to avoid potential confusion.


**** Service Worker Handler

Now below we have our actual service worker handler. This is where we'll define any service worker
logic that is to be used from the main application itself.


***** Imports

#+begin_src clojurescript :tangle ../src/service_worker_handler.cljs
(ns service-worker-handler
  (:require
   [taoensso.timbre :as log]
   [client.config :refer [check-remote-version]]
   [re-frame.db :as db]
   [promesa.core :as p]
   [re-frame.core :as re-frame]
   [cljs-workers.core :as main]
   [client.state :as state]
   [cljs.core.async :refer [go <!]]))
#+end_src


***** Deleting Old Caches

#+begin_src clojurescript :tangle ../src/service_worker_handler.cljs
(re-frame/reg-event-fx
 :app/clear-cache-for-update
 (fn [_ _]
   (log/warn "Purging all caches and service workers...")
   (p/let [cache-keys (js/caches.keys)
           _ (p/all (map #(js/caches.delete %) cache-keys))
           regs (.getRegistrations js/navigator.serviceWorker)
           _ (p/all (map #(.unregister %) regs))]
          (.reload js/window.location true))
   {}))
#+end_src


***** Registering the Service Worker

The major functionality we need is to register the service worker itself.
We do so while passing off the session token so that the service worker
may immediately begin to render our images.
#+begin_src clojurescript :tangle ../src/service_worker_handler.cljs
(defn register-sw! []
  (when (exists? js/navigator.serviceWorker)
    (let [sw-container js/navigator.serviceWorker
          try-sync!    (fn []
                         (when (.-controller sw-container)
                           (re-frame/dispatch [:auth/sync-sw-with-worker])))]

      (-> (.register sw-container "/sw.js" #js {:type "module"})
          (.then (fn [reg]
                   (when (.-waiting reg)
                     (.postMessage (.-waiting reg) #js {:type "SKIP_WAITING"})))))
      (try-sync!)
      (.addEventListener sw-container "controllerchange"
                         (fn []
                           (log/debug "re-frame: SW Controller changed, checking version...")
                           (try-sync!)
                           (-> (check-remote-version)
                               (p/then (fn [remote-v]
                                         (let [db @db/app-db
                                               current-v (get-in db [:config :version] "0.0.0")]
                                           (when (and remote-v
                                                      (not= (str remote-v) (str current-v))
                                                      (not= (str current-v) "0.0.0"))
                                             (log/info "SW Update: Version mismatch detected" remote-v "vs" current-v)
                                             (re-frame/dispatch [:app/clear-cache-for-update])))))
                               (p/catch (fn [err]
                                          (log/error "SW Update: Failed to check version" err))))))
      (.addEventListener sw-container "message"
                         (fn [event]
                           (let [data (.-data event)]
                             (when (= (.-type data) "NAVIGATE_TO_ROOM")
                               (let [room-id (.-room_id data)]
                                 (log/debug "SW requested navigation to room:" room-id)
                                 (re-frame/dispatch [:rooms/select room-id])))))))))

#+end_src


***** Syncing to the Service Worker with Reframe

Now, since we're using reframe we want to ensure we're providing our rendering
implementation an easy way to inform updates to the service worker.
We may wish to break this apart a bit for re-usability, but for now this will do.
#+begin_src clojurescript :tangle ../src/service_worker_handler.cljs
(re-frame/reg-event-fx
 :auth/sync-sw-with-worker
 (fn [{:keys [db]} _]
   (if-let [pool @state/!engine-pool]
     (go
       (let [res (<! (main/do-with-pool! pool {:handler :get-client-context}))]
         (when (= (:status res) "success")
           (re-frame/dispatch [:auth/sync-sw-only (:session res)]))))
     (log/warn "Engine pool not ready for SW sync"))
   {}))

(re-frame/reg-event-fx
 :auth/sync-sw-only
 (fn [_ [_ session]]
   {:sync-sw-auth session}))

(re-frame/reg-fx
 :sync-sw-auth
 (fn [session]
   (if-let [sw-controller (.-controller js/navigator.serviceWorker)]
     (try
       (let [origin (.-origin (js/URL. (:homeserverUrl session)))
             payload (assoc session :origin origin)]
         (.postMessage sw-controller #js {:type "SET_SESSION"
                                          :session (clj->js payload)})
         (js/console.log "re-frame: Session synced for" (:userId session) "at" origin))
       (catch js/Error e
         (js/console.error "re-frame: Failed to parse homeserver URL" e)))
     (js/console.warn "re-frame: SW controller not found"))))
#+end_src


