
** Worker

**** Preface

As we've built this out it becomes apparent there would be a tangible gain to separating
the behavior that is ONLY rust-sdk operations from the UI code.
This would allow our start-up to feel much more instantaneous and incredibly more responsive.

As far as documentation goes, some of it will be ported from the prior implementations location
if applicable.

**** Imports

#+begin_src clojurescript :tangle ../src/worker/core.cljs
(ns worker.core
  (:require
   [cljs-workers.worker :as worker]
   [promesa.core :as p]
   [taoensso.timbre :as log]
   [clojure.string :as str]
   [client.session-store :refer [SessionStore]]
   ["ffi-bindings" :as sdk]
   [cljs.core.async.interop :refer-macros [<p!]]
   [cljs.core.async :refer [go]]
   [worker.state :as state]
   [worker.spaces :as spaces]
   [worker.timeline]
   [worker.members]
   [worker.composer]
   [worker.call]
   [worker.rooms :as rooms]))
#+end_src



**** Web Worker Examples

The mechanisms we use for the web worker are relatively straightforward
once you see how they are used. It's effectively a bunch of RPCs between
the main thread and the web worker. The web worker we want to handle
all rust-sdk interaction. This creates a nice segmented design between
the Rust SDK operations and the actual UI. It also provides a guide
for creating future multi-threaded operations for the client.

At some point I would like to revise the cljs-workers library, but
for now it is plenty sufficient for what we need. That said, it isn't
actually super complex as it is just a wrapper for common web worker
operations.

#+begin_src clojurescript

#+end_src


#+begin_src clojurescript

#+end_src





**** Initialize the Wasm


So the first thing we need to do is actually initialize the
WASM.


#+begin_src clojurescript :tangle ../src/worker.cljs
(worker/register :init-wasm
                 (fn [_]
                   (go
                     (try
                       (<p! (sdk/uniffiInitAsync))
                       {:status :success}
                       (catch :default e
                         {:status :error :msg (str e)})))))
#+end_src





**** Starting the Client

This is more or less where we start our journey of actually interfacing with the
matrix-rust-sdk WASM bindings. Since the client initialization is relatively 'easy'
compared to actually making use of the information and state internally.

It seems that WASM needs camelCase after it is converted from Rust.
So entries_handle becomes entriesStream

We started with view models but eventually moved towards more Clojure native
implementations that align better with reframe to make writing more idiomatic.
As such it becomes much simpler to initialize and manage the state.
Though this does mean we'll retroactively need to add methods to do certain
behaviors against the Rust sdk.

This is a good spot to explore what the Rust FFI exposes to use in the client as well.
Such as the space_service is useful to avoid manaul calculation of the spaces vs rooms.
Well. So we thought anyway. It appears to not be as innately useful as initially thought.
