** Room List


**** Preface


**** Imports

#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(ns navigation.rooms.room-list
  (:require
   [re-frame.core :as re-frame]
   [taoensso.timbre :as log]
   [cljs-workers.core :as main]
   [client.state :as state]
   [client.session-store :as store]
   ["react-virtuoso" :refer [Virtuoso]]
   [navigation.rooms.entry :refer [render-room-item active-call-panel]]
   [cljs.core.async :refer [go <!]]))
#+end_src



**** Syncing


#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(re-frame/reg-event-db
 :rooms/parent-resolved
 (fn [db _]
   (update-in db [:ui :parent-refresh-counter] (fnil inc 0))))

(re-frame/reg-event-db
 :room-list/set-home-rooms-sync
 (fn [db [_ rooms]]
   (assoc db :rooms rooms)))

(re-frame/reg-event-db
 :room-list/set-bg-rooms-sync
 (fn [db [_ rooms-list]]
   (let [rooms-map (reduce (fn [acc r]
                             (let [id (or (:id r) (:roomId r))]
                               (if id
                                 (assoc acc id r)
                                 acc)))
                           {} rooms-list)]
     (assoc db :rooms-unfiltered-cache rooms-map))))
#+end_src



**** Space Tree Flattening

This is just a simple filter method to deduplicate
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(defn distinct-by [f coll]
  (let [!seen (atom #{})]
    (filterv (fn [x]
               (let [k (f x)]
                 (if (contains? @!seen k)
                   false
                   (do (swap! !seen conj k)
                       true))))
             coll)))

(defn safe-get [obj k-str k-kw]
  (if (map? obj)
    (get obj k-kw)
    (let [v (aget obj k-str)]
      (if (undefined? v)
        (aget obj (name k-kw))
        v))))


#+end_src


This provides a method to take the room map and turn it into a usable structure
to actually visualize our room lists. I'll come back and add more to this when
I add the call room previewing.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs




(defn flatten-tree [rooms-map children-map space-orders closed-drawers parent-id depth]
  (let [sdk-children    (get children-map parent-id [])
        manual-children (->> (vals rooms-map)
                             (filter #(= (safe-get % "first-parent-id" :first-parent-id) parent-id))
                             (map (fn [r] {:id         (or (safe-get r "id" :id) (safe-get r "roomId" :roomId))
                                           :is-space?  (safe-get r "isSpace" :isSpace)})))

        orders-for-parent (get space-orders parent-id {})

        child-refs      (->> (concat sdk-children manual-children)
                             (distinct-by :id)
                             (sort-by #(get orders-for-parent (:id %) "zzzz"))
                             (vec))]
    (reduce
     (fn [acc {:keys [id is-space?]}]
       (let [summary       (get rooms-map id)
             item          {:id                         id
                            :is-space?                  is-space?
                            :depth                      depth
                            :activeRoomCallParticipants (when summary (safe-get summary "activeRoomCallParticipants" :activeRoomCallParticipants))
                            :name                       (if summary (or (safe-get summary "name" :name) "Loading...") "Loading...")
                            :avatar                     (when summary (safe-get summary "avatar" :avatar))
                            :unreadNotificationsCount   (if summary (or (safe-get summary "unreadNotificationsCount" :unreadNotificationsCount) 0) 0)
                            :unreadMentionsCount        (if summary (or (safe-get summary "unreadMentionsCount" :unreadMentionsCount) 0) 0)}
             acc-with-item (conj acc item)]

         (if (and is-space? (not (contains? closed-drawers id)))
           (into acc-with-item (flatten-tree rooms-map children-map space-orders closed-drawers id (inc depth)))
           acc-with-item)))
     []
     child-refs)))




#+end_src


**** Room Global Reframe Components

There are our reframe pieces. I'll go into detail on each of them later on. For now this
is effectively a functioning *stub*.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(re-frame/reg-sub :rooms/active-id (fn [db _] (:active-room-id db)))
(re-frame/reg-sub :space-rooms (fn [db _] (vec (or (:space-rooms db) []))))
(re-frame/reg-sub :rooms/all (fn [db _] (let [rooms (:rooms db)] (if (map? rooms) (vec (vals rooms)) (vec (or rooms []))))))


(re-frame/reg-sub
 :rooms/active-metadata
 :<- [:rooms/active-id]
 :<- [:rooms/unfiltered-indexed-map]
 (fn [[active-id rooms-map] _]
   (when active-id (get rooms-map active-id))))


(re-frame/reg-event-fx
 :room-list/paginate-global
 (fn [_ _]
   (main/do-with-pool! @state/!engine-pool {:handler :paginate-room-list})
   {}))

(re-frame/reg-event-db
 :rooms/set-preview
 (fn [db [_ room-id preview-data]]
   (assoc-in db [:room-previews room-id] preview-data)))

(re-frame/reg-sub
 :rooms/preview
 (fn [db [_ room-id]]
   (get-in db [:room-previews room-id])))



#+end_src


**** Room Reframe Subscriptions

Important to note that the Rust sdk delivers the resulting rooms in order
of recent activity. So if we use a broad stroke to handle all of them we lose
this valuable data. Instead we want to provide a simple 'parsed' map for
the DMs list or All rooms list as these are best served fresh first.
For the space rooms themselves we want to flatten as we have described
above.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs

(re-frame/reg-sub :rooms/unfiltered-indexed-map (fn [db _] (get db :rooms-unfiltered-cache {})))



(re-frame/reg-sub :rooms/ordered-list (fn [db _] (get db :rooms [])))


(re-frame/reg-sub :rooms/space-orders (fn [db _] (get db :space-orders {})))

(re-frame/reg-sub
 :rooms/indexed-map
 :<- [:rooms/all]
 (fn [rooms-list _]
   (reduce (fn [acc room]
             (let [id (or (:id room) (:roomId room))]
               (if id
                 (assoc acc id room)
                 acc)))
           {} rooms-list)))

(re-frame/reg-event-db
 :rooms/apply-parent-resolution
 (fn [db [_ room-id first-parent-id]]
   (-> db
       (assoc-in [:rooms-unfiltered-cache room-id :first-parent-id] first-parent-id)
       (update :rooms (fn [rooms]
                        (if (sequential? rooms)
                          (mapv (fn [r]
                                  (if (= (:id r) room-id)
                                    (assoc r :first-parent-id first-parent-id)
                                    r))
                                rooms)
                          rooms))))))

(re-frame/reg-sub
 :rooms/current-view
 :<- [:spaces/active-id]
 :<- [:rooms/ordered-list]
 :<- [:rooms/unfiltered-indexed-map]
 :<- [:space-children/map]
 :<- [:rooms/space-orders]
 :<- [:rooms/closed-drawers]
 (fn [[active-id ordered-list indexed-map children-map space-orders closed-drawers] _]
   (if-not active-id
     ordered-list
     (flatten-tree indexed-map children-map space-orders closed-drawers active-id 0))))



#+end_src


**** Reframe Drawers


***** CSS

#+begin_src css :tangle ../../../css/room-list.css
.room-drawer-header {
    display: flex;
    align-items: center;
    padding: 18px 8px 4px 10px;
    font-size: 12px;
    font-weight: 700;
    color: #8e9297;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    cursor: pointer;
    user-select: none;
    transition: color 0.1s ease-in-out;
}

.room-drawer-header:hover {
    color: #ffffff;
}

.drawer-arrow {
    display: inline-block;
    width: 12px;
    height: 12px;
    line-height: 12px;
    margin-right: 4px;
    font-size: 8px;
    transition: transform 0.2s cubic-bezier(0.4, 0, 0.2, 1);
    color: #6a6d71;
}

.room-drawer-header.collapsed .drawer-arrow {
    transform: rotate(-90deg);
}
#+end_src


***** Reframe components

#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(re-frame/reg-event-db
 :rooms/toggle-drawer
 (fn [db [_ drawer-id]]
   (update-in db [:ui :closed-drawers]
              (fn [closed]
                (if (contains? closed drawer-id) (disj closed drawer-id) (conj (or closed #{}) drawer-id))))))

(re-frame/reg-sub :rooms/closed-drawers (fn [db _] (get-in db [:ui :closed-drawers] #{})))
#+end_src


**** Notifications and unread data

So notification handling is actually a fairly annoying process if we want the
smooth visual users expect. We need to bubble up the unread count for every
room within a space. This meant we needed to have the parent-child relationships
mapped out and then flatten them into a calculatable total.
The parent-child mapping process is documented above, but amusingly is
one of the more complex aspects of spaces and rooms.

To a much easier degree, we need to also calculate the unread count for DMs.
This is mostly useful for presenting that info on the space bar cleanly.
Otherwise we would just re-use (and probably should see if we can)
the method we have for all other rooms.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(re-frame/reg-sub
 :space/unread-stats
 :<- [:rooms/unfiltered-indexed-map]
 :<- [:space-children/map]
 :<- [:rooms/space-orders]
 (fn [[rooms-map children-map space-orders] [_ space-id]]
   (let [rooms-in-space (flatten-tree rooms-map children-map space-orders #{} space-id 0)
         stats (reduce (fn [acc room]
                         (-> acc
                             (update :notifs + (get room :unreadNotificationsCount 0))
                             (update :mentions + (get room :unreadMentionsCount 0))))
                       {:notifs 0 :mentions 0} rooms-in-space)]
     {:unread? (pos? (:notifs stats))
      :notif-count (:notifs stats)
      :mentions (:mentions stats)
      :highlight? (pos? (:mentions stats))})))


(re-frame/reg-sub
 :rooms/active-dm-pops
 :<- [:rooms/unfiltered-indexed-map]
 (fn [rooms-map _]
   (->> (vals rooms-map)
        (keep (fn [raw-room]
                (let [r           (if (map? raw-room) raw-room (js->clj raw-room :keywordize-keys true))
                      is-dm?      (or (:is-direct? r) (:isDirect r) (:is-direct r))
                      msg-count   (or (:unread-messages-count r) (:unreadMessagesCount r) 0)
                      mentions    (or (:highlight-count r) (:unreadMentionsCount r) 0)
                      ts          (or (:last_message_ts r) (:lastMessageTs r) 0)]
                  (when (and is-dm? (pos? msg-count))
                    {:id          (or (:id r) (:roomId r))
                     :name        (or (:name r) "Loading...")
                     :avatar-url  (or (:avatar r) (:avatarUrl r))
                     :is-dm?      true
                     :unread?     true
                     :highlight?  (pos? mentions)
                     :mentions    mentions
                     :msg-count   msg-count
                     :ts          ts}))))
        (sort-by :ts >)
        (map #(dissoc % :ts)))))

#+end_src




**** Room Selection

Selection is likely the biggest component of rooms as far as users are concerned.
This mechanism actually has to fulfill a few roles such as correctly entering
the correct state for calling or opening the correct panels given the current
view state.

****** TODO Fix the actual swap impl.
Stopped and just stubbed it in for now while I go back and clean up the CSS
and file structures.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(defn- is-call-room? [db room-id]
  (get-in db [:room-previews room-id :is-call?] false))

(re-frame/reg-event-fx
 :rooms/hydrate-room
     (fn [{:keys [db]} [_ room-id]]
      (if (:push-routed? db)
          {}
       {:dispatch [:rooms/select room-id]})))

(re-frame/reg-event-fx
 :rooms/select
 (fn [{:keys [db]} [_ room-id opts]]
   (let [current-room-id (:active-room-id db)
         current-user    (:active-user-id db)]
     (store/set-setting! (str "last_room_" current-user) room-id)

     (if (= current-room-id room-id)
       {:db (assoc-in db [:ui :sidebar-open?] false)}
       {:db         (assoc db :active-room-id nil)
        :dispatch-n [(when current-room-id [:sdk/cleanup-timeline current-room-id])]
        :dispatch-later [{:ms 20 :dispatch [:rooms/finish-select room-id opts]}]}))))


(re-frame/reg-event-fx
 :rooms/finish-select
 (fn [{:keys [db]} [_ room-id opts]]
   (let [active-call-id     (get-in db [:call :active-room-id])
         already-loaded?    (get-in db [:room-members room-id :data])
         loading?           (get-in db [:room-members room-id :loading?])
         is-call-room?      (is-call-room? db room-id)

         force-lobby?       (:force-lobby? opts)
         focus-override     (:focus-override opts)
         mobile?            (get-in db [:ui :mobile?])
         join-directly?     (if force-lobby? false (not mobile?))
         wipe-call-state?   (not is-call-room?)
         swapping-calls?    (and active-call-id (not= active-call-id room-id) is-call-room?)
         current-side-panel (get-in db [:ui :side-panel])
         side-panel-update  (if (and (= current-side-panel :timeline) (not focus-override)) nil current-side-panel)
         new-focus (if is-call-room? :call :timeline)
         base-db   (-> db
                       (assoc :active-room-id room-id)
                       (assoc-in [:ui :sidebar-open?] false)
                       (assoc-in [:ui :main-focus] new-focus))
         dispatches (remove nil?
                            [(when swapping-calls? [:call/hangup {:wipe-state? wipe-call-state?}])
                             [:sdk/boot-timeline room-id]
                             (when (not (or already-loaded? loading?)) [:room/fetch-members room-id])
                             [:sdk/fetch-room-emotes :room room-id]
                             [:composer/load-draft room-id]
                             [:container/set-main-focus new-focus]
                             (when focus-override [:container/set-side-panel focus-override])
                             (when (and (= current-side-panel :timeline) (nil? side-panel-update)) [:container/set-side-panel nil])
                             (when is-call-room? [:call/init-widget room-id {:join-directly? join-directly?}])])]
     {:db                 base-db
      :input/focus-composer (not mobile?)
      :dispatch-n         dispatches})))

#+end_src



**** Filter Selection

While setting filters isn't the most resource friendly implementation
for now it is an easy and clean way to provide a sorted list to the
user. We'll have to see how it scales as I suspect it is causing the
entire room list to reload. Hopefully not.

***** Component

#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(defn filter-toggle-bar []
  (let [tr            @(re-frame/subscribe [:i18n/tr])
        active-filter @(re-frame/subscribe [:room-list/active-filter])]
    [:div.filter-bar
     (for [[id label-key] [["people" :navigation.room-list.filters/people]
                           ["unread" :navigation.room-list.filters/unread]
                           ["other"    :navigation.room-list.filters/all] ]]
       ^{:key id}
       [:button.filter-btn
        {:class    (when (= active-filter id) "active")
         :on-click #(re-frame/dispatch [:room-list/apply-filter id])}
        (tr [label-key])])]))



;; just dropping here for now

(re-frame/reg-event-fx
 :room-list/apply-filter
 (fn [{:keys [db]} [_ filter-id]]
   (let [current-filter (:active-filter-id db)]
     (if (= current-filter filter-id)
       {}
       (do
         (log/debug "Swapping filter to" filter-id)
         (go
           (let [pool @state/!engine-pool
                 res  (<! (main/do-with-pool! pool {:handler :set-room-filter
                                                    :arguments {:filter-id filter-id}}))]
             (if (= (:status res) "success")
               (log/debug "Worker successfully swapped filter!")
               (log/error "Worker failed to swap filter:" res))))
         {:db (assoc db :active-filter-id filter-id)})))))

(re-frame/reg-sub :room-list/active-filter (fn [db _] (get db :active-filter-id "people")))
#+end_src

***** CSS

Now the CSS for the filter is relatively simple
#+begin_src css :tangle ../../../css/room-list.css
.filter-bar {
    display: flex;
    gap: 8px;
    padding: 10px;
    background-color: #2b2d31;
    border-bottom: 1px solid #1e1f22;
    overflow-x: auto;
    scrollbar-width: none;
}

.filter-bar::-webkit-scrollbar {
    display: none;
}

.filter-btn {
    background: transparent;
    color: #949ba4;
    border: 1px solid transparent;
    border-radius: 16px;
    cursor: pointer;
    padding: 4px 12px;
    font-size: 13px;
    font-weight: 500;
    white-space: nowrap;
    transition: all 0.15s ease-in-out;
}

.filter-btn:hover {
    background-color: #35373c;
    color: #dbdee1;
}

.filter-btn.active {
    background-color: #404249;
    color: #ffffff;
    border-color: transparent;
}
#+end_src


**** Virtuoso for Room List

Our virtualized room list. We ensure our rooms are in an array form
for consumption by Virtuoso and then instruct Virtuoso to ask
reframe for the next "page" upon reaching the end of its display.
We assign the data to be represented as the room array itself.
Now, we can also add nifty behavior for the content itself by then
checking for the "kind" of room. For now though, this is plenty sufficient.

#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(defn virtualized-room-list [tr client room-array active-space active-room closed-drawers active-filter]
  (let [item-renderer (render-room-item tr client room-array active-space active-room closed-drawers active-filter)]
    [:> Virtuoso
     {:style {:height "100%" :width "100%"}
      :data room-array
      :endReached #(re-frame/dispatch [:room-list/paginate-global])
      :itemContent item-renderer}]))
#+end_src






**** Room List Component



Now for the CSS
#+begin_src css :tangle ../../../css/room-list.css
.sidebar-rooms {
    width: 240px;
    flex-shrink: 1;
    background-color: #2b2d31;
    display: flex;
    flex-direction: column;
    padding: 12px;
}

@media (max-width: 768px) {
    .sidebar-rooms {
        width: calc(100vw - 72px);
        max-width: 240px;
      }
}


.room-layout {
    flex: 1;
    height: 100vh;
    display: grid;
    overflow: hidden;
}

.room-collection {
    flex: 1;
    min-height: 0;
}

.room-header {
    display: flex;
    align-items: center;
    padding: 0 16px;
    height: 48px;
    border-bottom: 1px solid #1e1f22;
    background: #313338;
    min-width: 0;
}

.filter-bar::-webkit-scrollbar {
    display: none;
}

.filter-btn:hover {
    background-color: #35373c;
    color: #dbdee1;
}


.room-name {
    font-weight: 600;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    flex: 0 1 auto;
}

#+end_src


Now for our room list component itself, we have three subscriptions requested from reframe
We want to make sure the component updates if our rooms change, our active space changes,
or our active room changes. We then add some decorating Hiccup around it to round out the
component.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(defn room-list []
  (let [tr              @(re-frame/subscribe [:i18n/tr])
        rooms           @(re-frame/subscribe [:rooms/current-view])
        active-room     @(re-frame/subscribe [:rooms/active-id])
        active-space    @(re-frame/subscribe [:spaces/active-metadata])
        closed-drawers  @(re-frame/subscribe [:rooms/closed-drawers])
        active-filter   @(re-frame/subscribe [:room-list/active-filter])
        client          nil
        room-array      (to-array rooms)]
    [:div.sidebar-rooms
     [:div.room-list-header
      (if active-space
        [:h3.room-list-header (:name active-space)]
        [:h3.room-list-header (tr [:navigation.room-list.headers/home])])]
     (when-not active-space
       [filter-toggle-bar])
     (if (or (nil? room-array) (== (alength room-array) 0))
       [:div.empty-state (tr [:navigation.room-list.empty-state/no-rooms])]
       [:div.room-collection
        [virtualized-room-list tr client room-array active-space active-room closed-drawers active-filter]])
     [active-call-panel]]))

#+end_src



**** CSS (Needs testing)


#+begin_src css :tangle ../../../css/room-list.css
.room-drawer-header {
    display: flex;
    align-items: center;
    padding: 18px 8px 4px 10px;
    font-size: 12px;
    font-weight: 700;
    color: #8e9297;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    cursor: pointer;
    user-select: none;
    transition: color 0.1s ease-in-out;
}

.room-drawer-header:hover {
    color: #ffffff;
}

.drawer-arrow {
    display: inline-block;
    width: 12px;
    height: 12px;
    line-height: 12px;
    margin-right: 4px;
    font-size: 8px;
    transition: transform 0.2s cubic-bezier(0.4, 0, 0.2, 1);
    color: #6a6d71;
}

.room-drawer-header.collapsed .drawer-arrow {
    transform: rotate(-90deg);
}


.room-list-header {
    display: flex;
    align-items: center;
    height: 48px;
    justify-content: center;
    min-width: 0;
}

.sidebar-rooms {
    width: 240px;
    flex-shrink: 0;
    background-color: #2b2d31;
    display: flex;
    flex-direction: column;
    padding: 12px;
}


@media (max-width: 768px) {
    .sidebar-rooms {
        width: calc(100vw - 72px);
        max-width: 240px;
    }
}


.room-layout {
    flex: 1;
    height: 100vh;
    display: grid;
    overflow: hidden;
}
.room-name {
    font-weight: 600;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    flex: 0 1 auto;
}


#+end_src
