** Room List


**** Imports

#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(ns navigation.rooms.room-list
  (:require
   [promesa.core :as p]
   [re-frame.core :as re-frame]
   [taoensso.timbre :as log]
   [re-frame.db :as db]
   ["react-virtuoso" :refer [Virtuoso]]
   [navigation.rooms.room-summary :refer [build-room-summary]]
   [navigation.rooms.entry :refer [build-room-actions render-room-item active-call-panel room-type-call?]]
   [client.diff-handler :refer [apply-matrix-diffs]]
   ["ffi-bindings" :as sdk :refer [RoomListEntriesDynamicFilterKind RoomListFilterCategory]]))
#+end_src


**** Parent Child Mapping Space Rooms

We need to create a queuing mechanism to properly load in the parentage for rooms.
If we do this correctly then we can build out the graph ourselves for determining
what a Space structure is. Currently we're using the assumption that the first
parent is the direct expected parent, but at some point we may want to try
to support more dynamic behavior.

Now we do this because when the Rust SDK starts, the SpaceService is still waiting
for the RoomListService to fully populate before it tries to make a DAG of the
Spaces. Even when it makes the DAG we can't really directly interact with it, so
instead we use the fact it exposes the parentage through a method named
joinedParentsOfChild. This is our key to building this 'tree' out.

Because we need the tree to calculate things from Space room list display
to calculating the notification total in the spaces, we do need to ensure
this works... and works well. So we build out our list and then pass it to our
queue here which periodically retries to populate the parentage for the given room.
After a number of fails we just simply determine that the room is an orphan and
remove it from the queue as well.

#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(re-frame/reg-event-db
 :rooms/parent-resolved
 (fn [db _]
   (update-in db [:ui :parent-refresh-counter] (fnil inc 0))))

(defonce !parent-queue (atom {}))

(defn enqueue-parent-check! [room-id]
  (swap! !parent-queue update room-id #(if % % 0)))

(defn process-parent-queue! []
  (let [queue         @!parent-queue
        db            @re-frame.db/app-db
        space-service (:space-service db)
        cache         (get db :rooms-unfiltered-cache {})]
    (when (and space-service (seq queue))
      (-> (p/all
           (map (fn [[id attempts]]
                  (if-let [room (get cache id)]
                    (-> (.joinedParentsOfChild space-service id)
                        (p/then (fn [parents]
                                  (if (pos? (alength parents))
                                    {:id id :status :success :parents parents :room room}
                                    {:id id :status :retry :attempts (inc attempts)})))
                        (p/catch (fn [e]
                                   (js/console.error "Queue FFI fail for" id e)
                                   {:id id :status :retry :attempts (inc attempts)})))
                    (p/resolved {:id id :status :drop})))
                queue))

          (p/then (fn [results]
                    (doseq [res results]
                      (when (= (:status res) :success)
                        (let [room (:room res)
                              parents (:parents res)]
                          (aset room "parents" parents)
                          (aset room "first-parent-id" (.-roomId (aget parents 0))))))

                    (let [to-keep (reduce (fn [acc res]
                                            (if (and (= (:status res) :retry)
                                                     (< (:attempts res) 3))
                                              (assoc acc (:id res) (:attempts res))
                                              acc))
                                          {}
                                          results)]
                      (reset! !parent-queue to-keep)

                      (when (some #(= (:status %) :success) results)
                        (re-frame/dispatch [:rooms/parent-resolved]))

                      (when (seq to-keep)
                        (js/setTimeout process-parent-queue! 2000)))))))))
#+end_src




**** Parsing Rust Room Objects

Parse the room into a useful CLJS form. Otherwise we have to work with
a JS room which isn't ideal. We could try being a bit more consistent
on this stipulation... but it isn't entirely essential now.

Unsettlingly, we use the space-service to determine the parentage
as we can't appropriately populate the SpaceRoomList.

Adding to this we also generate a room preview right here as it
makes more sense to do so during the room parsing. Odds are
in future versions we can more easily grab the room type, but
this is convenient enough... I guess... for now.

It is important to note we are leaving this as an unfulfilled promise.
If we tried to fulfill them all right here we add a potentially
significant delay that the user doesn't really care about. Instead
we can resolve that promise whenever we actually want to interact with
data associated with the RoomPreview. Otherwise it shouldn't matter.

#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(defn parse-room [client space-service room-interface]
  (p/let [room-info     (if (fn? (.-roomInfo room-interface)) (.roomInfo room-interface) nil)
          latest-event  (.latestEvent room-interface)
          room-id       (.-id room-info)

          ]

    (let [summary (build-room-summary room-interface room-info latest-event)
          room-preview  (when (and client (exists? (.-getRoomPreviewFromRoomId client)))
                          (try
                            (p/promise (.getRoomPreviewFromRoomId client room-id #js []))
                          (catch :default e
                            (js/console.error "FFI Call Failed for:" room-id e))))]
      (aset summary "raw-room" room-interface)
      (aset summary "room-preview" room-preview)
      summary)))
#+end_src



**** Removed Block

This is a bit of a band-aid to allow resolving those Room Previews before the user
has to interact with them. Ideally this shouldn't be needed just to determine the
room type, but there is not a built-in method that works (the space room list
in theory should be able to do this, but I've written on this in the Spaces section).
# this was a room preview loader


**** Fetch Space Hierarchy

Bit of an issue in the version of the sdk, but since we do need some state
events (as the sdk lacks a coherent method) we must do some operations
ourself. When we update I would imagine some of these will disappear.
For now though, to determine the actual hierarchy we need the hierarchy
end point itself which will easily allow us to sort Spaces.
We do eventually need to clean up the filter as this will cause
repeat fetches for the space rooms for now.

We'll keep the re-frame portion here are well simply because I expect
this to be removed later.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(defn fetch-space-hierarchy [space-id]
  (let [client @(re-frame/subscribe [:sdk/client])
        base-url (.homeserver client)
        token (.. client -session -accessToken)
        ;;_ (js/console.log base-url)
        url (str base-url "/_matrix/client/v3/rooms/" space-id "/hierarchy")]
    (-> (js/fetch url #js {:headers #js {:Authorization (str "Bearer " token)}})
        (p/then #(.json %))
        (p/then (fn [json]
                  (let [resp (js->clj json :keywordize-keys true)]
                    (re-frame/dispatch [:rooms/process-hierarchy space-id (:rooms resp)])))))))
#+end_src

These are the reframe events and such associated with the fetch-space-hierarchy.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(re-frame/reg-event-db
 :rooms/process-hierarchy
 (fn [db [_ root-space-id rooms]]
   (let [hierarchy-orders
         (reduce
          (fn [acc room]
            (let [parent-id       (:room_id room)
                  children-events (:children_state room)]
              (if (seq children-events)
                (let [child-map (reduce
                                 (fn [cmap event]
                                   (if (= (:type event) "m.space.child")
                                     (let [child-id (:state_key event)
                                           order    (get-in event [:content :order] "zzzz")]
                                       (assoc cmap child-id order))
                                     cmap))
                                 {}
                                 children-events)]
                  (assoc acc parent-id child-map))
                acc)))
          {}
          rooms)]
     (log/debug "Corrected Space Orders:" hierarchy-orders)
     (update db :space-orders merge hierarchy-orders))))

(re-frame/reg-sub
 :rooms/space-orders
 (fn [db _]
   (get db :space-orders {})))

#+end_src


**** Rust Filters

We previously had filters in initial builds, but when we opted for a full reframe
style implementation we removed them. We'll add them back here. Effectively calling these
informs the Rust SDK that you wish to get a new Room List set.
As a result on space swapping we ALWAYS want to ensure we set back to "All" as
we rely on the list for our room list view behaviors (even if the space loads a
'dumb' version).
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(defn get-rust-filter [filter-id]
  (case filter-id
    "unread"
    (RoomListEntriesDynamicFilterKind.All.
      #js {:filters #js [(RoomListEntriesDynamicFilterKind.Unread.)
                         (RoomListEntriesDynamicFilterKind.DeduplicateVersions.)]})
    "people"
    (RoomListEntriesDynamicFilterKind.All.
      #js {:filters #js [(RoomListEntriesDynamicFilterKind.Category. #js {:expect RoomListFilterCategory.People})
                         (RoomListEntriesDynamicFilterKind.Joined.)
                         (RoomListEntriesDynamicFilterKind.DeduplicateVersions.)]})
    "favourite"
    (RoomListEntriesDynamicFilterKind.All.
      #js {:filters #js [(RoomListEntriesDynamicFilterKind.Favourite.)
                         (RoomListEntriesDynamicFilterKind.DeduplicateVersions.)]})

    (RoomListEntriesDynamicFilterKind.All.
      #js {:filters #js [(RoomListEntriesDynamicFilterKind.NonLeft.)
                         (RoomListEntriesDynamicFilterKind.DeduplicateVersions.)]})))
#+end_src


**** Home Room Lists

Prior we had a very verbose and repeated diffs check, but
as our timeline, spaces, and room list all share the same
general patterns to handling diffs we can consolidate them and
call them like so.
So all we need to do is ask reframe for the current global rooms
and call the diff check against those rooms and the updates
to set the "new" global rooms. This will make our global list
refresh automatically.
Later we can apply filters on it to induce specific behavior
like creating a DM grouping.

To add onto this, but we use a mutex to ensure that the rust-sdk
doesn't ever end up in a state where the diffs aren't readily
available to refresh our window. We don't slow the rust-sdk down,
but instead establish a queue for our code to process them
and notify reframe properly.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(defonce !room-mutex (atom (p/resolved nil)))
(defn apply-home-diffs-async! [updates]
  (swap! !room-mutex
         (fn [prev-promise]
           (p/then prev-promise
                   (fn []
                     (let [db @re-frame.db/app-db
                           current-rooms (get db :rooms [])
                           space-service (:space-service db)
                           client (:client db)]
                       (-> (apply-matrix-diffs current-rooms updates #(parse-room client space-service %))
                           (p/then (fn [next-rooms]
                                     (re-frame/dispatch-sync [:room-list/set-home-rooms-sync next-rooms])
                                     (re-frame/dispatch [:room-list/set-home-rooms next-rooms])))
                           (p/catch (fn [err]
                                      (log/error "Global Diff Panic:" err)
                                      nil)))))))))


(re-frame/reg-event-fx
 :room-list/home-rooms-diff
 (fn [_ [_ updates]]
   (apply-home-diffs-async! updates)
   {}))

(re-frame/reg-event-db
 :room-list/set-home-rooms-sync
 (fn [db [_ rooms]]
   (assoc db :rooms rooms)))

(re-frame/reg-event-fx
 :room-list/set-home-rooms
 (fn [_ [_ rooms]]
   (let [top-room-ids (take 5 (map #(.-id %) rooms))]
     {:dispatch [:sdk/preload-timelines top-room-ids]})))

(re-frame/reg-event-db
 :room-list/save-home-list-handle
 (fn [db [_ result]]
   (assoc db
          :home-list-result result
          :home-list-controller (.controller result))))

#+end_src



**** Global Room Lists


This is our source of truth list. We don't ever mutate this with a filter
or expect to reload it. The only mutations are the ones the Rust SDK sends
us to update the shape of the list itself.
We also initialize the parent evaluation here so we can build out our
space trees


It's becoming apparent that swapping filters is really not great for performance.
Instead we should explore what a multi-subscription design would look like.
If we can just keep DMs fresh and an all list fresh... We'll be doing great.
Issue is when using filters on the all list... is that list is literally
our source of truth. So we really should just keep it pure.
If we want to filter a background list then we can do whatever to that one.

I initially wrote this and a comment mentioning that I didn't think we could
nicely do the parent-child relationship mapping, however, having gone back
and revised a good bit it is now easily done here and we generate a nice
mapped structure for use everywhere. So we can easily look up rooms at O(1)
as well.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(defonce !bg-room-mutex (atom (p/resolved nil)))

(defn apply-bg-rooms-diffs! [updates]
  (swap! !bg-room-mutex
         (fn [prev-promise]
           (p/then prev-promise
                   (fn []
                     (let [db @re-frame.db/app-db
                           current-rooms (get db :bg-rooms-array #js [])
                           old-cache (get db :rooms-unfiltered-cache {})
                           space-service (:space-service db)
                           client (:client db)]
                       (-> (apply-matrix-diffs current-rooms updates #(parse-room client space-service %))
                           (p/then (fn [next-rooms]
                                     (doseq [r next-rooms]
                                       (let [id (or (.-id r) (.-roomId r) (aget r "roomId"))]
                                         (when-let [old-room (get old-cache id)]
                                           (when-let [pid (aget old-room "first-parent-id")]
                                             (aset r "parents" (aget old-room "parents"))
                                             (aset r "first-parent-id" pid)))))
                                     (re-frame/dispatch-sync [:room-list/set-bg-rooms-sync next-rooms])
                                     (doseq [r next-rooms]
                                       (when-not (aget r "first-parent-id")
                                         (let [id (or (.-id r) (.-roomId r) (aget r "roomId"))]
                                           (enqueue-parent-check! id))))
                                     (process-parent-queue!)))
                           (p/catch (fn [err]
                                      (log/error "Global Diff Panic:" err)
                                      nil)))))))))



(re-frame/reg-event-db
 :room-list/set-bg-rooms-sync
 (fn [db [_ rooms-list]]
   (let [rooms-map (reduce (fn [acc r]
                             (let [id (or (.-id r) (.-roomId r) (aget r "roomId"))]
                               (assoc acc id r)))
                           {}
                           rooms-list)]
     (assoc db
            :bg-rooms-array rooms-list
            :rooms-unfiltered-cache rooms-map))))

(re-frame/reg-event-db
 :room-list/save-bg-list-handle
 (fn [db [_ result]]
   (assoc db
     :bg-room-list-result result
     :bg-room-list-controller (.controller result))))

(re-frame/reg-event-fx
 :room-list/bg-rooms-diff
 (fn [_ [_ updates]]
   (apply-bg-rooms-diffs! updates)
   {}))



#+end_src


**** Initializing Room List Syncing

We can simplify (and diverge) from Aurora's implementation as View models are very rigid
and lock us into a certain pattern. Instead we'll just let reframe know the diff and let
it handle re-rendering directly.
This can be broken part a bit more for labeling purpose. For now though, it is easily
described as creating a set of entries (initializing the sliding sync frame size) and
then attaching an onUpdate to easily refresh those entries without much effort.
We apply a filter to ensure we don't end up with any duplication on the resulting room list and
apply it. Then we prompt the app to give us the first page for the controller.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs

(defn start-room-list-sync! [room-list]
  (log/debug "Starting Dual Room List Sync (UI + Background)")
  (p/let [ui-result (.entriesWithDynamicAdaptersWith room-list 200 true
                                               #js {:onUpdate #(re-frame/dispatch [:room-list/home-rooms-diff %])})
        ui-controller (.controller ui-result)
        bg-result (.entriesWithDynamicAdaptersWith room-list 200 true
                                               #js {:onUpdate #(re-frame/dispatch [:room-list/bg-rooms-diff %])})
        bg-controller (.controller bg-result)]

    (re-frame/dispatch [:room-list/set-filter "people"])
    (.setFilter ui-controller (get-rust-filter "people"))
    (.addOnePage ui-controller)
    (re-frame/dispatch [:room-list/save-home-list-handle ui-result])
    (.setFilter bg-controller (get-rust-filter "all"))
    (.addOnePage bg-controller)
    (re-frame/dispatch [:room-list/save-bg-list-handle bg-result])))
#+end_src


**** Space Tree Flattening

This is just a simple filter method to deduplicate
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(defn distinct-by [f coll]
  (let [!seen (atom #{})]
    (filterv (fn [x]
               (let [k (f x)]
                 (if (contains? @!seen k)
                   false
                   (do (swap! !seen conj k)
                       true))))
             coll)))


(defn safe-get [obj k-str k-kw]
  (if (map? obj)
    (get obj k-kw)
    (let [v (aget obj k-str)]
      (if (undefined? v)
        (aget obj (name k-kw))
        v))))

#+end_src


This provides a method to take the room map and turn it into a usable structure
to actually visualize our room lists. I'll come back and add more to this when
I add the call room previewing.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(defn flatten-tree [rooms-map children-map space-orders closed-drawers parent-id depth]
  (let [sdk-children    (get children-map parent-id [])
        manual-children (->> (vals rooms-map)
                             (filter #(= (safe-get % "first-parent-id" :first-parent-id) parent-id))
                             (map (fn [r] {:id        (or (safe-get r "id" :id) (safe-get r "roomId" :roomId))
                                           :is-space? (safe-get r "isSpace" :isSpace)})))

        orders-for-parent (get space-orders parent-id {})

        child-refs      (->> (concat sdk-children manual-children)
                             (distinct-by :id)
                             (sort-by #(get orders-for-parent (:id %) "zzzz"))
                             (vec))]
    (reduce
     (fn [acc {:keys [id is-space?]}]
       (let [summary       (get rooms-map id)
             item          {:id                 id
                            :is-space?          is-space?
                            :depth              depth
                            :activeRoomCallParticipants (when summary (safe-get summary "activeRoomCallParticipants" :activeRoomCallParticipants))

                            :name               (if summary (or (safe-get summary "name" :name) "Loading...") "Loading...")
                            :avatar             (when summary (safe-get summary "avatar" :avatar))
                            :unreadNotificationsCount (if summary (or (safe-get summary "unreadNotificationsCount" :unreadNotificationsCount) 0) 0)
                            :unreadMentionsCount    (if summary (or (safe-get summary "unreadMentionsCount" :unreadMentionsCount) 0) 0)}
             acc-with-item (conj acc item)]

         (if (and is-space? (not (contains? closed-drawers id)))
           (into acc-with-item (flatten-tree rooms-map children-map space-orders closed-drawers id (inc depth)))
           acc-with-item)))
     []
     child-refs)))


#+end_src


**** Room Global Reframe Components

There are our reframe pieces. I'll go into detail on each of them later on. For now this
is effectively a functioning *stub*.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(re-frame/reg-sub
 :rooms/active-id
 (fn [db _]
   (:active-room-id db)))

(re-frame/reg-sub
 :space-rooms
 (fn [db _]
   (vec (or (:space-rooms db) []))))

(re-frame/reg-sub
 :rooms/active-metadata
 :<- [:rooms/active-id]
 :<- [:rooms/unfiltered-indexed-map]
 (fn [[active-id rooms-map] _]
   (when active-id
     (get rooms-map active-id))))

(re-frame/reg-sub
 :rooms/all
 (fn [db _]
   (let [rooms (:rooms db)]
     (if (map? rooms) (vec (vals rooms)) (vec (or rooms []))))))
#+end_src


**** Room Reframe Subscriptions

Important to note that the Rust sdk delivers the resulting rooms in order
of recent activity. So if we use a broad stroke to handle all of them we lose
this valuable data. Instead we want to provide a simple 'parsed' map for
the DMs list or All rooms list as these are best served fresh first.
For the space rooms themselves we want to flatten as we have described
above.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(re-frame/reg-sub
 :rooms/indexed-map
 :<- [:rooms/all]
 (fn [rooms-list _]
   (reduce (fn [acc room]
             (let [id (or (aget room "id") (aget room "roomId"))]
               (assoc acc id room)))
           {}
           rooms-list)))


(re-frame/reg-sub
 :rooms/ordered-list
 (fn [db _]
   (get db :rooms [])))

(re-frame/reg-sub
 :rooms/current-view
 :<- [:spaces/active-id]
 :<- [:rooms/ordered-list]
 :<- [:rooms/unfiltered-indexed-map]
 :<- [:space-children/map]
 :<- [:rooms/space-orders]
 :<- [:rooms/closed-drawers]
 (fn [[active-id ordered-list indexed-map children-map space-orders closed-drawers] _]
   (if-not active-id
     ordered-list
     (flatten-tree indexed-map children-map space-orders closed-drawers active-id 0))))

(re-frame/reg-sub
 :rooms/unfiltered-indexed-map
 (fn [db _]
   (get db :rooms-unfiltered-cache {})))

#_(re-frame/reg-sub
 :rooms/active-room-members
 :<- [:rooms/active-id]
 (fn [active-id db]
   (get-in db [:rooms/members active-id] [])))

#_(re-frame/reg-event-fx
 :rooms/fetch-members
 (fn [{:keys [db]} [_ room-id]]
   (let [client (:client db)]
     (when (and client room-id)
       (if-let [room (.getRoom client room-id)]
         (p/let [members (.membersNoSync room)
                 parsed  (map (fn [m]
                                {:user-id      (.userId m)
                                 :display-name (or (.displayName m) (.userId m))
                                 :avatar-url   (.avatarUrl m)})
                              members)]
           (re-frame/dispatch [:rooms/save-members room-id parsed]))
         (log/warn "Could not find room in client for members fetch:" room-id))))
   {}))

#_(re-frame/reg-event-db
 :rooms/save-members
 (fn [db [_ room-id members]]
   (assoc-in db [:rooms/members room-id] members)))
#+end_src


**** Reframe Drawers


***** CSS

#+begin_src css :tangle ../../../css/room-list.css
.room-drawer-header {
    display: flex;
    align-items: center;
    padding: 18px 8px 4px 10px;
    font-size: 12px;
    font-weight: 700;
    color: #8e9297;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    cursor: pointer;
    user-select: none;
    transition: color 0.1s ease-in-out;
}

.room-drawer-header:hover {
    color: #ffffff;
}

.drawer-arrow {
    display: inline-block;
    width: 12px;
    height: 12px;
    line-height: 12px;
    margin-right: 4px;
    font-size: 8px;
    transition: transform 0.2s cubic-bezier(0.4, 0, 0.2, 1);
    color: #6a6d71;
}

.room-drawer-header.collapsed .drawer-arrow {
    transform: rotate(-90deg);
}
#+end_src


***** Reframe components

#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs

(re-frame/reg-event-db
 :rooms/toggle-drawer
 (fn [db [_ drawer-id]]
   (update-in db [:ui :closed-drawers]
              (fn [closed]
                (if (contains? closed drawer-id)
                  (disj closed drawer-id)
                  (conj (or closed #{}) drawer-id))))))

(re-frame/reg-sub
 :rooms/closed-drawers
 (fn [db _]
   (get-in db [:ui :closed-drawers] #{})))


#+end_src


**** Notifications and unread data

So notification handling is actually a fairly annoying process if we want the
smooth visual users expect. We need to bubble up the unread count for every
room within a space. This meant we needed to have the parent-child relationships
mapped out and then flatten them into a calculatable total.
The parent-child mapping process is documented above, but amusingly is
one of the more complex aspects of spaces and rooms.

To a much easier degree, we need to also calculate the unread count for DMs.
This is mostly useful for presenting that info on the space bar cleanly.
Otherwise we would just re-use (and probably should see if we can)
the method we have for all other rooms.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(re-frame/reg-sub
 :space/unread-stats
 :<- [:rooms/unfiltered-indexed-map]
 :<- [:space-children/map]
 :<- [:rooms/space-orders]
 (fn [[rooms-map children-map space-orders] [_ space-id]]
  ;; (log/error space-id)
   (let [rooms-in-space (flatten-tree rooms-map children-map space-orders #{} space-id 0)
    ;;     _ (log/error rooms-in-space)
         stats (reduce (fn [acc room]
                         (let [notifs (get room :unreadNotificationsCount 0)
                               mentions (get room :unreadMentionsCount 0)]
                           (-> acc
                               (update :notifs + notifs)
                               (update :mentions + mentions))))
                       {:notifs 0 :mentions 0}
                       rooms-in-space)
  ;;       _ (log/error stats)
          ]
     {:unread? (pos? (:notifs stats))
      :notif-count (:notifs stats)
      :mentions (:mentions stats)
      :highlight? (pos? (:mentions stats))})))

(re-frame/reg-sub
 :rooms/active-dm-pops
 :<- [:rooms/unfiltered-indexed-map]
 (fn [rooms-map _]
   (->> (vals rooms-map)
        (filter #(aget % "isDirect"))
        (filter #(pos? (or (aget % "unreadMessagesCount") 0)))
        (sort-by #(or (aget % "last_message_ts") 0) >)
        (map (fn [r]
               (let [msg-count (or (aget r "unreadMessagesCount") 0)
                     mentions  (or (aget r "unreadMentionsCount") 0)]
                 {:id         (aget r "id")
                  :name       (aget r "name")
                  :avatar-url (aget r "avatar")
                  :is-dm?     true
                  :unread?    (pos? msg-count)
                  :highlight? (pos? mentions)
                  :mentions   msg-count}))))))
#+end_src


**** Room Selection

Selection is likely the biggest component of rooms as far as users are concerned.
This mechanism actually has to fulfill a few roles such as correctly entering
the correct state for calling or opening the correct panels given the current
view state.

****** TODO Fix the actual swap impl.
Stopped and just stubbed it in for now while I go back and clean up the CSS
and file structures.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(re-frame/reg-event-fx
 :rooms/select
 (fn [{:keys [db]} [_ room-id opts]]
   (let [current-room-id (:active-room-id db)
         active-call-id  (get-in db [:call :active-room-id])
         already-loaded? (get-in db [:room-members room-id :data])
         loading?        (get-in db [:room-members room-id :loading?])
         is-call-room?   (room-type-call? db room-id)
         force-lobby?    (:force-lobby? opts)
         focus-override  (:focus-override opts)
         mobile?         (get-in db [:ui :mobile?])
         join-directly?  (if force-lobby? false (not mobile?))
         wipe-call-state? (not is-call-room?)
         swapping-calls? (and active-call-id (not= active-call-id room-id) is-call-room?)
         current-side-panel (get-in db [:ui :side-panel])
         _ (log/error )
         _ (log/error current-side-panel)
         side-panel-update  (if (and (= current-side-panel :timeline)
                                     (= new-focus :timeline)
                                     (not focus-override))
                              nil
                              current-side-panel)]

     (if (= current-room-id room-id)
       {:db (assoc-in db [:ui :sidebar-open?] false)}

       (let [new-focus ;; (or focus-override
                            (if is-call-room? :call :timeline)
                         ;;   )
             base-db    (-> db
                            (assoc :active-room-id room-id)
                            (assoc-in [:ui :sidebar-open?] false)
                            (assoc-in [:ui :main-focus] new-focus))

             dispatches (remove nil?
                                [(when current-room-id [:sdk/cleanup-timeline current-room-id])
                                 (when swapping-calls? [:call/hangup {:wipe-state? wipe-call-state?}])
                                 [:sdk/boot-timeline room-id]
                                 (when (not (or already-loaded? loading?)) [:room/fetch-members room-id])
                                 [:sdk/fetch-room-emotes :room room-id]
                                 [:composer/load-draft room-id]
                                 [:container/set-main-focus new-focus]
                                 (when focus-override [:container/set-side-panel focus-override])
                                 (when (and (= current-side-panel :timeline) (nil? side-panel-update))
                                   [:container/set-side-panel nil])
                                 (when is-call-room? [:call/init-widget room-id {:join-directly? join-directly?}])])]
         {:db base-db
          :dispatch-n dispatches})))))

#+end_src





#+begin_src css :tangle ../../../css/room-list.css


#+end_src


**** Filter Selection

While setting filters isn't the most resource friendly implementation
for now it is an easy and clean way to provide a sorted list to the
user. We'll have to see how it scales as I suspect it is causing the
entire room list to reload. Hopefully not.

***** Reframe events and subscriptions

#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(re-frame/reg-event-db
 :room-list/set-filter
 (fn [db [_ filter-id]]
   (assoc db :active-filter-id filter-id)))

(re-frame/reg-sub
 :room-list/active-filter
 (fn [db _]
   (get db :active-filter-id "people")))

(re-frame/reg-event-fx
 :room-list/apply-filter
 (fn [{:keys [db]} [_ filter-id]]
   (let [current-filter (:active-filter-id db)
         controller     (:home-list-controller db)]
     (cond
       (= current-filter filter-id)
       (do (log/debug "Filter already set to:" filter-id)
           {})

       (not controller)
       (do (log/warn "Filter swap failed: No room-list-controller found.")
           {})

       :else
       (do
         (log/debug "Swapping filter from" current-filter "to" filter-id)
         (.setFilter controller (get-rust-filter filter-id))
         (.addOnePage controller)
         {:db (assoc db :active-filter-id filter-id)})))))

#+end_src

***** Reagent component

#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(defn filter-toggle-bar []
  (let [tr            @(re-frame/subscribe [:i18n/tr])
        active-filter @(re-frame/subscribe [:room-list/active-filter])]
    [:div.filter-bar
     (for [[id label-key] [["all"    :navigation.room-list.filters/all]
                           ["unread" :navigation.room-list.filters/unread]
                           ["people" :navigation.room-list.filters/people]]]
       ^{:key id}
       [:button.filter-btn
        {:class    (when (= active-filter id) "active")
         :on-click #(re-frame/dispatch [:room-list/apply-filter id])}
        (tr [label-key])])]))

#+end_src

***** CSS

Now the CSS for the filter is relatively simple
#+begin_src css :tangle ../../../css/room-list.css
.filter-bar {
    display: flex;
    gap: 8px;
    padding: 10px 16px;
    background-color: #2b2d31;
    border-bottom: 1px solid #1e1f22;
    overflow-x: auto;
    scrollbar-width: none;
}

.filter-bar::-webkit-scrollbar {
    display: none;
}

.filter-btn {
    background: transparent;
    color: #949ba4;
    border: 1px solid transparent;
    border-radius: 16px;
    cursor: pointer;
    padding: 4px 12px;
    font-size: 13px;
    font-weight: 500;
    white-space: nowrap;
    transition: all 0.15s ease-in-out;
}

.filter-btn:hover {
    background-color: #35373c;
    color: #dbdee1;
}

.filter-btn.active {
    background-color: #404249;
    color: #ffffff;
    border-color: transparent;
}
#+end_src


**** Virtuoso for Room List

Our virtualized room list. We ensure our rooms are in an array form
for consumption by Virtuoso and then instruct Virtuoso to ask
reframe for the next "page" upon reaching the end of its display.
We assign the data to be represented as the room array itself.
Now, we can also add nifty behavior for the content itself by then
checking for the "kind" of room. For now though, this is plenty sufficient.

#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(defn virtualized-room-list [tr client room-array active-space active-room closed-drawers active-filter]
  (let [item-renderer (render-room-item tr client room-array active-space active-room closed-drawers active-filter)]
    [:> Virtuoso
     {:style {:height "100%" :width "100%"}
      :data room-array
      :endReached #(re-frame/dispatch [:room-list/paginate-global])
      :itemContent item-renderer}]))
#+end_src






**** Room List Component



Now for the CSS
#+begin_src css :tangle ../../../css/room-list.css
.sidebar-rooms {
    width: 240px;
    flex-shrink: 0;
    background-color: #2b2d31;
    display: flex;
    flex-direction: column;
    padding: 12px;
    height: 100%;
}

.room-header {
    display: flex;
    align-items: center;
    padding: 0 16px;
    height: 48px;
    border-bottom: 1px solid #1e1f22;
    background: #313338;
    min-width: 0;
}

@media (max-width: 768px) {
    .sidebar-rooms {
        width: calc(100vw - 72px);
        max-width: 240px;
      }
}


.room-layout {
    flex: 1;
    height: 100vh;
    display: grid;
    overflow: hidden;
}

.room-collection {
    flex: 1;
    min-height: 0;
}

.room-header {
    display: flex;
    align-items: center;
    padding: 0 16px;
    height: 48px;
    border-bottom: 1px solid #1e1f22;
    background: #313338;
    min-width: 0;
}

.room-name {
    font-weight: 600;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    flex: 0 1 auto;
}

#+end_src


Now for our room list component itself, we have three subscriptions requested from reframe
We want to make sure the component updates if our rooms change, our active space changes,
or our active room changes. We then add some decorating Hiccup around it to round out the
component.
#+begin_src clojurescript :tangle ../../../src/navigation/rooms/room_list.cljs
(defn room-list []
  (let [tr              @(re-frame/subscribe [:i18n/tr])
        rooms           @(re-frame/subscribe [:rooms/current-view])
        active-room     @(re-frame/subscribe [:rooms/active-id])
        active-space    @(re-frame/subscribe [:spaces/active-metadata])
        closed-drawers  @(re-frame/subscribe [:rooms/closed-drawers])
        active-filter   @(re-frame/subscribe [:room-list/active-filter])
        client          @(re-frame/subscribe [:sdk/client])
        room-array      (to-array rooms)]
    [:div.sidebar-rooms
     [:div.room-list-header

      (if active-space
        [:h3.room-list-header (:name active-space)]
        [:h3.room-list-header (tr [:navigation.room-list.headers/home])])]
     (when-not active-space
       [filter-toggle-bar])
     (if (or (nil? room-array) (== (alength room-array) 0))
       [:div.empty-state (tr [:navigation.room-list.empty-state/no-rooms])]
       [:div.room-collection
        [virtualized-room-list tr client room-array active-space active-room closed-drawers active-filter]])
     [active-call-panel]]))
#+end_src



**** CSS (Needs testing)


#+begin_src css
.room-drawer-header {
    display: flex;
    align-items: center;
    padding: 18px 8px 4px 10px;
    font-size: 12px;
    font-weight: 700;
    color: #8e9297;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    cursor: pointer;
    user-select: none;
    transition: color 0.1s ease-in-out;
}

.room-drawer-header:hover {
    color: #ffffff;
}

.drawer-arrow {
    display: inline-block;
    width: 12px;
    height: 12px;
    line-height: 12px;
    margin-right: 4px;
    font-size: 8px;
    transition: transform 0.2s cubic-bezier(0.4, 0, 0.2, 1);
    color: #6a6d71;
}

.room-drawer-header.collapsed .drawer-arrow {
    transform: rotate(-90deg);
}



.filter-bar {
    display: flex;
    gap: 8px;
    padding: 10px 16px;
    background-color: #2b2d31;
    border-bottom: 1px solid #1e1f22;
    overflow-x: auto;
    scrollbar-width: none;
}

.filter-bar::-webkit-scrollbar {
    display: none;
}

.filter-btn {
    background: transparent;
    color: #949ba4;
    border: 1px solid transparent;
    border-radius: 16px;
    cursor: pointer;
    padding: 4px 12px;
    font-size: 13px;
    font-weight: 500;
    white-space: nowrap;
    transition: all 0.15s ease-in-out;
}

.filter-btn:hover {
    background-color: #35373c;
    color: #dbdee1;
}

.filter-btn.active {
    background-color: #404249;
    color: #ffffff;
    border-color: transparent;
}

.sidebar-rooms {
    width: 240px;
    flex-shrink: 0;
    background-color: #2b2d31;
    display: flex;
    flex-direction: column;
    padding: 12px;
}

.sidebar-rooms {
    width: 240px;
    flex-shrink: 0;
    background-color: #2b2d31;
    display: flex;
    flex-direction: column;
    padding: 12px;
}

.room-list-header {
    display: flex;
    align-items: center;
    padding: 0 16px;
    height: 48px;
    /* border-bottom: 1px solid #1e1f22; */
    background: #313338;
    min-width: 0;
}

@media (max-width: 768px) {
    .sidebar-rooms {
        width: calc(100vw - 72px);
        max-width: 240px;
      }
}


.room-layout {
    flex: 1;
    height: 100vh;
    display: grid;
    overflow: hidden;
}

.room-header {
    display: flex;
    align-items: center;
    padding: 0 16px;
    height: 48px;
    border-bottom: 1px solid #1e1f22;
    background: #313338;
    min-width: 0;
}

.room-name {
    font-weight: 600;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    flex: 0 1 auto;
}


#+end_src
